begin;
select no_plan();
-- Entire ordinary suite rolls back. Concurrency runs use these same fixtures in a throwaway database.
create function pg_temp.sid(x text) returns uuid language sql immutable as $$select md5('communications-' ||x)::uuid$$;
create function pg_temp.cmd(a text,d jsonb) returns jsonb language sql as $$select public.product_command(a,d,gen_random_uuid())$$;
insert into auth.users(id,email,raw_user_meta_data,email_confirmed_at)
select pg_temp.sid(x),x||'-communications@example.test',jsonb_build_object('name',x),now() from unnest(array['owner','coach','other-coach','branch','parent','other-parent']) x;
insert into public.role_assignments values (pg_temp.sid('owner'),'super_admin'),(pg_temp.sid('coach'),'coach'),(pg_temp.sid('other-coach'),'coach'),(pg_temp.sid('branch'),'branch');
insert into public.branches(id,slug,name,provisional) values(pg_temp.sid('branch-a'),'communications-test-a','Synthetic schedule branch',false),(pg_temp.sid('branch-b'),'communications-test-b','Other schedule branch',false);
insert into public.branch_sports values(pg_temp.sid('branch-a'),'swimming'),(pg_temp.sid('branch-b'),'swimming');
insert into public.branch_permissions select pg_temp.sid(x),pg_temp.sid('branch-a') from unnest(array['coach','other-coach','branch']) x;
insert into public.branch_permissions values(pg_temp.sid('other-coach'),pg_temp.sid('branch-b'));
insert into public.venues(id,branch_id,name,address) values(pg_temp.sid('venue-a'),pg_temp.sid('branch-a'),'Source pool','Synthetic'),(pg_temp.sid('venue-b'),pg_temp.sid('branch-b'),'Target pool','Synthetic');
insert into public.sport_levels(id,sport,name,rank) values(pg_temp.sid('level'),'swimming','Communications test level',321);
insert into public.age_groups(id,name,min_age,max_age) values(pg_temp.sid('ages'),'Communications test ages',5,10);
insert into public.academy_classes(id,branch_id,venue_id,coach_id,sport,level_id,age_group_id,name,capacity,weekdays,local_time,duration_minutes)
values(pg_temp.sid('class-a'),pg_temp.sid('branch-a'),pg_temp.sid('venue-a'),pg_temp.sid('coach'),'swimming',pg_temp.sid('level'),pg_temp.sid('ages'),'Source class',5,array[0],'17:00',60),
(pg_temp.sid('class-b'),pg_temp.sid('branch-b'),pg_temp.sid('venue-b'),pg_temp.sid('other-coach'),'swimming',pg_temp.sid('level'),pg_temp.sid('ages'),'Target class',5,array[0],'17:00',60);
insert into public.class_sessions(id,class_id,starts_at,ends_at,capacity)
select pg_temp.sid(x),pg_temp.sid('class-a'),now()+d,now()+d+interval '1 hour',5 from (values('past',interval '-2 hours'),('earlier',interval '1 day'),('anchor',interval '2 days'),('adjacent',interval '2 days 1 hour')) v(x,d);
insert into public.class_sessions(id,class_id,starts_at,ends_at,capacity) values(pg_temp.sid('target'),pg_temp.sid('class-b'),now()+interval '4 days',now()+interval '4 days 1 hour',1),(pg_temp.sid('race'),pg_temp.sid('class-a'),now()+interval '10 days',now()+interval '10 days 1 hour',1);
insert into public.families(id,name) values(pg_temp.sid('family'),'Schedule test family'),(pg_temp.sid('other-family'),'Other schedule family');
insert into public.guardians values(pg_temp.sid('family'),pg_temp.sid('parent')),(pg_temp.sid('other-family'),pg_temp.sid('other-parent'));
insert into public.family_branches values(pg_temp.sid('family'),pg_temp.sid('branch-a')),(pg_temp.sid('other-family'),pg_temp.sid('branch-a'));
insert into public.children(id,family_id,name,reported_age,age_captured_on) values(pg_temp.sid('child'),pg_temp.sid('family'),'Schedule Athlete',7,current_date),(pg_temp.sid('other-child'),pg_temp.sid('other-family'),'Other Athlete',7,current_date),(pg_temp.sid('trial-child'),pg_temp.sid('other-family'),'Trial Athlete',7,current_date);
insert into public.child_sports(child_id,sport,level_id,level,status) select pg_temp.sid(x),'swimming',pg_temp.sid('level'),'Communications test level','reviewed' from unnest(array['child','other-child','trial-child']) x;
insert into public.enrollments(id,child_id,class_id) values(pg_temp.sid('enrollment'),pg_temp.sid('child'),pg_temp.sid('class-a')),(pg_temp.sid('other-enrollment'),pg_temp.sid('other-child'),pg_temp.sid('class-a'));
insert into public.session_roster(id,session_id,enrollment_id,kind,attendance) values(pg_temp.sid('past-roster'),pg_temp.sid('past'),pg_temp.sid('enrollment'),'enrollment','present'),(pg_temp.sid('anchor-roster'),pg_temp.sid('anchor'),pg_temp.sid('enrollment'),'enrollment',null);
update public.class_sessions set finalized_at=now(),status='completed' where id=pg_temp.sid('past');

insert into auth.users(id,email,raw_user_meta_data,email_confirmed_at) select pg_temp.sid(x),x||'-communications@example.test',jsonb_build_object('name',x,'roles',jsonb_build_array('super_admin')),now() from unnest(array['sales','co-guardian','multi-parent','admin']) x;
delete from public.role_assignments where user_id=pg_temp.sid('sales');
insert into public.role_assignments values(pg_temp.sid('sales'),'sales'),(pg_temp.sid('admin'),'admin');
insert into public.branch_permissions values(pg_temp.sid('sales'),pg_temp.sid('branch-a'));
insert into public.guardians values(pg_temp.sid('family'),pg_temp.sid('co-guardian')),(pg_temp.sid('family'),pg_temp.sid('multi-parent')),(pg_temp.sid('other-family'),pg_temp.sid('multi-parent'));
insert into public.consent_records(family_id,actor_id,kind,version,granted,created_at) values(pg_temp.sid('family'),pg_temp.sid('parent'),'contact','test-v1',true,now()-interval '3 hours'),(pg_temp.sid('other-family'),pg_temp.sid('other-parent'),'contact','test-v1',false,now()-interval '3 hours');
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('owner'),'role','authenticated','aal','aal2')::text,true);
select set_config('test.comm.template',pg_temp.cmd('communication.template.create',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'name','Communications test notice','language','en','purpose','operational','subject','First operational notice','body','Your academy session details are ready.'))->>'id',true);
select set_config('test.comm.marketing',pg_temp.cmd('communication.template.create',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'name','Communications test marketing','language','ar','purpose','marketing','subject','إعلان الأكاديمية','body','تعرّف على أنشطة الأكاديمية الجديدة.'))->>'id',true);
select lives_ok($$select pg_temp.cmd('communication.template.create',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'name','Communications test notice','language','en','purpose','operational','subject','Second operational notice','body','This is a new immutable template version.'))$$,'Template changes create a versioned record');
select is((select max(version) from public.communication_templates where name='Communications test notice' and language='en'),2,'English template versions increment independently');
select is((select body from public.communication_templates where id=current_setting('test.comm.template')::uuid),'Your academy session details are ready.','Existing template content stays unchanged');
select throws_ok($$update public.communication_templates set body='Unauthorized direct template replacement' where id=current_setting('test.comm.template')::uuid$$,'42501',null,'Authenticated users cannot rewrite approved template records directly');
select is(jsonb_array_length(pg_temp.cmd('communication.preview',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.template')))->'recipients'),4,'Preview deduplicates one guardian across two branch families');
select is(jsonb_array_length(pg_temp.cmd('communication.preview',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.marketing')))->'recipients'),3,'Marketing preview requires current family contact consent');
select is(pg_temp.cmd('communication.preview',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.template')))->>'external','not_configured','Preview makes external provider state explicit');
select throws_ok($$select pg_temp.cmd('communication.schedule',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.template'),'scheduled_at',now()+interval '1 day'))$$,'22023',null,'Recipient confirmation is required by SQL');
select set_config('test.comm.future',pg_temp.cmd('communication.schedule',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.template'),'scheduled_at',now()+interval '1 day','confirmed',true))->>'id',true);
select throws_ok($$select pg_temp.cmd('communication.dispatch',jsonb_build_object('id',current_setting('test.comm.future')))$$,'P0409',null,'Future batch cannot dispatch early');
select lives_ok($$select pg_temp.cmd('communication.cancel',jsonb_build_object('id',current_setting('test.comm.future')))$$,'Authorized operator can cancel a scheduled batch');
select throws_ok($$select pg_temp.cmd('communication.dispatch',jsonb_build_object('id',current_setting('test.comm.future')))$$,'P0409',null,'Cancelled batch cannot dispatch');
select set_config('test.comm.due',pg_temp.cmd('communication.schedule',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.template'),'scheduled_at',now()-interval '1 minute','confirmed',true))->>'id',true);
select lives_ok($$select pg_temp.cmd('communication.dispatch',jsonb_build_object('id',current_setting('test.comm.due')))$$,'Due operational broadcast dispatches in-app');
select lives_ok($$select pg_temp.cmd('communication.dispatch',jsonb_build_object('id',current_setting('test.comm.due')))$$,'Repeated dispatch with a new request key is idempotent');
select throws_ok($$select pg_temp.cmd('communication.cancel',jsonb_build_object('id',current_setting('test.comm.due')))$$,'P0409',null,'Published communication cannot be recalled as a scheduled draft');
reset role;
select is((select count(*)::int from public.notifications n join public.product_events e on e.id=n.event_id where e.entity_id=current_setting('test.comm.due')::uuid),4,'One notification per actual recipient even across multiple family links');
select is((select count(*)::int from public.delivery_outbox o join public.product_events e on e.id=o.event_id where e.entity_id=current_setting('test.comm.due')::uuid and o.status='not_configured'),12,'External attempts remain not configured with no false delivery claim');
select is((select count(distinct n.body)::int from public.notifications n join public.product_events e on e.id=n.event_id where e.entity_id=current_setting('test.comm.due')::uuid and n.body='Your academy session details are ready.'),1,'Dispatch uses the selected immutable template version');
insert into public.consent_records(family_id,actor_id,kind,version,granted,created_at) values(pg_temp.sid('other-family'),pg_temp.sid('other-parent'),'contact','test-v2',true,now()-interval '2 hours');
set local role authenticated;
select set_config('test.comm.marketingbatch',pg_temp.cmd('communication.schedule',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.marketing'),'scheduled_at',now()-interval '1 minute','confirmed',true))->>'id',true);
select set_config('test.comm.expectedmarketing',(select count(*)::text from public.communication_recipients where batch_id=current_setting('test.comm.marketingbatch')::uuid and family_id=pg_temp.sid('family') and user_id<>pg_temp.sid('co-guardian')),true);
reset role;
-- Authority and consent are rechecked at dispatch, not frozen by the preview.
delete from public.guardians where user_id=pg_temp.sid('co-guardian');
insert into public.consent_records(family_id,actor_id,kind,version,granted,created_at) values(pg_temp.sid('other-family'),pg_temp.sid('other-parent'),'contact','test-v3',false,now()-interval '1 hour');
update public.profiles set active=false where id=pg_temp.sid('other-parent');
set local role authenticated;
select lives_ok($$select pg_temp.cmd('communication.dispatch',jsonb_build_object('id',current_setting('test.comm.marketingbatch')))$$,'Due dispatch resolves current consent and guardian revocations');
reset role;
select is((select count(*)::int from public.notifications n join public.product_events e on e.id=n.event_id where e.entity_id=current_setting('test.comm.marketingbatch')::uuid),current_setting('test.comm.expectedmarketing')::int,'Only selected-family recipients still authorized and consenting receive marketing');
select is((select count(*)::int from public.notifications n join public.product_events e on e.id=n.event_id where e.entity_id=current_setting('test.comm.marketingbatch')::uuid and n.recipient_id in(pg_temp.sid('co-guardian'),pg_temp.sid('other-parent'))),0,'Revoked guardian and suspended parent receive no queued publication');
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('co-guardian'),'role','authenticated','aal','aal1')::text,true);
select is((select count(*)::int from public.notifications),0,'Guardian revocation hides previous family notification content');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('other-parent'),'role','authenticated','aal','aal1')::text,true);
select is((select count(*)::int from public.notifications),0,'Suspended account cannot read previous notifications');
select throws_ok($$select pg_temp.cmd('communication.preview',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.template')))$$,'42501',null,'Suspended account cannot enter product commands');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('sales'),'role','authenticated','aal','aal1')::text,true);
select is((select count(*)::int from public.communication_recipients),0,'Sales cannot read campaign recipient identities');
select throws_ok($$select pg_temp.cmd('communication.preview',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.template')))$$,'42501',null,'Sales cannot preview guardian recipients');
select throws_ok($$select pg_temp.cmd('communication.dispatch',jsonb_build_object('id',current_setting('test.comm.due')))$$,'42501',null,'Even a sent batch cannot leak through sales dispatch retries');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('parent'),'role','authenticated','aal','aal1','user_metadata',jsonb_build_object('roles',jsonb_build_array('super_admin')))::text,true);
select ok(not ((public.account_context()->'roles') ? 'super_admin'),'Account context ignores forged metadata role claims');
select throws_ok($$select pg_temp.cmd('communication.template.create',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'name','Forged privilege','language','en','purpose','operational','subject','Unauthorized','body','Forged metadata must not authorize a broadcast.'))$$,'42501',null,'Forged role metadata grants no communications authority');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('owner'),'role','authenticated','aal','aal1')::text,true);
select throws_ok($$select pg_temp.cmd('communication.preview',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.template')))$$,'42501',null,'Owner requires current AAL2 even for recipient preview');
-- Explicit permissions remain scoped and are rechecked at execution, including cached previews.
reset role;
insert into public.product_permissions(user_id,permission,branch_id) values(pg_temp.sid('admin'),'communications.broadcast',pg_temp.sid('branch-a')),(pg_temp.sid('branch'),'communications.broadcast',pg_temp.sid('branch-a')),(pg_temp.sid('sales'),'communications.broadcast',pg_temp.sid('branch-a'));
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('sales'),'role','authenticated','aal','aal1')::text,true);
select throws_ok($$select pg_temp.cmd('communication.preview',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.template')))$$,'42501',null,'A product grant cannot turn a sales account into a broadcaster');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('branch'),'role','authenticated','aal','aal1')::text,true);
select throws_ok($$select pg_temp.cmd('communication.preview',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.template')))$$,'42501',null,'Broadcasts remain HeadOffice-only even with a Branch product grant');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('admin'),'role','authenticated','aal','aal1')::text,true);
select lives_ok($$select public.product_command('communication.preview',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.template')),pg_temp.sid('preview-key'))$$,'Explicitly authorized HeadOffice reviewer can preview its permitted branch');
select throws_ok($$select pg_temp.cmd('communication.preview',jsonb_build_object('branch_id',pg_temp.sid('branch-b'),'template_id',current_setting('test.comm.template')))$$,'42501',null,'Broadcast grant cannot cross branch scope');
select ok((select count(*) from public.communication_templates where id=current_setting('test.comm.template')::uuid)>0,'Authorized HeadOffice reviewer can load the template needed by its broadcast UI');
select set_config('test.comm.branchbatch',pg_temp.cmd('communication.schedule',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.template'),'scheduled_at',now()-interval '1 minute','confirmed',true))->>'id',true);
reset role;
delete from public.product_permissions where user_id=pg_temp.sid('admin');
set local role authenticated;
select throws_ok($$select pg_temp.cmd('communication.dispatch',jsonb_build_object('id',current_setting('test.comm.branchbatch')))$$,'42501',null,'Permission revocation prevents dispatch of an already scheduled batch');
select throws_ok($$select pg_temp.cmd('communication.preview',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.template')))$$,'42501',null,'Permission revocation prevents a fresh recipient preview');
select throws_ok($$select public.product_command('communication.preview',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.template')),pg_temp.sid('preview-key'))$$,'42501',null,'Permission revocation also prevents replay of cached guardian identities');
-- A shared class must not expand a family's child projection.
reset role;
update public.profiles set active=true where id=pg_temp.sid('other-parent');
insert into public.session_roster(session_id,enrollment_id,kind) values(pg_temp.sid('anchor'),pg_temp.sid('other-enrollment'),'enrollment');
insert into public.leads(id,branch_id,parent_name,mobile,family_id) values(pg_temp.sid('linked-lead'),pg_temp.sid('branch-a'),'Former guardian','+971500099901',pg_temp.sid('family')),(pg_temp.sid('unlinked-lead'),pg_temp.sid('branch-b'),'Unlinked trial parent','+971500099902',null);
insert into public.trial_enquiries(id,lead_id,submitted_by,child_id,child_name,reported_age,sport,experience,starting_level_id) values(pg_temp.sid('linked-enquiry'),pg_temp.sid('linked-lead'),pg_temp.sid('co-guardian'),pg_temp.sid('child'),'Schedule Athlete',7,'swimming','beginner',pg_temp.sid('level')),(pg_temp.sid('unlinked-enquiry'),pg_temp.sid('unlinked-lead'),pg_temp.sid('parent'),null,'Unlinked trial child',7,'swimming','beginner',pg_temp.sid('level'));
insert into public.trial_bookings(id,enquiry_id,session_id,level_id) values(pg_temp.sid('linked-trial'),pg_temp.sid('linked-enquiry'),pg_temp.sid('race'),pg_temp.sid('level')),(pg_temp.sid('unlinked-trial'),pg_temp.sid('unlinked-enquiry'),pg_temp.sid('target'),pg_temp.sid('level'));
insert into public.session_roster(session_id,trial_booking_id,kind) values(pg_temp.sid('race'),pg_temp.sid('linked-trial'),'trial'),(pg_temp.sid('target'),pg_temp.sid('unlinked-trial'),'trial');
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('parent'),'role','authenticated','aal','aal1')::text,true);
select is((select jsonb_array_length(s->'students') from jsonb_array_elements(public.family_schedule()) s where s->>'id'=pg_temp.sid('anchor')::text),1,'Family schedule includes only own child in a mixed-family session');
select is((select s->'students'->0->>'id' from jsonb_array_elements(public.family_schedule()) s where s->>'id'=pg_temp.sid('anchor')::text),pg_temp.sid('child')::text,'Family projection keeps the actual authorized child identity');
select is((select s->'students'->0->>'name' from jsonb_array_elements(public.family_schedule()) s where s->>'id'=pg_temp.sid('target')::text),'Unlinked trial child','Submitter still sees their own trial before a family child is linked');
select is(jsonb_array_length(public.development_sessions()),0,'Parent cannot use coach projection for classmates');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('co-guardian'),'role','authenticated','aal','aal1')::text,true);
select is(jsonb_array_length(public.family_schedule()),0,'Historical enquiry submitter loses linked-child schedule after guardian revocation');
select is((select count(*)::int from public.session_roster where trial_booking_id=pg_temp.sid('linked-trial')),0,'Raw roster RLS also revokes historical submitter access to linked child');
select is((select count(*)::int from public.trial_enquiries where id=pg_temp.sid('linked-enquiry')),0,'Raw enquiry RLS cannot bypass guardian revocation for linked child');
select is((select count(*)::int from public.trial_bookings where id=pg_temp.sid('linked-trial')),0,'Raw trial booking RLS cannot bypass guardian revocation');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('sales'),'role','authenticated','aal','aal1')::text,true);
select is(jsonb_array_length(public.family_schedule()),0,'Sales does not inherit parent schedule from default signup metadata');
select is(jsonb_array_length(public.development_sessions()),0,'Sales cannot inspect assigned coach roster projection');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('coach'),'role','authenticated','aal','aal1')::text,true);
select is((select jsonb_array_length(s->'students') from jsonb_array_elements(public.development_sessions()) s where s->>'id'=pg_temp.sid('anchor')::text),2,'Current coach sees only the assigned session roster');
select ok(public.development_sessions()::text !~ '"(family_id|mobile|email|dob)"','Coach-safe projection carries no family contact or financial identity');
reset role;
update public.academy_classes set active=false where id=pg_temp.sid('class-a');
set local role authenticated;
select is((select coalesce(sum(jsonb_array_length(s->'students')),0)::int from jsonb_array_elements(public.development_sessions()) s where s->>'class_id'=pg_temp.sid('class-a')::text),0,'Inactive-class notices do not keep child roster identities visible');
select is((select coalesce(sum(jsonb_array_length(s->'students')),0)::int from jsonb_array_elements(public.coach_sessions()) s where s->>'id' in(pg_temp.sid('anchor')::text,pg_temp.sid('race')::text,pg_temp.sid('past')::text)),0,'Legacy coach projection cannot bypass inactive-class roster privacy');
reset role;
update public.academy_classes set active=true where id=pg_temp.sid('class-a');
insert into public.coach_substitutions(id,session_id,coach_id,starts_at,ends_at,reason) values(pg_temp.sid('substitution'),pg_temp.sid('anchor'),pg_temp.sid('other-coach'),now()-interval '1 hour',now()+interval '1 hour','Synthetic current replacement');
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('other-coach'),'role','authenticated','aal','aal1')::text,true);
select is((select jsonb_array_length(s->'students') from jsonb_array_elements(public.development_sessions()) s where s->>'id'=pg_temp.sid('anchor')::text),2,'Current permitted substitute receives assigned roster projection');
reset role;
update public.coach_substitutions set revoked_at=now() where id=pg_temp.sid('substitution');
set local role authenticated;
select is((select count(*)::int from jsonb_array_elements(public.development_sessions()) s where s->>'id'=pg_temp.sid('anchor')::text),0,'Substitute revocation removes the session immediately');
-- Notice acknowledgement can survive cancellation without restoring attendance/assessment authority.
reset role;
insert into public.academy_policies(id,branch_id,version,name,makeup_days) values(pg_temp.sid('policy'),pg_temp.sid('branch-a'),1,'Synthetic notice makeup policy',30);
update public.session_roster set attendance='excused' where id=pg_temp.sid('past-roster');
select private.makeup_credit_for(pg_temp.sid('past-roster'));
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('owner'),'role','authenticated','aal','aal2')::text,true);
select pg_temp.cmd('academy.makeup.book',jsonb_build_object('credit_id',(select id from public.makeup_credits where source_roster_id=pg_temp.sid('past-roster')),'session_id',pg_temp.sid('earlier')));
select lives_ok($$select pg_temp.cmd('academy.session.cancel',jsonb_build_object('session_id',pg_temp.sid('earlier'),'reason','Synthetic makeup session cancellation'))$$,'Cancelling a makeup occurrence creates a real family notice');
select lives_ok($$select pg_temp.cmd('academy.session.cancel',jsonb_build_object('session_id',pg_temp.sid('earlier'),'reason','Repeated cancellation does not duplicate history'))$$,'Repeated occurrence cancellation remains safe');
select is((select count(*)::int from public.session_changes where session_id=pg_temp.sid('earlier') and kind='cancellation'),1,'Makeup cancellation records exactly one central history entry');
select is((select count(*)::int from public.product_events where entity_id=pg_temp.sid('earlier') and kind='session.cancelled' and family_id=pg_temp.sid('family')),1,'Makeup cancellation emits exactly one family event');
select is((select status from public.makeup_credits where source_roster_id=pg_temp.sid('past-roster')),'available','Cancelled makeup restores its existing credit');
select lives_ok($$select pg_temp.cmd('schedule.move',jsonb_build_object('session_id',pg_temp.sid('race'),'scope','occurrence','minutes_delta',30,'reason','Synthetic linked trial time change'))$$,'Move linked trial occurrence');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('parent'),'role','authenticated','aal','aal1')::text,true);
select is((select count(*)::int from public.notifications n join public.product_events e on e.id=n.event_id join public.session_changes sc on sc.id=e.entity_id where sc.session_id=pg_temp.sid('race') and sc.kind='time' and n.recipient_id=pg_temp.sid('parent')),1,'Current linked trial guardian receives time change notice');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('owner'),'role','authenticated','aal','aal2')::text,true);
select lives_ok($$select pg_temp.cmd('academy.session.cancel',jsonb_build_object('session_id',pg_temp.sid('race'),'reason','Synthetic linked trial cancellation'))$$,'Cancelling a linked trial reaches its current family');
select is((select count(*)::int from public.session_changes where session_id=pg_temp.sid('race') and kind='cancellation'),1,'Trial cancellation records exactly one central history entry');
reset role;
select is((select count(*)::int from public.notifications n join public.product_events e on e.id=n.event_id where e.entity_id=pg_temp.sid('race') and e.kind='session.cancelled' and n.recipient_id=pg_temp.sid('parent')),1,'Current family guardian receives the trial cancellation notification');
reset role;
update public.class_sessions set status='cancelled',cancellation_reason='Synthetic cancellation notice' where id=pg_temp.sid('anchor');
select set_config('test.comm.change',(select id::text from public.session_changes where session_id=pg_temp.sid('anchor') and kind='cancellation'),true);
select is((select count(*)::int from public.session_changes where session_id=pg_temp.sid('anchor') and kind='cancellation'),1,'Direct central cancellation transition records one history row');
select is((select count(*)::int from public.product_events where entity_id=pg_temp.sid('anchor') and kind='session.cancelled'),2,'Mixed-family cancellation preserves separate notice authorization for both families');
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('coach'),'role','authenticated','aal','aal1')::text,true);
select is((select jsonb_array_length(s->'students') from jsonb_array_elements(public.development_sessions()) s where s->>'id'=pg_temp.sid('anchor')::text),0,'Cancelled-session notice contains no roster identities');
select lives_ok($$select pg_temp.cmd('schedule.acknowledge',jsonb_build_object('id',current_setting('test.comm.change')::uuid))$$,'Assigned coach acknowledges cancellation through the notice-only authorization');
select is((select count(*)::int from public.session_changes where id=current_setting('test.comm.change')::uuid),1,'Assigned coach can read the current cancellation notice');
reset role;
delete from public.branch_permissions where user_id=pg_temp.sid('coach');
set local role authenticated;
select is(jsonb_array_length(public.development_sessions()),0,'Branch permission revocation removes coach notices and rosters');
select is((select count(*)::int from public.session_changes where id=current_setting('test.comm.change')::uuid),0,'Revoked coach cannot retain direct change-record access');
select throws_ok($$select pg_temp.cmd('schedule.acknowledge',jsonb_build_object('id',current_setting('test.comm.change')::uuid))$$,'42501',null,'Revoked coach cannot acknowledge a known notice ID');
-- Versioned contact-document withdrawal uses the same effective consent ledger as delivery.
reset role;
insert into auth.users(id,email,raw_user_meta_data,email_confirmed_at) values(pg_temp.sid('consent-parent'),'consent-parent-communications@example.test','{"name":"Consent test guardian"}',now());
insert into public.families(id,name) values(pg_temp.sid('consent-family'),'Consent test family');
insert into public.guardians values(pg_temp.sid('consent-family'),pg_temp.sid('consent-parent'));
insert into public.family_branches values(pg_temp.sid('consent-family'),pg_temp.sid('branch-a'));
insert into public.consent_records(family_id,actor_id,kind,version,granted,created_at) values(pg_temp.sid('consent-family'),pg_temp.sid('consent-parent'),'contact','old-contact',true,now()-interval '1 day');
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('owner'),'role','authenticated','aal','aal2')::text,true);
select set_config('test.comm.contactdoc',pg_temp.cmd('community.document.create',jsonb_build_object('title','Synthetic contact preferences','purpose','contact','version','test-only-contact-2','body','Optional test-only in-app marketing permission.'))->>'id',true);
select ok((pg_temp.cmd('communication.preview',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.marketing')))->'recipients') @> jsonb_build_array(jsonb_build_object('user_id',pg_temp.sid('consent-parent'))),'Old accepted contact consent initially qualifies the guardian');
select set_config('test.comm.contactbatch',pg_temp.cmd('communication.schedule',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.marketing'),'scheduled_at',now()-interval '1 minute','confirmed',true))->>'id',true);
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('consent-parent'),'role','authenticated','aal','aal1')::text,true);
select lives_ok($$select pg_temp.cmd('community.document.accept',jsonb_build_object('id',current_setting('test.comm.contactdoc'),'family_id',pg_temp.sid('consent-family'),'granted',false))$$,'Guardian records contact-document withdrawal');
select is((select granted from public.consent_records where family_id=pg_temp.sid('consent-family') and kind='contact' order by created_at desc limit 1),false,'Withdrawal appends current effective contact consent');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('owner'),'role','authenticated','aal','aal2')::text,true);
select ok(not ((pg_temp.cmd('communication.preview',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'template_id',current_setting('test.comm.marketing')))->'recipients') @> jsonb_build_array(jsonb_build_object('user_id',pg_temp.sid('consent-parent')))),'New preview excludes the withdrawn guardian');
select lives_ok($$select pg_temp.cmd('communication.dispatch',jsonb_build_object('id',current_setting('test.comm.contactbatch')))$$,'Previously queued marketing dispatch rechecks the withdrawal');
select is((select status from public.communication_recipients where batch_id=current_setting('test.comm.contactbatch')::uuid and user_id=pg_temp.sid('consent-parent')),'revoked','Queued recipient is revoked rather than delivered');
reset role;
select is((select count(*)::int from public.notifications where recipient_id=pg_temp.sid('consent-parent')),0,'No marketing notification is delivered after withdrawal');
select * from finish();
rollback;
