begin;
select no_plan();
select has_function('private','run_scheduled_jobs',array['text','integer'],'A real private durable scheduler worker exists');
create function pg_temp.jid(x text) returns uuid language sql immutable as $$select md5('durable-jobs-'||x)::uuid$$;
insert into auth.users(id,email,raw_user_meta_data,email_confirmed_at) select pg_temp.jid(x),x||'-durable@example.test',jsonb_build_object('name',x),now() from unnest(array['owner','admin','parent','revoked','suspended','nonparent','coach','sales','branch']) x;
update public.profiles set synthetic=true where id in(select pg_temp.jid(x) from unnest(array['owner','admin','parent','revoked','suspended','nonparent','coach','sales','branch']) x);
insert into public.role_assignments values(pg_temp.jid('owner'),'super_admin'),(pg_temp.jid('admin'),'admin'),(pg_temp.jid('coach'),'coach'),(pg_temp.jid('sales'),'sales'),(pg_temp.jid('branch'),'branch');
insert into public.branches(id,slug,name,provisional) values(pg_temp.jid('branch-a'),'durable-jobs-a','Synthetic job branch',false),(pg_temp.jid('branch-b'),'durable-jobs-b','Disabled job branch',false);
update public.branches set synthetic=true where id in(pg_temp.jid('branch-a'),pg_temp.jid('branch-b'));
insert into public.product_permissions(user_id,permission,branch_id) values(pg_temp.jid('admin'),'communications.broadcast',pg_temp.jid('branch-a'));
insert into public.families(id,name) values(pg_temp.jid('family'),'Synthetic job family');
update public.families set synthetic=true where id=pg_temp.jid('family');
insert into public.family_branches values(pg_temp.jid('family'),pg_temp.jid('branch-a'));
insert into public.guardians select pg_temp.jid('family'),pg_temp.jid(x) from unnest(array['parent','revoked','suspended','nonparent']) x;
insert into public.consent_records(family_id,actor_id,kind,version,granted) values(pg_temp.jid('family'),pg_temp.jid('parent'),'contact','synthetic-v1',true);
insert into public.communication_templates(id,name,language,purpose,subject,body,version,created_by) values(pg_temp.jid('template'),'Synthetic worker','en','operational','Test notice','Synthetic private family body',1,pg_temp.jid('admin')),(pg_temp.jid('marketing'),'Synthetic marketing','en','marketing','Test promotion','Synthetic private promotion body',1,pg_temp.jid('admin'));
insert into public.communication_batches(id,template_id,branch_id,scheduled_at,created_by) values(pg_temp.jid('batch'),pg_temp.jid('template'),pg_temp.jid('branch-a'),now()-interval '1 minute',pg_temp.jid('admin')),(pg_temp.jid('future'),pg_temp.jid('template'),pg_temp.jid('branch-a'),now()+interval '1 day',pg_temp.jid('admin')),(pg_temp.jid('disabled'),pg_temp.jid('template'),pg_temp.jid('branch-b'),now()-interval '1 minute',pg_temp.jid('owner'));
insert into public.communication_recipients(batch_id,family_id,user_id) select pg_temp.jid('batch'),pg_temp.jid('family'),pg_temp.jid(x) from unnest(array['parent','revoked','suspended','nonparent']) x;
select is(private.run_scheduled_jobs('kafou-local',20)->>'status','disabled','Migration creates no enabled job or approvals');
select is((select count(*)::int from private.scheduled_jobs),0,'Disabled worker produces no queue writes');
select ok(not has_function_privilege('authenticated','private.run_scheduled_jobs(text,integer)','EXECUTE'),'Authenticated users cannot execute worker');
select ok(not has_function_privilege('service_role','private.run_scheduled_jobs(text,integer)','EXECUTE'),'Service API key cannot execute private system worker');
select ok(not has_function_privilege('anon','public.scheduler_configure(uuid,boolean,text,text)','EXECUTE'),'Anonymous caller cannot approve jobs');
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.jid('parent'),'role','authenticated','iss','http://127.0.0.1:56321/auth/v1','aal','aal1')::text,true);
select throws_ok($$select public.scheduler_configure(pg_temp.jid('branch-a'),true,'kafou-local','Synthetic test activation')$$,'42501',null,'Parent cannot approve jobs');
select throws_ok($$select public.scheduler_status()$$,'42501',null,'Parent cannot read internal job metadata');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.jid('admin'),'role','authenticated','iss','http://127.0.0.1:56321/auth/v1','aal','aal1')::text,true);
select throws_ok($$select public.scheduler_configure(pg_temp.jid('branch-a'),true,'kafou-local','Synthetic test activation')$$,'42501',null,'Head Office grant cannot authorize autonomous jobs');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.jid('owner'),'role','authenticated','iss','http://127.0.0.1:56321/auth/v1','aal','aal1')::text,true);
select throws_ok($$select public.scheduler_configure(pg_temp.jid('branch-a'),true,'kafou-local','Synthetic test activation')$$,'42501',null,'Owner AAL1 cannot approve jobs');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.jid('owner'),'role','authenticated','iss','http://127.0.0.1:56321/auth/v1','aal','aal2')::text,true);
select throws_ok($$select public.scheduler_configure(pg_temp.jid('branch-a'),true,'production','Synthetic test activation')$$,'22023',null,'Unapproved target rejected');
select throws_ok($$select public.scheduler_configure(pg_temp.jid('branch-a'),true,'cwdazidovxqeevmpicng','Synthetic test activation')$$,'42501',null,'Validated local owner issuer cannot authorize hosted environment');
reset role;
update public.branches set synthetic=false where id=pg_temp.jid('branch-a');
set local role authenticated;
select throws_ok($$select public.scheduler_configure(pg_temp.jid('branch-a'),true,'kafou-local','Synthetic test activation')$$,'22023',null,'Confirmed real branch cannot be enabled as synthetic');
reset role;
update public.branches set synthetic=true where id=pg_temp.jid('branch-a');
set local role authenticated;
select lives_ok($$select public.scheduler_configure(pg_temp.jid('branch-a'),true,'kafou-local','Synthetic test activation')$$,'MFA owner explicitly enables one synthetic branch');
select is(jsonb_array_length(public.scheduler_status()->'controls'),1,'Owner can observe explicit activation');
reset role;
select throws_ok($$select private.run_scheduled_jobs('kafou-local',20)$$,'42501',null,'Even privileged SQL worker refuses to impersonate a user JWT');
select set_config('request.jwt.claims','{}',true);
select is(private.run_scheduled_jobs('cwdazidovxqeevmpicng',20)->>'status','disabled','Local control cannot authorize the other target');
delete from public.guardians where user_id=pg_temp.jid('revoked');
update public.profiles set active=false where id=pg_temp.jid('suspended');
delete from public.role_assignments where user_id=pg_temp.jid('nonparent') and role='parent';
select is((private.run_scheduled_jobs('kafou-local',20)->>'processed')::int,1,'System executes only due approved branch batch');
select is((select count(*)::int from public.notifications n join public.product_events e on e.id=n.event_id where e.entity_id=pg_temp.jid('batch')),1,'Current guardianship, profile and parent role rechecked at execution');
select is((select count(*)::int from public.communication_recipients where batch_id=pg_temp.jid('batch') and status='revoked'),3,'Ineligible frozen recipients explicitly revoked');
select ok((select actor_id is null from public.product_events where entity_id=pg_temp.jid('batch')),'System event does not fabricate a staff actor');
select is((select creator_id from private.scheduled_job_runs where job_id=(select id from private.scheduled_jobs where entity_id=pg_temp.jid('batch'))),pg_temp.jid('admin'),'Run retains original approving broadcast creator');
select is((select count(*)::int from private.scheduled_job_effects),1,'Durable cause links job and emitted event');
select is((select count(*)::int from public.delivery_outbox o join public.product_events e on e.id=o.event_id where e.entity_id=pg_temp.jid('batch') and o.status='not_configured' and o.attempts=0),3,'External delivery stays disabled without fake send attempts');
select is((private.run_scheduled_jobs('kafou-local',20)->>'processed')::int,0,'Repeated execution does not repeat work');
select is((select count(*)::int from public.notifications n join public.product_events e on e.id=n.event_id where e.entity_id=pg_temp.jid('batch')),1,'Retry cannot duplicate notification');
-- A revoked creator cannot preserve an old grant via a scheduled batch.
insert into public.communication_batches(id,template_id,branch_id,scheduled_at,created_by) values(pg_temp.jid('revoked-batch'),pg_temp.jid('template'),pg_temp.jid('branch-a'),now(),pg_temp.jid('admin'));
insert into public.communication_recipients(batch_id,family_id,user_id) values(pg_temp.jid('revoked-batch'),pg_temp.jid('family'),pg_temp.jid('parent'));
delete from public.product_permissions where user_id=pg_temp.jid('admin');
select private.run_scheduled_jobs('kafou-local',20);
select is((select last_code from private.scheduled_jobs where entity_id=pg_temp.jid('revoked-batch')),'CREATOR_AUTHORITY_REVOKED','Current creator capability revocation blocks publication');
select is((select count(*)::int from public.product_events where entity_id=pg_temp.jid('revoked-batch')),0,'Revoked creator emits no family content');
insert into public.product_permissions(user_id,permission,branch_id) values(pg_temp.jid('admin'),'communications.broadcast',pg_temp.jid('branch-b'));
select ok(not private.scheduled_broadcaster_current(pg_temp.jid('admin'),pg_temp.jid('branch-a')),'Unrelated branch grant cannot authorize creator');
insert into public.product_permissions(user_id,permission,branch_id) values(pg_temp.jid('coach'),'communications.broadcast',pg_temp.jid('branch-a')),(pg_temp.jid('sales'),'communications.broadcast',pg_temp.jid('branch-a')),(pg_temp.jid('branch'),'communications.broadcast',pg_temp.jid('branch-a'));
select ok(not private.scheduled_broadcaster_current(pg_temp.jid('coach'),pg_temp.jid('branch-a')) and not private.scheduled_broadcaster_current(pg_temp.jid('sales'),pg_temp.jid('branch-a')) and not private.scheduled_broadcaster_current(pg_temp.jid('branch'),pg_temp.jid('branch-a')),'Grants never turn Coach/Sales/Branch into a Head Office broadcaster');
insert into public.product_permissions(user_id,permission,branch_id) values(pg_temp.jid('admin'),'communications.broadcast',pg_temp.jid('branch-a'));
insert into public.communication_batches(id,template_id,branch_id,scheduled_at,created_by) values(pg_temp.jid('marketing-batch'),pg_temp.jid('marketing'),pg_temp.jid('branch-a'),now(),pg_temp.jid('admin'));
insert into public.communication_recipients(batch_id,family_id,user_id) values(pg_temp.jid('marketing-batch'),pg_temp.jid('family'),pg_temp.jid('parent'));
insert into public.consent_records(family_id,actor_id,kind,version,granted,created_at) values(pg_temp.jid('family'),pg_temp.jid('parent'),'contact','synthetic-v2',false,clock_timestamp());
select private.run_scheduled_jobs('kafou-local',20);
select is((select count(*)::int from public.product_events where entity_id=pg_temp.jid('marketing-batch')),0,'Current contact consent withdrawal suppresses marketing');
-- Actual database failure injection rolls back the item and records only SQLSTATE.
insert into public.communication_batches(id,template_id,branch_id,scheduled_at,created_by) values(pg_temp.jid('retry-batch'),pg_temp.jid('template'),pg_temp.jid('branch-a'),now(),pg_temp.jid('admin'));
insert into public.communication_recipients(batch_id,family_id,user_id) values(pg_temp.jid('retry-batch'),pg_temp.jid('family'),pg_temp.jid('parent'));
create function pg_temp.fail_notification() returns trigger language plpgsql as $$begin raise exception 'PRIVATE family body must never enter job logs' using errcode='P0999';end$$;
create trigger synthetic_jobs_failure before insert on public.notifications for each row execute function pg_temp.fail_notification();
select private.run_scheduled_jobs('kafou-local',20);
select is((select state from private.scheduled_jobs where entity_id=pg_temp.jid('retry-batch')),'retry','Actual database failure persists a retryable job');
select is((select last_code from private.scheduled_jobs where entity_id=pg_temp.jid('retry-batch')),'P0999','Failure records redacted SQLSTATE only');
select ok((select next_attempt_at>now() from private.scheduled_jobs where entity_id=pg_temp.jid('retry-batch')),'Retry respects backoff');
select is((select count(*)::int from public.product_events where entity_id=pg_temp.jid('retry-batch')),0,'Failed transaction leaves no partial event');
select is((select status from public.communication_recipients where batch_id=pg_temp.jid('retry-batch')),'queued','Failed transaction preserves unprocessed recipient');
select is((private.run_scheduled_jobs('kafou-local',20)->>'processed')::int,0,'Backoff is enforced, not advisory');
drop trigger synthetic_jobs_failure on public.notifications;
update private.scheduled_jobs set next_attempt_at=now() where entity_id=pg_temp.jid('retry-batch');
select private.run_scheduled_jobs('kafou-local',20);
select is((select state from private.scheduled_jobs where entity_id=pg_temp.jid('retry-batch')),'succeeded','Retry succeeds after genuine fault is removed');
select is((select count(*)::int from private.scheduled_job_runs where job_id=(select id from private.scheduled_jobs where entity_id=pg_temp.jid('retry-batch'))),2,'Failed and successful attempts are both retained');
select throws_ok($$update private.scheduled_job_runs set affected=99$$,'42501',null,'Attempt history cannot be overwritten');
select throws_ok($$delete from private.scheduled_job_controls$$,'42501',null,'Activation approval history cannot be erased');
select throws_ok($$delete from private.scheduled_job_effects$$,'42501',null,'System cause links are append only');
-- Synthetic seven-day rule and financial non-effects.
insert into public.children(id,family_id,name,dob) values(pg_temp.jid('child'),pg_temp.jid('family'),'Synthetic reminder child','2018-01-01');
update public.children set synthetic=true where id=pg_temp.jid('child');
insert into public.commercial_packages(id,branch_id,sport,name,price_minor,session_allowance,terms,created_by) values(pg_temp.jid('package'),pg_temp.jid('branch-a'),'swimming','Synthetic reminder package',1000,8,'Synthetic reminder terms',pg_temp.jid('owner'));
insert into public.commercial_memberships(id,package_id,child_id,family_id,branch_id,sport,starts_on,expires_on,accepted_by) select pg_temp.jid('member-'||d),pg_temp.jid('package'),pg_temp.jid('child'),pg_temp.jid('family'),pg_temp.jid('branch-a'),'swimming',(now() at time zone 'Asia/Dubai')::date-30,(now() at time zone 'Asia/Dubai')::date+d,pg_temp.jid('parent') from unnest(array[-1,0,7,8]) d;
update public.commercial_memberships set status='active' where package_id=pg_temp.jid('package');
insert into public.commercial_memberships(id,package_id,child_id,family_id,branch_id,sport,starts_on,expires_on,accepted_by,status) select pg_temp.jid('member-'||s),pg_temp.jid('package'),pg_temp.jid('child'),pg_temp.jid('family'),pg_temp.jid('branch-a'),'swimming',(now() at time zone 'Asia/Dubai')::date-30,(now() at time zone 'Asia/Dubai')::date+3,pg_temp.jid('parent'),s from unnest(array['pending','frozen','suspended']) s;
select private.run_scheduled_jobs('kafou-local',20);
select is((select count(*)::int from public.commercial_renewal_reminders r join public.commercial_memberships m on m.id=r.membership_id where m.package_id=pg_temp.jid('package')),2,'Only today through seven Dubai calendar days qualifies');
select is((select count(*)::int from private.scheduled_jobs where entity_id in(select pg_temp.jid('member-'||s) from unnest(array['pending','frozen','suspended']) s)),0,'Autonomous reminders exclude pending, frozen and suspended memberships');
select is((select count(*)::int from public.notifications n join public.product_events e on e.id=n.event_id where e.kind='membership.renewal_due' and e.family_id=pg_temp.jid('family') and n.recipient_id<>pg_temp.jid('parent')),0,'Renewal recipients use current active synthetic guardian-parent links');

select private.run_scheduled_jobs('kafou-local',20);
select is((select count(*)::int from public.commercial_renewal_reminders r join public.commercial_memberships m on m.id=r.membership_id where m.package_id=pg_temp.jid('package')),2,'Recurring run never duplicates renewal reminders');
select is((select count(*)::int from public.commercial_invoices where family_id=pg_temp.jid('family')),0,'Reminder creates no invoice or charge');
select is((select count(*)::int from public.entitlement_ledger where membership_id in(select id from public.commercial_memberships where package_id=pg_temp.jid('package'))),0,'Reminder grants no membership entitlement');
-- Expired offer cleanup does not auto-book or auto-offer.
insert into public.venues(id,branch_id,name,address) values(pg_temp.jid('venue'),pg_temp.jid('branch-a'),'Synthetic venue','Synthetic');
insert into public.sport_levels(id,sport,name,rank) values(pg_temp.jid('level'),'swimming','Synthetic jobs level',678);
insert into public.age_groups(id,name,min_age,max_age) values(pg_temp.jid('ages'),'Synthetic job ages',1,17);
insert into public.academy_classes(id,branch_id,venue_id,coach_id,sport,level_id,age_group_id,name,capacity,weekdays,local_time,duration_minutes) values(pg_temp.jid('class'),pg_temp.jid('branch-a'),pg_temp.jid('venue'),pg_temp.jid('coach'),'swimming',pg_temp.jid('level'),pg_temp.jid('ages'),'Synthetic jobs class',2,array[0],'16:00',60);
insert into public.class_sessions(id,class_id,starts_at,ends_at,capacity) values(pg_temp.jid('session'),pg_temp.jid('class'),now()+interval '2 days',now()+interval '2 days 1 hour',2);
insert into public.enrollments(id,child_id,class_id) values(pg_temp.jid('enrollment'),pg_temp.jid('child'),pg_temp.jid('class'));
insert into public.waitlist_entries(id,child_id,enrollment_id,session_id,status,offered_until) values(pg_temp.jid('expired-offer'),pg_temp.jid('child'),pg_temp.jid('enrollment'),pg_temp.jid('session'),'offered',now()-interval '1 minute');
select private.run_scheduled_jobs('kafou-local',20);
select is((select status from public.waitlist_entries where id=pg_temp.jid('expired-offer')),'expired','Autonomous worker durably expires offer');
select is((select state from private.scheduled_jobs where entity_id=pg_temp.jid('expired-offer')),'staff_review','Expiry leaves an explicit staff next-offer review item');
select is((select count(*)::int from public.session_roster where session_id=pg_temp.jid('session')),0,'Expiry cannot book a child');
-- Bound a large approved audience across durable continuation ticks.
insert into auth.users(id,email,raw_user_meta_data,email_confirmed_at) select pg_temp.jid('bulk-'||n),'bulk-'||n||'-jobs@example.test',jsonb_build_object('name','Synthetic recipient '||n),now() from generate_series(1,205) n;
update public.profiles set synthetic=true where id in(select pg_temp.jid('bulk-'||n) from generate_series(1,205) n);
insert into public.guardians select pg_temp.jid('family'),pg_temp.jid('bulk-'||n) from generate_series(1,205) n;
insert into public.communication_batches(id,template_id,branch_id,scheduled_at,created_by) values(pg_temp.jid('bulk-batch'),pg_temp.jid('template'),pg_temp.jid('branch-a'),now(),pg_temp.jid('admin'));
insert into public.communication_recipients(batch_id,family_id,user_id) select pg_temp.jid('bulk-batch'),pg_temp.jid('family'),pg_temp.jid('bulk-'||n) from generate_series(1,205) n;
select private.run_scheduled_jobs('kafou-local',1);
select is((select count(*)::int from public.communication_recipients where batch_id=pg_temp.jid('bulk-batch') and status='sent'),100,'One item processes at most 100 reviewed recipients');
select is((select status from public.communication_batches where id=pg_temp.jid('bulk-batch')),'scheduled','Partial batch remains scheduled until all recipients resolve');
select is((select state from private.scheduled_jobs where entity_id=pg_temp.jid('bulk-batch')),'pending','Bounded continuation is durable');
delete from public.guardians where user_id in(select user_id from public.communication_recipients where batch_id=pg_temp.jid('bulk-batch') and status='queued');
select private.run_scheduled_jobs('kafou-local',1);
select private.run_scheduled_jobs('kafou-local',1);
select is((select count(*)::int from public.communication_recipients where batch_id=pg_temp.jid('bulk-batch') and status='revoked'),105,'Continuation rechecks access, including records outside the first page');
select is((select status from public.communication_batches where id=pg_temp.jid('bulk-batch')),'sent','Batch completes only after all frozen recipients resolve');
-- Retry exhaustion becomes operator-visible; raw provider/error text never leaks.
insert into public.communication_batches(id,template_id,branch_id,scheduled_at,created_by) values(pg_temp.jid('failed-batch'),pg_temp.jid('template'),pg_temp.jid('branch-a'),now(),pg_temp.jid('admin'));
insert into public.communication_recipients(batch_id,family_id,user_id) values(pg_temp.jid('failed-batch'),pg_temp.jid('family'),pg_temp.jid('parent'));
create trigger synthetic_jobs_failure before insert on public.notifications for each row execute function pg_temp.fail_notification();
do $$begin for i in 1..5 loop update private.scheduled_jobs set next_attempt_at=now() where entity_id=pg_temp.jid('failed-batch');perform private.run_scheduled_jobs('kafou-local',20);end loop;end$$;
drop trigger synthetic_jobs_failure on public.notifications;
select is((select state from private.scheduled_jobs where entity_id=pg_temp.jid('failed-batch')),'failed','Five failures stop retries for explicit operator review');
select is((select failures from private.scheduled_jobs where entity_id=pg_temp.jid('failed-batch')),5,'Failure counter remains observable');
select is((private.run_scheduled_jobs('kafou-local',20)->>'processed')::int,0,'Failed item cannot spin indefinitely');
-- Latest approval disables all future work; owner suspension also stops approved work.
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.jid('owner'),'role','authenticated','iss','http://127.0.0.1:56321/auth/v1','aal','aal2')::text,true);
select lives_ok($$select public.scheduler_configure(pg_temp.jid('branch-a'),false,'kafou-local','Synthetic pause after verification')$$,'Owner pauses without erasing approval history');
select is(jsonb_array_length(public.scheduler_status()->'staff_queue'),1,'Owner sees the explicit expired-offer staff queue');
select ok(public.scheduler_status()->>'last_success' is not null,'Status reports actual last successful work');
select is((public.scheduler_status()->'counts'->>'failed')::int,1,'Status exposes retry exhaustion');
select ok(public.scheduler_status()::text not like '%PRIVATE family body%','Status does not leak injected exception body');
reset role;
select set_config('request.jwt.claims','{}',true);
select is(private.run_scheduled_jobs('kafou-local',20)->>'status','disabled','Latest pause supersedes prior approval');
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.jid('owner'),'role','authenticated','iss','http://127.0.0.1:56321/auth/v1','aal','aal2')::text,true);
select public.scheduler_configure(pg_temp.jid('branch-a'),true,'kafou-local','Synthetic resume for revocation test');
reset role;
select set_config('request.jwt.claims','{}',true);
update public.profiles set active=false where id=pg_temp.jid('owner');
select is(private.run_scheduled_jobs('kafou-local',20)->>'status','disabled','Approval does not survive owner suspension');
update public.profiles set active=true where id=pg_temp.jid('owner');
delete from public.role_assignments where user_id=pg_temp.jid('owner') and role='super_admin';
select is(private.run_scheduled_jobs('kafou-local',20)->>'status','disabled','Approval does not survive owner role revocation');
select * from finish();
rollback;
