begin;
select no_plan();
create function pg_temp.fid(x text) returns uuid language sql immutable as $$select md5('private-files-'||x)::uuid$$;
create function pg_temp.filecmd(a text,d jsonb) returns jsonb language sql as $$select public.product_command(a,d,gen_random_uuid())$$;
insert into auth.users(id,email,raw_user_meta_data,email_confirmed_at) select pg_temp.fid(x),x||'-private-files@example.test',jsonb_build_object('name',x),now() from unnest(array['parent','guardian','other-parent','coach','sales','branch','other-branch','owner']) x;
delete from public.role_assignments where user_id in(pg_temp.fid('coach'),pg_temp.fid('sales'),pg_temp.fid('branch'),pg_temp.fid('other-branch'),pg_temp.fid('owner'));
insert into public.role_assignments values(pg_temp.fid('coach'),'coach'),(pg_temp.fid('sales'),'sales'),(pg_temp.fid('branch'),'branch'),(pg_temp.fid('other-branch'),'branch'),(pg_temp.fid('owner'),'super_admin');
insert into public.branches(id,slug,name,provisional) values(pg_temp.fid('branch-a'),'private-files-test-a','Private file branch',false),(pg_temp.fid('branch-b'),'private-files-test-b','Other private file branch',false);
insert into public.branch_permissions select pg_temp.fid(x),pg_temp.fid('branch-a') from unnest(array['coach','sales','branch']) x;
insert into public.branch_permissions values(pg_temp.fid('other-branch'),pg_temp.fid('branch-b'));
insert into public.families(id,name) values(pg_temp.fid('family'),'Synthetic file family'),(pg_temp.fid('other-family'),'Other synthetic file family');
insert into public.guardians values(pg_temp.fid('family'),pg_temp.fid('parent')),(pg_temp.fid('family'),pg_temp.fid('guardian')),(pg_temp.fid('other-family'),pg_temp.fid('other-parent'));
insert into public.family_branches values(pg_temp.fid('family'),pg_temp.fid('branch-a'));
insert into public.children(id,family_id,name,reported_age,age_captured_on) values(pg_temp.fid('child'),pg_temp.fid('family'),'Synthetic file child',7,current_date),(pg_temp.fid('other-child'),pg_temp.fid('other-family'),'Other synthetic child',7,current_date);
-- Storage metadata is a transaction-only fixture, never real uploaded bytes.
select ok(exists(select 1 from storage.buckets where id='kafou-private-documents' and not public),'Configured file bucket is private');
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.fid('parent'),'role','authenticated','aal','aal1')::text,true);
select throws_ok($$select pg_temp.filecmd('files.begin',jsonb_build_object('family_id',pg_temp.fid('family'),'child_id',pg_temp.fid('other-child'),'name','wrong-child.pdf','mime_type','application/pdf','size_bytes',12,'sha256',repeat('a',64)))$$,'42501',null,'Known child UUID from another family cannot be attached');
select throws_ok($$select pg_temp.filecmd('files.begin',jsonb_build_object('family_id',pg_temp.fid('other-family'),'name','wrong-family.pdf','mime_type','application/pdf','size_bytes',12,'sha256',repeat('a',64)))$$,'42501',null,'Parent cannot create metadata under another family');
select set_config('test.file.begin',public.product_command('files.begin',jsonb_build_object('family_id',pg_temp.fid('family'),'child_id',pg_temp.fid('child'),'branch_id',pg_temp.fid('branch-a'),'uploaded_by',pg_temp.fid('owner'),'object_path','arbitrary/injected','name','شهادة تجريبية.pdf','mime_type','application/pdf','size_bytes',12,'sha256',repeat('a',64)),pg_temp.fid('begin-key'))::text,true);
select set_config('test.file.id',(current_setting('test.file.begin')::jsonb->>'id'),true);
select set_config('test.file.path',(current_setting('test.file.begin')::jsonb->>'path'),true);
select is((select uploaded_by from public.family_files where id=current_setting('test.file.id')::uuid),pg_temp.fid('parent'),'Metadata records the real authenticated uploader');
select is((select object_path from public.family_files where id=current_setting('test.file.id')::uuid),pg_temp.fid('parent')::text||'/'||current_setting('test.file.id'),'Object path ignores caller-controlled paths');
select throws_ok($$select pg_temp.filecmd('files.finish',jsonb_build_object('id',current_setting('test.file.id')))$$,'P0409',null,'Metadata cannot become ready before private storage persists');
select throws_ok($$select pg_temp.filecmd('files.download',jsonb_build_object('id',current_setting('test.file.id')))$$,'P0409',null,'Pending file is not downloadable');
select throws_ok($$update public.family_files set status='ready' where id=current_setting('test.file.id')::uuid$$,'42501',null,'Direct metadata mutation cannot forge a finished upload');
select throws_ok($$insert into storage.objects(bucket_id,name,metadata) values('kafou-private-documents',current_setting('test.file.path'),'{"size":12}')$$,'42501',null,'Authenticated direct storage upload is denied');
reset role;
insert into storage.objects(bucket_id,name,metadata) values('kafou-private-documents',current_setting('test.file.path'),'{"size":11,"mimetype":"application/pdf"}');
set local role authenticated;
select throws_ok($$select pg_temp.filecmd('files.finish',jsonb_build_object('id',current_setting('test.file.id')))$$,'P0409',null,'Stored size mismatch cannot finish upload');
reset role;
update storage.objects set metadata='{"size":12,"mimetype":"application/pdf"}' where bucket_id='kafou-private-documents' and name=current_setting('test.file.path');
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.fid('guardian'),'role','authenticated','aal','aal1')::text,true);
select throws_ok($$select pg_temp.filecmd('files.finish',jsonb_build_object('id',current_setting('test.file.id')))$$,'42501',null,'Another authorized guardian cannot finish someone else upload');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.fid('parent'),'role','authenticated','aal','aal1')::text,true);
select lives_ok($$select pg_temp.filecmd('files.finish',jsonb_build_object('id',current_setting('test.file.id')))$$,'Uploader finishes an exactly persisted private object');
select is((select status from public.family_files where id=current_setting('test.file.id')::uuid),'ready','Ready metadata matches persisted object');
select is((select count(*)::int from storage.objects where bucket_id='kafou-private-documents'),0,'Object remains unreadable through direct authenticated storage table');
select lives_ok($$select public.product_command('files.download',jsonb_build_object('id',current_setting('test.file.id')),pg_temp.fid('download-key'))$$,'Authorized download records an access event');
select lives_ok($$select public.product_command('files.download',jsonb_build_object('id',current_setting('test.file.id')),pg_temp.fid('download-key'))$$,'Unchanged idempotent download authorization retry is safe');
select is((select count(*)::int from public.file_access_events where file_id=current_setting('test.file.id')::uuid and action='download'),1,'Same download request key creates one access event');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.fid('guardian'),'role','authenticated','aal','aal1')::text,true);
select is((select count(*)::int from public.family_files where id=current_setting('test.file.id')::uuid),1,'Current guardian can read the protected family file metadata');
select lives_ok($$select public.product_command('files.download',jsonb_build_object('id',current_setting('test.file.id')),pg_temp.fid('guardian-download-key'))$$,'Current guardian may authorize a logged download');
reset role;
delete from public.guardians where user_id=pg_temp.fid('guardian');
set local role authenticated;
select is((select count(*)::int from public.family_files where id=current_setting('test.file.id')::uuid),0,'Guardian revocation immediately hides file metadata and path');
select is((select count(*)::int from public.file_access_events where file_id=current_setting('test.file.id')::uuid),0,'Guardian revocation also hides file access history');
select throws_ok($$select pg_temp.filecmd('files.download',jsonb_build_object('id',current_setting('test.file.id')))$$,'42501',null,'Revoked guardian cannot authorize a known file ID');
select throws_ok($$select public.product_command('files.download',jsonb_build_object('id',current_setting('test.file.id')),pg_temp.fid('guardian-download-key'))$$,'42501',null,'Revoked guardian cannot replay cached download authorization');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.fid('other-parent'),'role','authenticated','aal','aal1')::text,true);
select is((select count(*)::int from public.family_files where id=current_setting('test.file.id')::uuid),0,'Unrelated family cannot read metadata');
select throws_ok($$select pg_temp.filecmd('files.download',jsonb_build_object('id',current_setting('test.file.id')))$$,'42501',null,'Unrelated parent cannot download a known file ID');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.fid('coach'),'role','authenticated','aal','aal1')::text,true);
select is((select count(*)::int from public.family_files where id=current_setting('test.file.id')::uuid),0,'Coach assignment and branch permission do not expose family documents');
select throws_ok($$select pg_temp.filecmd('files.download',jsonb_build_object('id',current_setting('test.file.id')))$$,'42501',null,'Coach cannot authorize document download');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.fid('sales'),'role','authenticated','aal','aal1')::text,true);
select is((select count(*)::int from public.family_files where id=current_setting('test.file.id')::uuid),0,'Sales cannot read family files');
select throws_ok($$select pg_temp.filecmd('files.download',jsonb_build_object('id',current_setting('test.file.id')))$$,'42501',null,'Sales cannot authorize document download');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.fid('other-branch'),'role','authenticated','aal','aal1')::text,true);
select throws_ok($$select pg_temp.filecmd('files.download',jsonb_build_object('id',current_setting('test.file.id')))$$,'42501',null,'Unrelated branch cannot inspect family documents');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.fid('branch'),'role','authenticated','aal','aal1')::text,true);
select lives_ok($$select pg_temp.filecmd('files.download',jsonb_build_object('id',current_setting('test.file.id')))$$,'Scoped reception can log an operational document download');
select lives_ok($$select public.product_command('files.download',jsonb_build_object('id',current_setting('test.file.id')),pg_temp.fid('branch-cache'))$$,'Branch caches authorized access');
reset role;
delete from public.family_branches where family_id=pg_temp.fid('family');
set local role authenticated;
select throws_ok($$select pg_temp.filecmd('files.download',jsonb_build_object('id',current_setting('test.file.id')))$$,'42501',null,'Fresh download correctly denied after family unlink');
select throws_ok($$select public.product_command('files.download',jsonb_build_object('id',current_setting('test.file.id')),pg_temp.fid('branch-cache'))$$,'42501',null,'Cached authorization must also deny after family unlink');
reset role;
insert into public.family_branches values(pg_temp.fid('family'),pg_temp.fid('branch-a'));
set local role authenticated;

select throws_ok($$select pg_temp.filecmd('files.withdraw',jsonb_build_object('id',current_setting('test.file.id')))$$,'42501',null,'Reception cannot withdraw a guardian file');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.fid('owner'),'role','authenticated','aal','aal1')::text,true);
select throws_ok($$select pg_temp.filecmd('files.download',jsonb_build_object('id',current_setting('test.file.id')))$$,'42501',null,'Owner must satisfy AAL2 for file access');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.fid('parent'),'role','authenticated','aal','aal1')::text,true);
select lives_ok($$select public.product_command('files.withdraw',jsonb_build_object('id',current_setting('test.file.id')),pg_temp.fid('withdraw-key'))$$,'Owning parent withdraws future download access');
select lives_ok($$select public.product_command('files.withdraw',jsonb_build_object('id',current_setting('test.file.id')),pg_temp.fid('withdraw-key'))$$,'Unchanged withdrawal retry remains idempotent');
select throws_ok($$select pg_temp.filecmd('files.download',jsonb_build_object('id',current_setting('test.file.id')))$$,'P0409',null,'Withdrawn file can no longer authorize new downloads');
select is((select count(*)::int from public.file_access_events where file_id=current_setting('test.file.id')::uuid and action='withdraw'),1,'Withdrawal records exactly one access audit event');
reset role;
select is((select count(*)::int from storage.objects where bucket_id='kafou-private-documents' and name=current_setting('test.file.path')),1,'Withdrawal retains bytes for the separate retention policy');
select ok(not has_table_privilege('anon','public.family_files','SELECT'),'Anonymous users cannot inspect file metadata');
select * from finish();rollback;
