begin;
select no_plan();
select has_table('public','product_permissions','Explicit product permissions exist');
select has_table('public','notifications','Persistent notifications exist');
select has_function('public','product_command',array['text','jsonb','uuid'],'Idempotent product boundary exists');
select ok(not has_table_privilege('authenticated','public.notifications','INSERT'),'No direct notification spoofing');
select ok(not has_table_privilege('anon','public.product_permissions','SELECT'),'Anonymous cannot inspect grants');

-- A cached write is reusable only while the caller's protected access snapshot is unchanged.
create function pg_temp.pid(x text) returns uuid language sql immutable as $$select md5('product-cache-'||x)::uuid$$;
insert into auth.users(id,email,raw_user_meta_data,email_confirmed_at) values(pg_temp.pid('admin'),'product-cache-admin@example.test','{"name":"Synthetic reviewer"}',now()),(pg_temp.pid('other'),'product-cache-other@example.test','{"name":"Other reviewer"}',now());
insert into public.role_assignments values(pg_temp.pid('admin'),'admin'),(pg_temp.pid('other'),'admin');
insert into public.branches(id,slug,name,provisional) values(pg_temp.pid('branch'),'product-cache-branch','Synthetic cache branch',false);
insert into public.branch_sports values(pg_temp.pid('branch'),'swimming');
insert into public.product_permissions(user_id,permission,branch_id) values(pg_temp.pid('admin'),'finance.packages',pg_temp.pid('branch')),(pg_temp.pid('other'),'finance.packages',pg_temp.pid('branch'));
select set_config('test.core.payload',jsonb_build_object('branch_id',pg_temp.pid('branch'),'sport','swimming','name','Synthetic cache package','price_minor',0,'session_allowance',4,'terms','Test-only package for authorization retries')::text,true);
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.pid('admin'),'role','authenticated','aal','aal1')::text,true);
select set_config('test.core.original',public.product_command('commercial.package.create',current_setting('test.core.payload')::jsonb,pg_temp.pid('create-key'))::text,true);
select is(public.product_command('commercial.package.create',current_setting('test.core.payload')::jsonb,pg_temp.pid('create-key')),current_setting('test.core.original')::jsonb,'Unchanged authorization and payload return the exact original response');
select throws_ok($$select public.product_command('commercial.package.create',current_setting('test.core.payload')::jsonb||'{"name":"Changed cached payload"}',pg_temp.pid('create-key'))$$,'P0409',null,'Unchanged authority cannot reuse a key for different data');
reset role;
select is((select count(*)::int from public.commercial_packages where branch_id=pg_temp.pid('branch')),1,'Retry did not duplicate the protected write');
update public.profiles set name='Renamed synthetic reviewer' where id=pg_temp.pid('admin');
set local role authenticated;
select is(public.product_command('commercial.package.create',current_setting('test.core.payload')::jsonb,pg_temp.pid('create-key')),current_setting('test.core.original')::jsonb,'A harmless profile rename does not invalidate a retry');
reset role;
delete from public.product_permissions where user_id=pg_temp.pid('admin') and permission='finance.packages';
set local role authenticated;
select throws_ok($$select public.product_command('commercial.package.create',current_setting('test.core.payload')::jsonb,pg_temp.pid('create-key'))$$,'42501',null,'Revoking a protected permission invalidates cached write authorization');
select throws_ok($$select public.product_command('commercial.package.create',current_setting('test.core.payload')::jsonb,pg_temp.pid('fresh-key'))$$,'42501',null,'Revoked permission also denies a fresh write key');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.pid('other'),'role','authenticated','aal','aal1')::text,true);
select lives_ok($$select public.product_command('commercial.package.create',current_setting('test.core.payload')::jsonb,pg_temp.pid('create-key'))$$,'The same key belongs independently to another authorized actor');
reset role;
select is((select count(*)::int from public.commercial_packages where branch_id=pg_temp.pid('branch')),2,'A different actor creates its own write instead of receiving someone else cached response');
update public.profiles set active=false where id=pg_temp.pid('other');
set local role authenticated;
select throws_ok($$select public.product_command('commercial.package.create',current_setting('test.core.payload')::jsonb,pg_temp.pid('create-key'))$$,'42501',null,'Account suspension is enforced before any cached response');
reset role;
update public.profiles set active=true where id=pg_temp.pid('other');
delete from public.role_assignments where user_id=pg_temp.pid('other') and role='admin';
set local role authenticated;
select throws_ok($$select public.product_command('commercial.package.create',current_setting('test.core.payload')::jsonb,pg_temp.pid('create-key'))$$,'42501',null,'Role revocation invalidates a previous protected write response');
reset role;
select * from finish(); rollback;
