begin;
select no_plan();
-- Entire ordinary suite rolls back. Concurrency runs use these same fixtures in a throwaway database.
create function pg_temp.sid(x text) returns uuid language sql immutable as $$select md5('schedule-extension-'||x)::uuid$$;
create function pg_temp.cmd(a text,d jsonb) returns jsonb language sql as $$select public.product_command(a,d,gen_random_uuid())$$;
insert into auth.users(id,email,raw_user_meta_data,email_confirmed_at)
select pg_temp.sid(x),x||'-schedule@example.test',jsonb_build_object('name',x),now() from unnest(array['owner','coach','other-coach','branch','parent','other-parent']) x;
insert into public.role_assignments values (pg_temp.sid('owner'),'super_admin'),(pg_temp.sid('coach'),'coach'),(pg_temp.sid('other-coach'),'coach'),(pg_temp.sid('branch'),'branch');
insert into public.branches(id,slug,name,provisional) values(pg_temp.sid('branch-a'),'schedule-extension-a','Synthetic schedule branch',false),(pg_temp.sid('branch-b'),'schedule-extension-b','Other schedule branch',false);
insert into public.branch_sports values(pg_temp.sid('branch-a'),'swimming'),(pg_temp.sid('branch-b'),'swimming');
insert into public.branch_permissions select pg_temp.sid(x),pg_temp.sid('branch-a') from unnest(array['coach','other-coach','branch']) x;
insert into public.branch_permissions values(pg_temp.sid('other-coach'),pg_temp.sid('branch-b'));
insert into public.venues(id,branch_id,name,address) values(pg_temp.sid('venue-a'),pg_temp.sid('branch-a'),'Source pool','Synthetic'),(pg_temp.sid('venue-b'),pg_temp.sid('branch-b'),'Target pool','Synthetic');
insert into public.sport_levels(id,sport,name,rank) values(pg_temp.sid('level'),'swimming','Schedule test level',321);
insert into public.age_groups(id,name,min_age,max_age) values(pg_temp.sid('ages'),'Schedule test ages',5,10);
insert into public.academy_classes(id,branch_id,venue_id,coach_id,sport,level_id,age_group_id,name,capacity,weekdays,local_time,duration_minutes)
values(pg_temp.sid('class-a'),pg_temp.sid('branch-a'),pg_temp.sid('venue-a'),pg_temp.sid('coach'),'swimming',pg_temp.sid('level'),pg_temp.sid('ages'),'Source class',5,array[0],'17:00',60),
(pg_temp.sid('class-b'),pg_temp.sid('branch-b'),pg_temp.sid('venue-b'),pg_temp.sid('other-coach'),'swimming',pg_temp.sid('level'),pg_temp.sid('ages'),'Target class',5,array[0],'17:00',60);
insert into public.class_sessions(id,class_id,starts_at,ends_at,capacity)
select pg_temp.sid(x),pg_temp.sid('class-a'),now()+d,now()+d+interval '1 hour',5 from (values('past',interval '-2 hours'),('earlier',interval '1 day'),('anchor',interval '2 days'),('adjacent',interval '2 days 1 hour')) v(x,d);
insert into public.class_sessions(id,class_id,starts_at,ends_at,capacity) values(pg_temp.sid('target'),pg_temp.sid('class-b'),now()+interval '4 days',now()+interval '4 days 1 hour',1),(pg_temp.sid('race'),pg_temp.sid('class-a'),now()+interval '10 days',now()+interval '10 days 1 hour',1);
insert into public.families(id,name) values(pg_temp.sid('family'),'Schedule test family'),(pg_temp.sid('other-family'),'Other schedule family');
insert into public.guardians values(pg_temp.sid('family'),pg_temp.sid('parent')),(pg_temp.sid('other-family'),pg_temp.sid('other-parent'));
insert into public.family_branches values(pg_temp.sid('family'),pg_temp.sid('branch-a')),(pg_temp.sid('other-family'),pg_temp.sid('branch-a'));
insert into public.children(id,family_id,name,reported_age,age_captured_on) values(pg_temp.sid('child'),pg_temp.sid('family'),'Schedule Athlete',7,current_date),(pg_temp.sid('other-child'),pg_temp.sid('other-family'),'Other Athlete',7,current_date),(pg_temp.sid('trial-child'),pg_temp.sid('other-family'),'Trial Athlete',7,current_date);
insert into public.child_sports(child_id,sport,level_id,level,status) select pg_temp.sid(x),'swimming',pg_temp.sid('level'),'Schedule test level','reviewed' from unnest(array['child','other-child','trial-child']) x;
insert into public.enrollments(id,child_id,class_id) values(pg_temp.sid('enrollment'),pg_temp.sid('child'),pg_temp.sid('class-a')),(pg_temp.sid('other-enrollment'),pg_temp.sid('other-child'),pg_temp.sid('class-a'));
insert into public.session_roster(id,session_id,enrollment_id,kind,attendance) values(pg_temp.sid('past-roster'),pg_temp.sid('past'),pg_temp.sid('enrollment'),'enrollment','present'),(pg_temp.sid('anchor-roster'),pg_temp.sid('anchor'),pg_temp.sid('enrollment'),'enrollment',null);
update public.class_sessions set finalized_at=now(),status='completed' where id=pg_temp.sid('past');
create temp table schedule_original as select id,starts_at,ends_at from public.class_sessions where class_id=pg_temp.sid('class-a');
grant select on schedule_original to authenticated;
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('parent'),'role','authenticated','aal','aal1')::text,true);
select throws_ok($$select pg_temp.cmd('schedule.preview',jsonb_build_object('session_id',pg_temp.sid('anchor'),'scope','series'))$$,'42501',null,'Parent cannot inspect an academy-wide change preview');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('owner'),'role','authenticated','aal','aal2')::text,true);
select is(jsonb_array_length(pg_temp.cmd('schedule.preview',jsonb_build_object('session_id',pg_temp.sid('anchor'),'scope','occurrence'))->'sessions'),1,'Occurrence preview contains only selected future occurrence');
select is(jsonb_array_length(pg_temp.cmd('schedule.preview',jsonb_build_object('session_id',pg_temp.sid('anchor'),'scope','future'))->'sessions'),3,'Future preview includes selected and later occurrences');
select is(jsonb_array_length(pg_temp.cmd('schedule.preview',jsonb_build_object('session_id',pg_temp.sid('anchor'),'scope','series'))->'sessions'),4,'Series preview includes earlier future occurrences but no completed history');
select lives_ok($$select pg_temp.cmd('schedule.move',jsonb_build_object('session_id',pg_temp.sid('anchor'),'scope','future','minutes_delta',30,'reason','Approved pool timing update'))$$,'Adjacent future sessions can shift forward together atomically');
select is((select count(*)::int from public.class_sessions s join schedule_original o using(id) where s.id in(pg_temp.sid('anchor'),pg_temp.sid('adjacent'),pg_temp.sid('race')) and s.starts_at=o.starts_at+interval '30 minutes'),3,'All selected future occurrences move exactly once');
select is((select s.starts_at from public.class_sessions s where id=pg_temp.sid('past')),(select starts_at from schedule_original where id=pg_temp.sid('past')),'Completed occurrence remains unchanged');
select is((select s.starts_at from public.class_sessions s where id=pg_temp.sid('earlier')),(select starts_at from schedule_original where id=pg_temp.sid('earlier')),'Earlier future occurrence is outside future scope');
select lives_ok($$select pg_temp.cmd('schedule.move',jsonb_build_object('session_id',pg_temp.sid('anchor'),'scope','future','minutes_delta',-30,'reason','Restore original pool timing'))$$,'Adjacent sessions can also shift backward together');
select is((select count(*)::int from public.class_sessions s join schedule_original o using(id) where s.starts_at=o.starts_at),5,'Opposite shifts restore all original dates without loop-variable drift');
-- Reviewer input must be validated by SQL, not only the HTTP schema.
reset role;
insert into public.transfer_requests(id,enrollment_id,target_class_id,reason,requested_by) values(pg_temp.sid('transfer'),pg_temp.sid('enrollment'),pg_temp.sid('class-b'),'Parent requested compatible branch',pg_temp.sid('parent'));
set local role authenticated;
select throws_ok($$select pg_temp.cmd('schedule.transfer.review',jsonb_build_object('id',pg_temp.sid('transfer'),'reason','Reviewed documented request'))$$,'22023',null,'Omitted transfer decision cannot become an approval');
select throws_ok($$select pg_temp.cmd('schedule.transfer.review',jsonb_build_object('id',pg_temp.sid('transfer'),'decision','approved','reason','Reviewed documented request'))$$,'P0409',null,'Transfer requires an eligible target membership');
select is((select status from public.enrollments where id=pg_temp.sid('enrollment')),'active','Failed transfer leaves source enrollment active');
select is((select cancelled from public.session_roster where id=pg_temp.sid('anchor-roster')),false,'Failed transfer retains existing seat');
select set_config('test.schedule.package',pg_temp.cmd('commercial.package.create',jsonb_build_object('branch_id',pg_temp.sid('branch-b'),'sport','swimming','name','Synthetic transfer package','price_minor',0,'session_allowance',10,'terms','Synthetic free test package'))->>'id',true);
select set_config('test.schedule.membership',pg_temp.cmd('commercial.membership.start',jsonb_build_object('package_id',current_setting('test.schedule.package'),'child_id',pg_temp.sid('child'),'starts_on',current_date,'accepted',true))->>'id',true);
select set_config('test.schedule.sourcepackage',pg_temp.cmd('commercial.package.create',jsonb_build_object('branch_id',pg_temp.sid('branch-a'),'sport','swimming','name','Synthetic source package','price_minor',0,'session_allowance',10,'terms','Synthetic free test package'))->>'id',true);
select set_config('test.schedule.sourcemembership',pg_temp.cmd('commercial.membership.start',jsonb_build_object('package_id',current_setting('test.schedule.sourcepackage'),'child_id',pg_temp.sid('child'),'starts_on',current_date,'accepted',true))->>'id',true);
reset role;
insert into public.enrollments(id,child_id,class_id) values(pg_temp.sid('blocking-enrollment'),pg_temp.sid('other-child'),pg_temp.sid('class-b'));
insert into public.session_roster(id,session_id,enrollment_id,kind) values(pg_temp.sid('blocking-roster'),pg_temp.sid('target'),pg_temp.sid('blocking-enrollment'),'enrollment');
insert into public.waitlist_entries(id,child_id,enrollment_id,session_id,status,offered_until) values(pg_temp.sid('source-offer'),pg_temp.sid('child'),pg_temp.sid('enrollment'),pg_temp.sid('race'),'offered',now()+interval '1 day');
set local role authenticated;
select throws_ok($$select pg_temp.cmd('schedule.transfer.review',jsonb_build_object('id',pg_temp.sid('transfer'),'decision','approved','reason','Full target must roll back transfer'))$$,'P0409',null,'Full target occurrence rolls back an otherwise funded transfer');
select is((select status from public.enrollments where id=pg_temp.sid('enrollment')),'active','Capacity failure restores source enrollment');
select is((select cancelled from public.session_roster where id=pg_temp.sid('anchor-roster')),false,'Capacity failure restores released source seat');
select is((select sum(reserved_delta)::int from public.entitlement_ledger where membership_id=current_setting('test.schedule.sourcemembership')::uuid),1,'Capacity failure restores source entitlement reservation');
reset role;
update public.session_roster set cancelled=true where id=pg_temp.sid('blocking-roster');
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('parent'),'role','authenticated','aal','aal1')::text,true);
select throws_ok($$select pg_temp.cmd('schedule.transfer.review',jsonb_build_object('id',pg_temp.sid('transfer'),'decision','approved','reason','Parent attempting own approval'))$$,'42501',null,'Parent cannot self-approve a transfer');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('owner'),'role','authenticated','aal','aal2')::text,true);
select lives_ok($$select pg_temp.cmd('schedule.transfer.review',jsonb_build_object('id',pg_temp.sid('transfer'),'decision','approved','reason','Reviewed compatible target membership'))$$,'Owner approves compatible funded transfer');
select is((select status from public.enrollments where id=pg_temp.sid('enrollment')),'ended','Original enrollment is ended rather than rewritten');
select is((select attendance from public.session_roster where id=pg_temp.sid('past-roster')),'present','Completed attendance history remains attached to original enrollment');
select is((select cancelled from public.session_roster where id=pg_temp.sid('anchor-roster')),true,'Old future ordinary seat is released');
select is((select status from public.waitlist_entries where id=pg_temp.sid('source-offer')),'cancelled','Ended source enrollment cannot keep or accept an outstanding offer');
select is((select sum(reserved_delta)::int from public.entitlement_ledger where membership_id=current_setting('test.schedule.sourcemembership')::uuid),0,'Old source membership reservation is released exactly once');
select is((select count(*)::int from public.session_roster where session_id=pg_temp.sid('target') and not cancelled),1,'New target occurrence is reserved');
select lives_ok($$select pg_temp.cmd('schedule.transfer.review',jsonb_build_object('id',pg_temp.sid('transfer'),'decision','approved','reason','Retry same completed approval'))$$,'Transfer approval is idempotent with a new request key');
select is((select count(*)::int from public.transfer_decisions where request_id=pg_temp.sid('transfer')),1,'Only one decision and target enrollment are retained');
reset role;
select is((select sum(reserved_delta)::int from public.entitlement_ledger where membership_id=current_setting('test.schedule.membership')::uuid),1,'Target membership has exactly one reserved entitlement');
set local role authenticated;
-- Crossing Dubai midnight must not move a paid reservation beyond its membership coverage.
reset role;
insert into public.class_sessions(id,class_id,starts_at,ends_at,capacity) select pg_temp.sid('expiry-session'),pg_temp.sid('class-b'),((expires_on-1)::timestamp+interval '23 hours 30 minutes') at time zone 'Asia/Dubai',((expires_on)::timestamp+interval '30 minutes') at time zone 'Asia/Dubai',1 from public.commercial_memberships where id=current_setting('test.schedule.membership')::uuid;
insert into public.session_roster(id,session_id,enrollment_id,kind) select pg_temp.sid('expiry-roster'),pg_temp.sid('expiry-session'),new_enrollment_id,'enrollment' from public.transfer_decisions where request_id=pg_temp.sid('transfer');
select private.commercial_roster_event(pg_temp.sid('expiry-roster'),'reserve','Synthetic expiry boundary reservation');
set local role authenticated;
select throws_ok($$select pg_temp.cmd('schedule.move',jsonb_build_object('session_id',pg_temp.sid('expiry-session'),'scope','occurrence','minutes_delta',60,'reason','Change crosses membership coverage boundary'))$$,'P0409',null,'Moving across Dubai midnight revalidates membership coverage');
select throws_ok($$select pg_temp.cmd('academy.session.move',jsonb_build_object('session_id',pg_temp.sid('expiry-session'),'starts_at',(select starts_at+interval '60 minutes' from public.class_sessions where id=pg_temp.sid('expiry-session')),'ends_at',(select ends_at+interval '60 minutes' from public.class_sessions where id=pg_temp.sid('expiry-session')),'reason','Direct move across membership expiry'))$$,'P0409',null,'Direct academy move must also revalidate paid entitlement date');
select is((select (starts_at at time zone 'Asia/Dubai')::date from public.class_sessions where id=pg_temp.sid('expiry-session')),(select expires_on-1 from public.commercial_memberships where id=current_setting('test.schedule.membership')::uuid),'Invalid membership-date change rolls back session time');
select is((select sum(reserved_delta)::int from public.entitlement_ledger where roster_id=pg_temp.sid('expiry-roster')),1,'Invalid date change also restores the paid reservation');
-- Direct branch permission covers both sides of a transfer.
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('other-parent'),'role','authenticated','aal','aal1')::text,true);
select is((select count(*)::int from public.transfer_decisions where request_id=pg_temp.sid('transfer')),0,'Unrelated family cannot read transfer decision');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('coach'),'role','authenticated','aal','aal1')::text,true);
select lives_ok($$select pg_temp.cmd('schedule.acknowledge',jsonb_build_object('id',(select id from public.session_changes where session_id=pg_temp.sid('anchor') limit 1)))$$,'Current assigned coach acknowledges a real time change');
select lives_ok($$select pg_temp.cmd('schedule.acknowledge',jsonb_build_object('id',(select id from public.session_changes where session_id=pg_temp.sid('anchor') limit 1)))$$,'Acknowledgement is idempotent');
select is((select count(*)::int from public.operational_acknowledgements),1,'Repeat acknowledgement produces one record');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('other-coach'),'role','authenticated','aal','aal1')::text,true);
select throws_ok($$select pg_temp.cmd('schedule.acknowledge',jsonb_build_object('id',(select id from public.session_changes where session_id=pg_temp.sid('anchor') limit 1)))$$,'42501',null,'Unassigned coach cannot acknowledge another class change');

reset role;
insert into public.leads(id,branch_id,parent_name,mobile,family_id) values(pg_temp.sid('lead'),pg_temp.sid('branch-a'),'Synthetic trial guardian','+971500099991',pg_temp.sid('other-family'));
insert into public.trial_enquiries(id,lead_id,submitted_by,child_id,child_name,reported_age,sport,experience,starting_level_id) values(pg_temp.sid('enquiry'),pg_temp.sid('lead'),pg_temp.sid('other-parent'),pg_temp.sid('trial-child'),'Trial Athlete',7,'swimming','beginner',pg_temp.sid('level'));
insert into public.waitlist_entries(id,child_id,enrollment_id,session_id,status,offered_until) values(pg_temp.sid('offer'),pg_temp.sid('other-child'),pg_temp.sid('other-enrollment'),pg_temp.sid('race'),'offered',now()+interval '1 day');
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('owner'),'role','authenticated','aal','aal2')::text,true);
select throws_ok($$select public.operations_command('trial.book',jsonb_build_object('enquiry_id',pg_temp.sid('enquiry'),'session_id',pg_temp.sid('race')))$$,'P0409',null,'Central capacity protects a waitlist offer against baseline trial booking');
select is((select count(*)::int from public.trial_bookings where enquiry_id=pg_temp.sid('enquiry')),0,'Rejected trial leaves no orphan booking');
select lives_ok($$select pg_temp.cmd('academy.waitlist.accept',jsonb_build_object('id',pg_temp.sid('offer')))$$,'Offered child can consume the reserved last seat');
select is((select count(*)::int from public.session_roster where session_id=pg_temp.sid('race') and not cancelled),1,'Accepting an offer creates exactly one occupied seat');
select is((select status from public.waitlist_entries where id=pg_temp.sid('offer')),'booked','Accepted offer no longer counts as a second reservation');
select throws_ok($$select public.operations_command('trial.book',jsonb_build_object('enquiry_id',pg_temp.sid('enquiry'),'session_id',pg_temp.sid('race')))$$,'P0409',null,'A live enrollment also protects capacity against trial booking');
reset role;
update public.session_roster set cancelled=true where session_id=pg_temp.sid('race');
update public.waitlist_entries set status='offered',offered_until=now()-interval '1 minute' where id=pg_temp.sid('offer');
set local role authenticated;
select lives_ok($$select public.operations_command('trial.book',jsonb_build_object('enquiry_id',pg_temp.sid('enquiry'),'session_id',pg_temp.sid('race')))$$,'Expired offer does not consume capacity');
-- A real external resource conflict must undo every previous iteration in the same move.
reset role;
insert into public.academy_classes(id,branch_id,venue_id,coach_id,sport,level_id,age_group_id,name,capacity,weekdays,local_time,duration_minutes) select pg_temp.sid('conflicting-class'),branch_id,venue_id,coach_id,sport,level_id,age_group_id,'Unmoved neighboring class',capacity,weekdays,local_time,duration_minutes from public.academy_classes where id=pg_temp.sid('class-a');
insert into public.class_sessions(id,class_id,starts_at,ends_at,capacity) select pg_temp.sid('conflict'),pg_temp.sid('conflicting-class'),ends_at+interval '10 minutes',ends_at+interval '70 minutes',1 from public.class_sessions where id=pg_temp.sid('earlier');
set local role authenticated;
select throws_ok($$select pg_temp.cmd('schedule.move',jsonb_build_object('session_id',pg_temp.sid('anchor'),'scope','series','minutes_delta',30,'reason','Conflicting series must roll back'))$$,'P0409',null,'External coach or venue conflict rejects the entire series change');
select is((select count(*)::int from public.class_sessions s join schedule_original o using(id) where s.starts_at=o.starts_at),5,'Failed series change rolls back already moved occurrences');
select lives_ok($$select pg_temp.cmd('schedule.cancel',jsonb_build_object('session_id',pg_temp.sid('anchor'),'scope','future','reason','Reviewed future closure notice'))$$,'Future cancellation resolves all selected occurrences');
select is((select count(*)::int from public.class_sessions where class_id=pg_temp.sid('class-a') and status='cancelled'),3,'Future cancellation leaves earlier occurrence and completed history intact');
select is((select count(*)::int from public.session_roster where session_id=pg_temp.sid('race') and not cancelled),0,'Scope cancellation releases a trial seat');
select is((select status from public.class_sessions where id=pg_temp.sid('past')),'completed','Completed history remains completed after scoped cancellation');
select is((select count(*)::int from public.session_changes where session_id=pg_temp.sid('anchor') and kind='cancellation'),1,'Cancellation creates its own reviewable coach notice');
select set_config('test.schedule.cancelchange',coalesce((select id::text from public.session_changes where session_id=pg_temp.sid('anchor') and kind='cancellation'),pg_temp.sid('missing-change')::text),true);
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('coach'),'role','authenticated','aal','aal1')::text,true);
select lives_ok($$select pg_temp.cmd('schedule.acknowledge',jsonb_build_object('id',current_setting('test.schedule.cancelchange')))$$,'Assigned coach can acknowledge cancellation without regaining cancelled roster access');
reset role;
delete from public.branch_permissions where user_id=pg_temp.sid('coach');
set local role authenticated;
select is((select count(*)::int from public.operational_acknowledgements),0,'Revoked coach loses access to acknowledgements');
select throws_ok($$select pg_temp.cmd('schedule.acknowledge',jsonb_build_object('id',current_setting('test.schedule.cancelchange')))$$,'42501',null,'Revoked coach cannot acknowledge a known change identifier');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('owner'),'role','authenticated','aal','aal2')::text,true);

reset role;
insert into public.transfer_requests(id,enrollment_id,target_class_id,reason,requested_by) values(pg_temp.sid('decline'),pg_temp.sid('other-enrollment'),pg_temp.sid('class-b'),'Separate reviewed request',pg_temp.sid('other-parent'));
insert into public.product_permissions(user_id,permission,branch_id) values(pg_temp.sid('branch'),'operations.transfer',pg_temp.sid('branch-a'));
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('branch'),'role','authenticated','aal','aal1')::text,true);
select throws_ok($$select pg_temp.cmd('schedule.transfer.review',jsonb_build_object('id',pg_temp.sid('decline'),'decision','declined','reason','Source branch cannot decide target branch'))$$,'42501',null,'Source-branch permission cannot authorize the other branch');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.sid('owner'),'role','authenticated','aal','aal2')::text,true);
select lives_ok($$select pg_temp.cmd('schedule.transfer.review',jsonb_build_object('id',pg_temp.sid('decline'),'decision','declined','reason','Reviewed transfer declined with reason'))$$,'Reviewer can decline without rewriting an enrollment');
select is((select status from public.transfer_requests where id=pg_temp.sid('decline')),'declined','Declined decision persists its outcome');
select is((select status from public.enrollments where id=pg_temp.sid('other-enrollment')),'active','Decline retains source enrollment');
select throws_ok($$select pg_temp.cmd('schedule.transfer.review',jsonb_build_object('id',pg_temp.sid('missing-transfer'),'decision','approved','reason','Unknown record must not report success'))$$,'P0002',null,'Unknown request cannot report a completed approval');
select * from finish();
rollback;
