import { dailyArabic } from "./daily-arabic";
import { attendanceArabic } from "./attendance-arabic";
import { stabilizationArabic } from "./stabilization-arabic";
import { managementArabic } from "./management-arabic";
import { productArabic } from "./product-arabic";
import { academyArabic } from "./academy-arabic";
import { engagementArabic } from "./engagement-arabic";
import { commercialArabic } from "./commercial-arabic";
import { developmentArabic } from "./development-arabic";
import { communityArabic } from "./community-arabic";
export const platformArabic: Record<string, string> = {
  ...managementArabic,
  ...attendanceArabic,
  ...stabilizationArabic,
  "No matching students": "لا يوجد طلاب مطابقون للبحث",
  "Clear search": "مسح البحث",
  People: "الأفراد",
  Academy: "الأكاديمية",
  Money: "المالية",
  Communication: "التواصل",
  "Insights and setup": "التقارير والإعدادات",
  Home: "الرئيسية",
  "Parent Home": "الرئيسية",
  "Coach Today": "يوم المدرب",
  "Today at KAFOU": "اليوم في كافو",
  "Front desk today": "الاستقبال اليوم",
  Membership: "العضوية",
  Settings: "الإعدادات",
  "Manage family": "إدارة الأسرة",
  "Open next roster": "فتح قائمة الحضور التالية",
  "Open arrivals": "فتح قائمة الوصول",
  "FAMILY APP": "تطبيق الأسرة",
  "Schedule tools": "أدوات الجدول",
  "Progress tools": "أدوات التقدم",
  "Family tools": "أدوات الأسرة",
  "Memberships tools": "أدوات العضوية",
  "Support tools": "أدوات الدعم",
  "Upcoming classes": "الحصص القادمة",
  "Schedule view": "عرض الجدول",
  Upcoming: "القادمة",
  History: "السجل",
  "Confirmed classes for every child.": "الحصص المؤكدة لكل طفل.",
  "Follow trial requests and confirmed bookings.":
    "تابع طلبات التجربة والحجوزات المؤكدة.",
  "Academy events and competitions.": "فعاليات الأكاديمية ومسابقاتها.",
  "Make-up and rescheduling": "التعويض وإعادة الجدولة",
  "Use an available credit for a valid replacement slot.":
    "استخدم رصيداً متاحاً لحجز موعد بديل مناسب.",
  "Published feedback and level history.": "التقييمات المنشورة وسجل المستويات.",
  "Progress reports": "تقارير التقدم",
  "Open approved development reports.": "افتح تقارير التطور المعتمدة.",
  "Download issued certificates.": "نزّل الشهادات الصادرة.",
  Achievements: "الإنجازات",
  "Recognition shared by the academy.": "الإنجازات التي تشاركها الأكاديمية.",
  "Children and family profile": "الأطفال وملف الأسرة",
  "Manage child and guardian details.": "أدر بيانات الأطفال وأولياء الأمور.",
  "Registration history": "سجل التسجيل والاستفسارات",
  "View submitted enquiries and references.":
    "اعرض الاستفسارات المرسلة وأرقامها المرجعية.",
  "Guardian access": "وصول ولي الأمر",
  "Review family account access.": "راجع صلاحيات الوصول إلى حساب الأسرة.",
  "Family documents": "مستندات الأسرة",
  "Open files shared with your family.": "افتح الملفات المشتركة مع أسرتك.",
  "Current package": "الباقة الحالية",
  "Package status, validity and remaining sessions.":
    "حالة الباقة وصلاحيتها والحصص المتبقية.",
  "Invoices and receipts": "الفواتير والإيصالات",
  "Review balances and recorded offline payments.":
    "راجع الأرصدة والدفعات المسجلة خارج النظام.",
  "Support tickets": "طلبات الدعم",
  "Ask the academy operations team for help.":
    "اطلب المساعدة من فريق عمليات الأكاديمية.",
  "Coach communication": "التواصل مع المدرب",
  "Child-linked conversations with assigned staff.":
    "محادثات مرتبطة بالطفل مع الموظفين المعيّنين.",
  "Notifications and preferences": "الإشعارات والتفضيلات",
  "Review academy updates and notification status.":
    "راجع تحديثات الأكاديمية وحالة الإشعارات.",
  "Account settings": "إعدادات الحساب",
  "Manage sign-in and account security.": "أدر تسجيل الدخول وأمان الحساب.",
  "ONE STUDENT JOURNEY": "رحلة واحدة لكل طالب",
  Students: "الطلاب",
  "Search students": "البحث عن الطلاب",
  "authorized students": "طلاب ضمن الصلاحية",
  "Permission-scoped records": "سجلات ضمن الصلاحيات",
  "Assignment-scoped access": "وصول حسب التكليف",
  "Find the child once, then follow their schedule, membership and progress.":
    "ابحث عن الطفل مرة واحدة، ثم تابع جدوله وعضويته وتقدمه.",
  "Only athletes on your assigned session rosters appear here.":
    "يظهر هنا فقط اللاعبون ضمن قوائم الحصص المعيّنة لك.",
  "STUDENT WORKSPACE": "مساحة الطالب",
  "Visible through your assigned roster":
    "ظاهر من خلال قائمة الحصة المعيّنة لك",
  "Open family": "فتح الأسرة",
  "assigned sessions": "حصص معيّنة",
  "Class and level stay linked to this student.":
    "يبقى الصف والمستوى مرتبطين بهذا الطالب.",
  "No active membership": "لا توجد عضوية نشطة",
  "Membership information appears after enrollment.":
    "تظهر معلومات العضوية بعد التسجيل.",
  "View membership": "عرض العضوية",
  "Session-based record": "سجل حسب الحصة",
  "Attendance remains separate from the weekly schedule.":
    "يبقى سجل الحضور منفصلاً عن الجدول الأسبوعي.",
  "published assessments": "تقييمات منشورة",
  "Draft and submit progress from the coaching workspace.":
    "احفظ مسودة التقدم وأرسلها من مساحة التدريب.",
  "Parents see published progress only.":
    "يرى أولياء الأمور التقدم المنشور فقط.",
  "Open progress": "فتح التقدم",
  available: "متاح",
  reports: "تقارير",
  certificates: "شهادات",
  "View certificates": "عرض الشهادات",
  "Family contacts and finance are not included in coach access.":
    "لا تشمل صلاحية المدرب بيانات تواصل الأسرة أو المعلومات المالية.",
  "NEXT ASSIGNED SESSION": "الحصة المعيّنة التالية",
  "Open students": "فتح الطلاب",
  "Assess students": "تقييم الطلاب",
  "Roster preview": "معاينة القائمة",
  "more students": "طلاب إضافيون",
  "UP NEXT": "القادم",
  "Assigned schedule": "الجدول المعيّن",
  "No additional assigned sessions.": "لا توجد حصص معيّنة إضافية.",
  "SESSION CHECKLIST": "قائمة إكمال الحصة",
  "Leave every session complete": "أكمل كل حصة قبل المغادرة",
  "Confirm the roster before the session": "تأكد من القائمة قبل الحصة",
  "Record attendance after the session": "سجّل الحضور بعد الحصة",
  "Save assessment notes for the right student":
    "احفظ ملاحظات التقييم للطالب الصحيح",
  "Queues reflect loaded records. Collections totals are complete.":
    "تعكس قوائم المتابعة السجلات المحملة. إجماليات التحصيلات كاملة.",
  "Refresh report": "تحديث التقرير",
  "Coach messages": "رسائل المدرب",
  "Parent registration link": "رابط تسجيل ولي الأمر",
  "Create registration link": "إنشاء رابط التسجيل",
  "Registration link": "رابط التسجيل",
  "Copy link": "نسخ الرابط",
  Copied: "تم النسخ",
  Revoke: "إلغاء الرابط",
  "Select and copy the link.": "حدد الرابط وانسخه.",
  "Copy this link now. It expires in 48 hours. No message has been sent.":
    "انسخ الرابط الآن. تنتهي صلاحيته خلال ٤٨ ساعة. لم تُرسل أي رسالة.",
  "Continue parent registration": "متابعة تسجيل ولي الأمر",
  "Sign in and add your child to your family account, then return here to connect the enquiry.":
    "سجّل الدخول وأضف طفلك إلى حساب الأسرة، ثم عد إلى هنا لربط الاستفسار.",
  "Open family account": "فتح حساب الأسرة",
  "Choose child": "اختر الطفل",
  "This confirms that you want to link this enquiry to the selected child in your own family.":
    "تؤكد بذلك رغبتك في ربط هذا الاستفسار بالطفل المختار من أسرتك.",
  "Confirm child and continue": "تأكيد الطفل والمتابعة",
  "Enquiry connected. Open your family account to choose an eligible trial.":
    "تم ربط الاستفسار. افتح حساب الأسرة لاختيار حصة تجريبية مناسبة.",
  "Complete authorized totals for the selected period. Detail pagination does not affect these figures.":
    "إجماليات كاملة ضمن صلاحياتك للفترة المحددة. لا يؤثر تحميل صفحات التفاصيل على هذه الأرقام.",
  "Complete authorized totals. Detail pagination does not affect collections.":
    "إجماليات كاملة ضمن صلاحياتك. لا يؤثر تحميل صفحات التفاصيل على التحصيلات.",
  "Snapshot time": "وقت احتساب البيانات",
  "All sports": "جميع الرياضات",
  "Finance covers all sports in the selected branch. Family payments may cover several sports.":
    "تشمل الأرقام المالية جميع الرياضات في الفرع المحدد. قد تغطي دفعات الأسرة عدة رياضات.",
  Refunds: "المبالغ المستردة",
  "Child conversations follow current enrollment and coach assignment. Operations reviews coach replies before publication when required by policy.":
    "ترتبط المحادثات بتسجيل الطفل وتكليف المدرب الحالي. تراجع العمليات ردود المدرب قبل نشرها عندما تتطلب السياسة ذلك.",
  "Coach messaging is inactive or no eligible enrollment is available.":
    "مراسلة المدرب غير مفعلة أو لا يوجد تسجيل مؤهل.",
  "Child and class": "الطفل والصف",
  "Open conversation": "فتح المحادثة",
  Participant: "مشارك",
  "Read by participants": "عدد المشاركين الذين قرؤوا الرسالة",
  "Approve and publish": "اعتماد ونشر",
  "Send for review": "إرسال للمراجعة",
  "Send message": "إرسال الرسالة",
  "Escalated to operations": "تم التصعيد إلى العمليات",
  "Escalate to operations": "تصعيد إلى العمليات",
  used: "مستخدم",
  revoked: "ملغى",
  expired: "منتهي الصلاحية",
  "Sessions needing a coach": "حصص تحتاج إلى مدرب",
  "Business Reports": "تقارير الأعمال",
  "This month": "هذا الشهر",
  "Booked places": "الأماكن المحجوزة",
  Utilisation: "نسبة الإشغال",
  "Students progressed": "الطلاب المتقدمون",
  "Branch comparison": "مقارنة الفروع",
  "Sport performance": "أداء الرياضات",
  "Daily attendance trend": "اتجاه الحضور اليومي",
  "No report activity in this period.": "لا يوجد نشاط للتقرير خلال هذه الفترة.",
  "Current stages of leads created in this period.":
    "المراحل الحالية للعملاء المحتملين الذين أُضيفوا خلال هذه الفترة.",
  "Utilisation is booked places divided by capacity, excluding cancelled sessions. Attendance includes only finalized, marked records; excused absences are shown separately.":
    "الإشغال هو عدد الأماكن المحجوزة مقسوماً على السعة، باستثناء الحصص الملغاة. يشمل الحضور السجلات النهائية المسجّلة فقط؛ وتُعرض حالات الغياب بعذر بشكل منفصل.",
  "Students progressed counts distinct children with an approved level change in this period, excluding reversed changes.":
    "يُحسب كل طفل مرة واحدة عند اعتماد انتقاله إلى مستوى جديد خلال هذه الفترة، مع استثناء التغييرات المتراجع عنها.",
  "Published assessments use publication date. Delivery counts are completed sessions, not a coach quality score.":
    "تُحسب التقييمات المنشورة حسب تاريخ نشرها. عدد الحصص المنفّذة لا يُعد تقييماً لجودة المدرب.",
  "Back to login": "العودة إلى تسجيل الدخول",
  days: "أيام",
  "Event date": "موعد الفعالية",
  "Dubai time": "توقيت دبي",
  "Dated child attendance": "حضور الأطفال حسب الموعد",
  "Save attendance": "حفظ الحضور",
  "Finalize attendance": "اعتماد الحضور",
  "Save every child’s mark, then finalize after this date ends. Families see finalized marks only.":
    "احفظ حالة حضور كل طفل، ثم اعتمد السجل بعد انتهاء هذا الموعد. تظهر للعائلات سجلات الحضور المعتمدة فقط.",
  "Corrected attendance": "الحضور المصحّح",
  Correction: "تصحيح",
  "Families see attendance after staff finalize this date.":
    "تظهر حالة الحضور للعائلات بعد اعتماد الموظفين لسجل هذا الموعد.",
  "Cancel this date": "إلغاء هذا الموعد",
  "This event is cancelled.": "هذه الفعالية ملغاة.",
  "Choose eligible children from one family. Each child must have the required assessed sport level and age.":
    "اختر الأطفال المؤهلين من عائلة واحدة. يجب أن يطابق عمر كل طفل ومستواه الرياضي المعتمَد متطلبات الفعالية.",
  "This registration covers every scheduled date above. The accepted timetable and waiver are saved separately for each child.":
    "يشمل هذا التسجيل جميع المواعيد المدرجة أعلاه. يُحفظ الجدول المقبول وإقرار الموافقة بشكل منفصل لكل طفل.",
  "Waiver version": "نسخة إقرار الموافقة",
  "The waiver is unavailable. Registration is closed.":
    "إقرار الموافقة غير متاح. التسجيل مغلق.",
  "Accept this waiver for this child": "أوافق على هذا الإقرار لهذا الطفل",
  "Registered children": "الأطفال المسجّلون",
  "No active registrations.": "لا توجد تسجيلات نشطة.",
  "All children in this registration will be cancelled together.":
    "سيتم إلغاء تسجيل جميع الأطفال المشمولين بهذا الطلب معاً.",
  "Cancel sibling registration": "إلغاء تسجيل الأشقاء",
  "Cancel event": "إلغاء الفعالية",
  "Events and camps": "الفعاليات والمعسكرات",
  "These synthetic events are separate from regular classes. No payment is collected. All selected siblings register together or none do.":
    "هذه فعاليات تجريبية منفصلة عن الحصص المعتادة، ولا تُحصّل فيها أي مدفوعات. يُسجّل جميع الأشقاء المحددين معاً، أو لا يُسجّل أي منهم.",
  "Event format": "نوع الفعالية",
  "One-off event": "فعالية لمرة واحدة",
  "Multi-date camp": "معسكر متعدد المواعيد",
  "Event title": "عنوان الفعالية",
  "Choose a waiver": "اختر إقرار الموافقة",
  "Starts (Dubai time)": "البداية (بتوقيت دبي)",
  "Ends (Dubai time)": "النهاية (بتوقيت دبي)",
  "Configure 2–30 non-overlapping dates within 90 days, each within one Dubai day and up to 12 hours. Registration covers all dates and closes at the first start. No payment is collected.":
    "حدّد من موعدين إلى ٣٠ موعداً غير متداخلة خلال ٩٠ يوماً. يجب أن يقع كل موعد ضمن يوم واحد بتوقيت دبي وألا تتجاوز مدته ١٢ ساعة. يشمل التسجيل جميع المواعيد ويُغلق عند بداية الموعد الأول. لا تُحصّل أي مدفوعات.",
  "Number of dates": "عدد المواعيد",
  "No events available.": "لا توجد فعاليات متاحة.",
  "Book trial": "حجز تجربة",
  Assessment: "تقييم",
  "Open makeup credits": "أرصدة التعويض المتاحة",
  "REPORTING PERIOD": "فترة التقرير",
  Collections: "التحصيلات",
  "Reset to today": "العودة إلى اليوم",
  "Money received in period": "المبالغ المستلمة خلال الفترة",
  "Invoices issued in period": "الفواتير الصادرة خلال الفترة",
  "Outstanding balance (all time)": "إجمالي الرصيد المستحق",
  Sessions: "الحصص",
  "Primary navigation": "التنقل الرئيسي",
  "Open notifications": "فتح الإشعارات",
  Operations: "العمليات",
  Retry: "إعادة المحاولة",
  Date: "التاريخ",
  ...productArabic,
  ...academyArabic,
  ...engagementArabic,
  ...commercialArabic,
  ...developmentArabic,
  ...communityArabic,
  "My profile": "ملفي الشخصي",
  Saved: "تم الحفظ",
  Bio: "نبذة",
  "Qualifications (comma separated)": "المؤهلات (مفصولة بفواصل)",
  "Save profile": "حفظ الملف الشخصي",
  "Weekly availability": "التوافر الأسبوعي",
  "No availability submitted yet.": "لم يتم إرسال أي توافر بعد.",
  Remove: "إزالة",
  Day: "اليوم",
  "Add availability window": "إضافة فترة توافر",
  Sunday: "الأحد",
  Monday: "الاثنين",
  Tuesday: "الثلاثاء",
  Wednesday: "الأربعاء",
  Thursday: "الخميس",
  Friday: "الجمعة",
  Saturday: "السبت",
  Coaches: "المدربون",
  "No bio on file yet.": "لا توجد نبذة مسجلة بعد.",
  "No coaches assigned yet.": "لا يوجد مدربون معينون بعد.",
  "Business reports": "تقارير الأعمال",
  "Figures reflect loaded, authorized records for the selected period only.":
    "تعكس الأرقام السجلات المصرّح بها المحمّلة للفترة المحددة فقط.",
  Leads: "العملاء المحتملون",
  "Conversion rate": "معدل التحويل",
  "Lost rate": "معدل الفقد",
  "Sessions in period": "الحصص خلال الفترة",
  "Attendance rate": "معدل الحضور",
  "Not yet available": "غير متاح بعد",
  Invoiced: "المفوتر",
  Received: "المستلم",
  Outstanding: "المستحق",
  "Active memberships": "العضويات النشطة",
  "Expiring in period": "المنتهية خلال الفترة",
  "Sessions delivered": "الحصص المنفذة",
  Assessments: "التقييمات",
  "Published assessments": "التقييمات المنشورة",
  "Counts reflect loaded records. Load more for a fuller view.":
    "تعكس الأعداد السجلات المحمّلة. حمّل المزيد لعرض أشمل.",
  missed: "لم يحضر",
  "Family access code": "رمز الوصول للعائلة",
  "Accept family access from reception": "قبول الوصول للعائلة من الاستقبال",
  "Your account reference": "معرّف حسابك",
  "Parent account reference": "معرّف حساب ولي الأمر",
  "Issue family access code": "إصدار رمز الوصول للعائلة",
  "Give a verified parent family access": "منح ولي أمر موثّق حق الوصول للعائلة",
  "Enquiry saved. Choose an eligible session below to book your trial.":
    "تم حفظ الطلب. اختر حصة مناسبة أدناه لحجز التجربة.",
  "Check your preferences. After saving, sign in to see eligible trial sessions.":
    "راجع تفضيلاتك. بعد الحفظ، اعرض الحصص التجريبية المناسبة.",
  "Your assigned sessions are available in read-only view. Assessments open in a later phase.":
    "الحصص المعيّنة متاحة للعرض فقط. التقييمات متاحة في مرحلة لاحقة.",
  "Trial booking and attendance are available for configured sessions. Payments are not enabled.":
    "الحجز والحضور متاحان للحصص المضبوطة. المدفوعات غير مفعّلة.",
  excused: "بعذر",
  late: "متأخر",
  absent: "غائب",
  present: "حاضر",
  makeup: "تعويض",
  enrollment: "تسجيل",
  trial: "تجربة",
  active: "نشط",
  requested: "طلب قيد المعالجة",
  converted: "مسجّل",
  attended: "حضر التجربة",
  booked: "محجوزة",
  completed: "مكتملة",
  cancelled: "ملغاة",
  scheduled: "مجدولة",
  ai: "مساعد آلي",
  referral: "إحالة",
  walk_in: "زيارة مباشرة",
  phone: "الهاتف",
  whatsapp: "واتساب",
  social: "التواصل الاجتماعي",
  website: "الموقع الإلكتروني",
  unsure: "غير متأكد",
  training: "يتدرّب حالياً",
  some: "بعض الخبرة",
  beginner: "مبتدئ",
  badminton: "الريشة الطائرة",
  karate: "الكاراتيه",
  football: "كرة القدم",
  swimming: "السباحة",
  "Lead source": "مصدر العميل المحتمل",
  "New lead": "عميل محتمل جديد",
  "Create lead": "إنشاء عميل محتمل",
  "Read-only assigned sessions. Attendance editing and assessments are not enabled for coaches.":
    "الحصص المعيّنة للعرض فقط. تعديل الحضور والتقييمات غير متاحين للمدرّبين.",
  "Cancellation reason": "سبب الإلغاء",
  "Cancel session": "إلغاء الحصة",
  "Finalization becomes available when the session starts.":
    "يتاح اعتماد الحضور عند بدء الحصة.",
  "Finalize Attendance": "اعتماد الحضور",
  "Attendance finalized. Normal editing is locked.":
    "تم اعتماد الحضور. التعديل المعتاد مقفل.",
  Student: "الطالب",
  Attendance: "الحضور",
  Participation: "نوع المشاركة",
  "Mark All Present": "تحديد حضور الجميع",
  "No students on this roster.": "لا يوجد طلاب في هذه القائمة.",
  "Attendance roster": "قائمة الحضور",
  "Generate sharing code": "إنشاء رمز المشاركة",
  "Generate a single-use code for reception to link your child to an existing enquiry. Expires after 24 hours.":
    "أنشئ رمزاً للاستخدام مرة واحدة لربط طفلك بطلب موجود لدى الاستقبال. تنتهي صلاحيته بعد ٢٤ ساعة.",
  "Share family with reception": "مشاركة العائلة مع الاستقبال",
  "Package configuration pending. No payment has been collected.":
    "إعداد الباقة قيد الانتظار. لم تُحصّل أي دفعة.",
  "Active enrollments": "التسجيلات النشطة",
  "No trials yet.": "لا توجد تجارب بعد.",
  "Child reference": "معرّف الطفل",
  "Parent sharing code": "رمز المشاركة من ولي الأمر",
  "Link existing family": "ربط عائلة موجودة",
  "Link parent-authorized child": "ربط طفل بتفويض ولي الأمر",
  "Override reason": "سبب الاستثناء",
  Session: "الحصة",
  "Book with recorded override": "حجز مع توثيق الاستثناء",
  "Authorized allocation override": "استثناء التسكين المصرّح به",
  "Review starting level": "مراجعة المستوى الابتدائي",
  "Age override reason (only if required)":
    "سبب استثناء العمر (عند الحاجة فقط)",
  Class: "صف",
  "Convert to Member": "تسجيل كطالب نشط",
  "Cancel trial": "إلغاء التجربة",
  "Bookings reserve a dated session. Enquiries without a booking remain requests.":
    "يحجز الحجز حصة بتاريخ محدد. تبقى الاستفسارات دون حجز مجرد طلبات.",
  "Open roster": "فتح قائمة الحضور",
  "Dated sessions": "الحصص المؤرخة",
  "Resume bookings": "استئناف الحجوزات",
  "Pause new bookings": "إيقاف الحجوزات الجديدة",
  To: "إلى",
  From: "من",
  "Generate dated sessions": "إنشاء حصص مؤرخة",
  Inactive: "غير نشط",
  places: "مقاعد",
  "No classes configured yet.": "لم تُضبط الفصول بعد.",
  "Duration in minutes": "المدة بالدقائق",
  "Start time (UAE)": "وقت البداية (الإمارات)",
  "Weekdays (0 Sunday to 6 Saturday, separated by commas)":
    "أيام الأسبوع (٠ الأحد إلى ٦ السبت، مفصولة بفواصل إنجليزية)",
  Capacity: "السعة",
  "Age group": "الفئة العمرية",
  Level: "المستوى",
  Venue: "الموقع",
  "Class name": "اسم الفصل",
  "Class definition": "تعريف الفصل",
  "Create recurring class": "إنشاء فصل متكرر",
  "Maximum age": "الحد الأقصى للعمر",
  "Minimum age": "الحد الأدنى للعمر",
  "Age group name": "اسم الفئة العمرية",
  "Add age group": "إضافة فئة عمرية",
  "Beginner entry level": "المستوى الابتدائي للمبتدئين",
  "Level order": "ترتيب المستوى",
  "Level name": "اسم المستوى",
  "Add sport level": "إضافة مستوى رياضي",
  "Book free trial": "احجز تجربة مجانية",
  "Trial booked": "تم حجز التجربة",
  "places available": "مقاعد متاحة",
  "UAE time": "بتوقيت الإمارات",
  "No eligible sessions are available. Staff can review the starting level and timetable.":
    "لا توجد حصص مناسبة حالياً. يمكن للفريق مراجعة المستوى الابتدائي والجدول.",
  "Check available sessions": "عرض الحصص المتاحة",
  "Availability checks branch, sport, age, level and remaining places. A place is reserved only after confirmation.":
    "يتحقق التوفر من الفرع والرياضة والعمر والمستوى والمقاعد المتبقية. يُحجز المقعد بعد التأكيد فقط.",
  "Find an eligible trial": "ابحث عن تجربة مناسبة",
  "sessions today in loaded records": "حصص اليوم ضمن السجلات المحمّلة",
  "follow-ups due in loaded records": "متابعات مستحقة ضمن السجلات المحمّلة",
  "Upcoming trials and active enrollments appear in Trials.":
    "تظهر التجارب القادمة والتسجيلات النشطة في صفحة التجارب.",
  "Operational overview": "نظرة تشغيلية",
  "Your next sporting step": "خطوتك الرياضية القادمة",
  Converted: "مسجّل نشط",
  "Trial Attended": "حضر التجربة",
  "Trial Booked": "تم حجز التجربة",
  "Assigned sessions": "الحصص المعيّنة",
  "Classes / Sessions": "الفصول والحصص",
  "Sports / Levels": "الرياضات والمستويات",
  Trials: "التجارب",
  "Staging workspace · synthetic academy records only":
    "بيئة اختبار · بيانات أكاديمية تجريبية فقط",
  "If an account exists for this email, you will receive reset instructions.":
    "إذا وُجد حساب بهذا البريد الإلكتروني، فستصلك إرشادات استعادة كلمة المرور.",
  "Check your email to continue creating your account.":
    "تحقّق من بريدك الإلكتروني لإكمال إنشاء حسابك.",
  "Load more records": "تحميل المزيد من السجلات",
  "Choose a child from your family": "اختر طفلاً من عائلتك",
  "Enter another child": "إدخال طفل آخر",
  "Academy website": "موقع الأكاديمية",
  "Sign out": "تسجيل الخروج",
  "Staging workspace · synthetic records only · no live bookings":
    "بيئة اختبار · بيانات تجريبية فقط · لا توجد حجوزات فعلية",
  "Your workspace": "مساحة عملك",
  "Super Admin": "المدير العام",
  "Owner (Super Admin)": "المالك (المدير العام)",
  Parent: "وليّ الأمر",
  Branch: "الفرع",
  Account: "الحساب",
  Overview: "نظرة عامة",
  Enquiries: "الاستفسارات",
  Families: "العائلات",
  Family: "العائلة",
  Branches: "الفروع",
  Team: "الفريق",
  Audit: "سجل التغييرات",
  Security: "الأمان",
  "Switch workspace": "تبديل مساحة العمل",
  "Workspace navigation": "التنقّل في مساحة العمل",
  "Loading…": "جارٍ التحميل…",
  Refresh: "تحديث",
  "Loading your workspace…": "جارٍ تحميل مساحة العمل…",
  "A stronger start, together.": "معاً لبداية أقوى.",
  "Welcome to your KAFOU workspace.": "أهلاً بك في مساحة كفو.",
  "Your coach account is ready. Student access opens when sessions and coach assignments are configured.":
    "حساب المدرّب جاهز. يتاح الوصول إلى الطلاب بعد إعداد الحصص وتعيين المدرّبين.",
  "Manage the first steps of each sporting journey. Only records permitted for your account appear here.":
    "تابع الخطوات الأولى لكل رحلة رياضية. تظهر هنا السجلات المسموح لحسابك بالوصول إليها فقط.",
  "Manage your family": "إدارة عائلتك",
  "Open enquiry queue": "عرض الاستفسارات",
  "Send a trial enquiry": "إرسال طلب تجربة",
  "Scheduling, attendance and payments are not active in this phase.":
    "الجداول والحضور والمدفوعات غير مفعّلة في هذه المرحلة.",
  "Your submitted enquiries. A reference is not a confirmed trial booking.":
    "طلباتك المرسلة. الرقم المرجعي لا يعني تأكيد حجز تجربة.",
  "No enquiries yet.": "لا توجد طلبات بعد.",
  Reference: "الرقم المرجعي",
  Child: "الطفل",
  Status: "الحالة",
  "Enquiry received": "تم استلام الطلب",
  "Follow up with families and prepare their next step.":
    "تابع العائلات وساعدها على الاستعداد للخطوة التالية.",
  "No enquiries in your permitted branches.":
    "لا توجد استفسارات في الفروع المتاحة لك.",
  "Family contact": "التواصل مع العائلة",
  Stage: "المرحلة",
  "Follow-up": "المتابعة",
  Action: "الإجراء",
  "Possible duplicate · review required": "تكرار محتمل · يلزم التحقق",
  "Not set": "غير محدد",
  "Open enquiry": "عرض الطلب",
  "Back to enquiries": "العودة إلى الطلبات",
  "Update enquiry": "تحديث الطلب",
  "Assigned staff": "الموظف المسؤول",
  Unassigned: "غير معيّن",
  "Lost reason": "سبب عدم الاستمرار",
  "Add an interaction": "إضافة تواصل",
  Note: "ملاحظة",
  "Create or link a family": "إنشاء عائلة أو ربطها",
  "Create a new family": "إنشاء عائلة جديدة",
  "Link family and child": "ربط العائلة والطفل",
  "Family linked. No enrollment or sale has been created.":
    "تم ربط العائلة. لم يتم إنشاء تسجيل أو عملية بيع.",
  "Interaction timeline": "سجل التواصل",
  "Create your family profile": "إنشاء ملف عائلتك",
  "Family name": "اسم العائلة",
  "No families are linked to your permitted branches.":
    "لا توجد عائلات مرتبطة بالفروع المتاحة لك.",
  "Select family": "اختر العائلة",
  "Family contact information": "بيانات التواصل مع العائلة",
  Children: "الأطفال",
  "View profile": "عرض الملف",
  "Child profile": "ملف الطفل",
  "Child name": "اسم الطفل",
  Age: "العمر",
  "Date of birth (optional)": "تاريخ الميلاد (اختياري)",
  "Level to be assessed": "المستوى بانتظار التقييم",
  "Add a sport interest": "إضافة رياضة مفضّلة",
  "Reviewed starting level (optional)": "المستوى الأولي المعتمد (اختياري)",
  "Add a child": "إضافة طفل",
  "Consent preferences": "تفضيلات الموافقة",
  "Staging consent examples only. Approved academy policies are required before live intake.":
    "أمثلة تجريبية للموافقة فقط. يلزم اعتماد سياسات الأكاديمية قبل استقبال بيانات فعلية.",
  "Contact updates": "رسائل التحديث",
  "Photo and media use": "استخدام الصور والوسائط",
  Allowed: "مسموح",
  "Not allowed": "غير مسموح",
  Withdraw: "سحب الموافقة",
  Allow: "الموافقة",
  "Provisional preferences are not confirmed venues. Confirm actual details before publishing availability.":
    "الخيارات المؤقتة ليست مواقع معتمدة. تحقّق من التفاصيل قبل نشر التوفّر.",
  Provisional: "مؤقت",
  Confirmed: "معتمد",
  "Branch details": "تفاصيل الفرع",
  "Branch name": "اسم الفرع",
  "Arabic name": "الاسم بالعربية",
  Area: "المنطقة",
  "Mark details confirmed": "اعتماد التفاصيل",
  "Mark provisional": "تعيين كمؤقت",
  Deactivate: "إلغاء التفعيل",
  Activate: "تفعيل",
  Venues: "المواقع",
  "Add a venue": "إضافة موقع",
  "Venue name": "اسم الموقع",
  Address: "العنوان",
  "Operating information": "معلومات التشغيل",
  "Add a branch preference": "إضافة خيار فرع",
  "URL label": "الاسم المختصر للرابط",
  "Available sports": "الرياضات المتاحة",
  "Save sports": "حفظ الرياضات",
  Save: "حفظ",
  "Saving…": "جارٍ الحفظ…",
  "Saved.": "تم الحفظ.",
  "Staff accounts are invitation-only. Permission changes require administrator verification.":
    "حسابات الموظفين بالدعوة فقط. تتطلّب تغييرات الصلاحيات تحقق المدير.",
  "Invite staff": "دعوة موظف",
  Role: "الدور",
  "Send invitation": "إرسال الدعوة",
  "Invitation sent.": "تم إرسال الدعوة.",
  Active: "نشط",
  Suspended: "موقوف",
  "Account active": "الحساب نشط",
  "Save access": "حفظ الصلاحيات",
  Invitations: "الدعوات",
  Accepted: "مقبولة",
  Revoked: "ملغاة",
  Pending: "قيد الانتظار",
  "Permitted branches": "الفروع المسموح بها",
  "Protected change history. Contact details and passwords are excluded.":
    "سجل تغييرات محمي. لا يتضمن بيانات التواصل أو كلمات المرور.",
  Time: "الوقت",
  Record: "السجل",
  Actor: "المنفّذ",
  "Change details": "تفاصيل التغيير",
  System: "النظام",
  "Staging workspace": "مساحة الاختبار",
  "Secure your account": "حماية حسابك",
  "Verify your authenticator before using administrator tools.":
    "تحقّق بتطبيق المصادقة قبل استخدام أدوات الإدارة.",
  "Use an authenticator app for an extra layer of account security.":
    "استخدم تطبيق مصادقة لتعزيز أمان حسابك.",
  "Set up authenticator": "إعداد تطبيق المصادقة",
  "Scan this code with your authenticator app":
    "امسح الرمز باستخدام تطبيق المصادقة",
  "Manual setup key": "مفتاح الإعداد اليدوي",
  "Six-digit authenticator code": "رمز المصادقة المكوّن من ستة أرقام",
  Verify: "تحقّق",
  "Account security": "أمان الحساب",
  "Choose a new password.": "اختر كلمة مرور جديدة.",
  "Confirming your account.": "جارٍ تأكيد حسابك.",
  "Please wait…": "يرجى الانتظار…",
  "Update password": "تحديث كلمة المرور",
  "Password updated. Sign in with your new password.":
    "تم تحديث كلمة المرور. سجّل الدخول بكلمة المرور الجديدة.",
  New: "جديد",
  Contacted: "تم التواصل",
  Interested: "مهتم",
  "Trial Offered": "عُرضت تجربة",
  Lost: "لم يستمر",
  "branch preferences": "خيارات فروع",
  "Branch preferences": "خيارات الفروع",
  "Choose a branch": "اختر الفرع",
  "Your email address": "بريدك الإلكتروني",
  "Staging accounts only. Use synthetic details; live family intake is not open.":
    "حسابات اختبار فقط. استخدم بيانات تجريبية؛ استقبال العائلات الفعلي لم يبدأ.",
  "Staging only. Use synthetic details. Submitting saves an enquiry, not a booking.":
    "للاختبار فقط. استخدم بيانات تجريبية. الإرسال يحفظ طلباً ولا يؤكّد حجزاً.",
  "Send trial enquiry": "إرسال طلب تجربة",
  "Your trial enquiry has been received. A trial is not booked until the academy confirms a time.":
    "تم استلام طلب التجربة. لا يُعدّ حجزاً حتى تؤكّد الأكاديمية الموعد.",
  "The service could not complete this request. Please try again.":
    "تعذّر إكمال الطلب. يرجى المحاولة مجدداً.",
  "Please sign in to continue.": "يرجى تسجيل الدخول للمتابعة.",
  "This account has no academy access.":
    "لا يملك هذا الحساب صلاحية دخول الأكاديمية.",
  "This account is suspended. Contact the academy.":
    "هذا الحساب موقوف. يرجى التواصل مع الأكاديمية.",
  "You do not have permission for this action.":
    "ليست لديك صلاحية تنفيذ هذا الإجراء.",
  "This record or request already exists. Refresh and try again.":
    "السجل أو الطلب موجود مسبقاً. حدّث الصفحة وحاول مجدداً.",
  "The record was not found or is unchanged.": "السجل غير موجود أو لم يتغيّر.",
  "Check the information and try again.": "تحقّق من البيانات وحاول مجدداً.",
  "Too many attempts. Please try again later.":
    "محاولات كثيرة. يرجى المحاولة لاحقاً.",
  "Email or password is incorrect, or email verification is required.":
    "البريد أو كلمة المرور غير صحيحين، أو يلزم تأكيد البريد الإلكتروني.",
  "Staging email delivery is not configured. Account creation is unavailable.":
    "إرسال البريد في بيئة الاختبار غير مهيّأ. إنشاء الحساب غير متاح حالياً.",
  "Staging email delivery is not configured. Recovery email is unavailable.":
    "إرسال البريد في بيئة الاختبار غير مهيّأ. رسالة الاستعادة غير متاحة.",
  "Staging email delivery is not configured. Invitations cannot be sent.":
    "إرسال البريد في بيئة الاختبار غير مهيّأ. لا يمكن إرسال الدعوات.",
  "This link is invalid or expired. Request a new link.":
    "الرابط غير صالح أو انتهت صلاحيته. اطلب رابطاً جديداً.",
  "The verification code is incorrect or expired.":
    "رمز التحقق غير صحيح أو انتهت صلاحيته.",
  "Administrator verification is required.": "يلزم تحقق المدير.",
  "Invitation could not be sent. The email may already have an account.":
    "تعذّر إرسال الدعوة. قد يكون البريد مرتبطاً بحساب موجود.",
  "Trial enquiry received; no session reserved.":
    "تم استلام طلب التجربة؛ لم تُحجز حصة.",
  "Enquiry status or assignment updated.": "تم تحديث حالة الطلب أو تعيينه.",
  "Family and child linked. No enrollment or sale created.":
    "تم ربط العائلة والطفل. لم يتم إنشاء تسجيل أو بيع.",
  "Head Office": "الإدارة المركزية",
  "Family workspace": "مساحة العائلة",
  "Sales workspace": "مساحة المبيعات",
  "Coach workspace": "مساحة المدرب",
  "Your workspaces": "مساحات العمل",
  Workspace: "مساحة العمل",
  "Built around every child.": "كل طفل في قلب اهتمامنا.",
  "Search workspace": "البحث في مساحة العمل",
  "Action center": "مركز المتابعة",
  "Profile and security": "الملف والأمان",
  "Open navigation": "فتح القائمة",
  "Filter branch": "تصفية حسب الفرع",
  "All permitted branches": "جميع الفروع المصرّح بها",
  "Quick action": "إجراء سريع",
  "Choose your workspace": "اختر مساحة عملك",
  "Your day, in focus.": "يومك، بوضوح.",
  "Every conversation counts.": "كل تواصل يصنع فرقاً.",
  "Academy overview": "نظرة على الأكاديمية",
  "Secure access. Shared purpose.": "وصول آمن. هدف مشترك.",
  "Close panel": "إغلاق اللوحة",
  "Search the permitted records currently loaded in your workspace.":
    "ابحث في السجلات المصرّح بها والمحمّلة حالياً في مساحة عملك.",
  "Search children, families, leads or classes":
    "ابحث عن طفل أو عائلة أو عميل أو صف",
  "Search records": "البحث في السجلات",
  "No matching records": "لا توجد نتائج مطابقة",
  "Try another name or load more records.":
    "جرّب اسماً آخر أو حمّل المزيد من السجلات.",
  "Type a name, sport or reference to begin.":
    "اكتب اسماً أو رياضة أو رقماً مرجعياً للبدء.",
  "Operational reminders from your loaded records.":
    "تذكيرات تشغيلية من السجلات المحمّلة.",
  "You’re all caught up": "أنت على اطّلاع بكل شيء",
  "No pending actions in the records currently loaded.":
    "لا توجد إجراءات معلّقة في السجلات المحمّلة حالياً.",
  "Follow-ups due": "متابعات مستحقة",
  "Reconnect with families awaiting their next step.":
    "تواصل مع العائلات التي تنتظر خطوتها التالية.",
  "Attendance pending": "حضور بانتظار الاعتماد",
  "Review started sessions and finalize the roster.":
    "راجع الحصص التي بدأت واعتمد سجل الحضور.",
  "Ready for conversion": "جاهزة للتسجيل",
  "Help an attended trial become the next chapter.":
    "حوّل التجربة المكتملة إلى بداية جديدة.",
  "Take the next step": "ابدأ الخطوة التالية",
  "View trial status": "عرض حالة التجربة",
  "View schedule": "عرض الجدول",
  "Book a trial": "حجز تجربة",
  "Open attendance": "فتح الحضور",
  "Find a family": "البحث عن عائلة",
  "Your account": "حسابك",
  "Changes saved": "تم حفظ التغييرات",
  "Dismiss notification": "إغلاق التنبيه",
  "ONE ACADEMY": "أكاديمية واحدة",
  "Good to have you here.": "سعداء بوجودك معنا.",
  "Choose where you want to work. Your permissions follow you, wherever you go.":
    "اختر مساحة عملك. تبقى صلاحياتك محددة في كل مساحة.",
  "YOUR ACCESS": "وصولك",
  "Your children, their sessions, your next step.":
    "أطفالك وحصصهم وخطوتكم التالية.",
  "Your assigned sessions and athletes, in one place.":
    "حصصك والرياضيون المكلّف بهم، في مكان واحد.",
  "Meaningful conversations. Confident next steps.": "تواصل هادف. خطوات واثقة.",
  "People, sessions and the details that keep the academy moving.":
    "الأشخاص والحصص والتفاصيل التي تنظّم عمل الأكاديمية.",
  "Open workspace": "فتح مساحة العمل",
  "Workspace selection never changes your access permissions.":
    "اختيار مساحة العمل لا يغيّر صلاحيات الوصول.",
  "YOUR FAMILY. THEIR FUTURE.": "عائلتك. مستقبلهم.",
  "Small steps. Lasting confidence.": "خطوات صغيرة. ثقة تدوم.",
  "Keep their sporting journey close. See what’s next, explore their sports and take care of the details.":
    "تابع رحلتهم الرياضية. اطّلع على القادم، واكتشف رياضاتهم، واهتم بالتفاصيل.",
  "GROWING TOGETHER": "ننمو معاً",
  "Your young athletes": "رياضيّوك الصغار",
  "Athlete profile": "ملف الرياضي",
  "Their next sport starts here.": "رياضتهم التالية تبدأ هنا.",
  "Next class": "الحصة القادمة",
  "No class scheduled yet": "لا توجد حصة مجدولة بعد",
  "Their journey starts here": "رحلتهم تبدأ هنا",
  "Add your child to keep their sports and next steps together.":
    "أضف طفلك لمتابعة رياضاته وخطواته القادمة في مكان واحد.",
  "Coming up": "القادم",
  "Room for a new beginning": "مساحة لبداية جديدة",
  "A confirmed trial or class will appear here.":
    "ستظهر هنا التجارب أو الحصص المؤكدة.",
  "Everything in its place": "كل شيء في مكانه",
  "Family details": "بيانات العائلة",
  "Keep contact information and consent choices up to date.":
    "حدّث بيانات التواصل وخيارات الموافقة.",
  "Trials and enrollment": "التجارب والتسجيل",
  "Follow each enquiry from first interest to a confirmed place.":
    "تابع كل طلب من الاهتمام الأول حتى تأكيد المكان.",
  "Manage your authenticator and protect your family account.":
    "أدر تطبيق المصادقة واحمِ حساب عائلتك.",
  "A sporting journey, one step at a time.": "رحلة رياضية، خطوة بخطوة.",
  "Sport-specific levels": "مستويات مستقلة لكل رياضة",
  "Assessments and progress history will be available in the next operational phase.":
    "ستتوفر التقييمات وسجلات التطور في المرحلة التشغيلية القادمة.",
  "Edit child details": "تعديل بيانات الطفل",
  "FOCUS ON THE SESSION": "ركّز على الحصة",
  "Your athletes. Your next session.": "رياضيّوك. حصتك القادمة.",
  "A clear view of your assigned timetable and roster. Student data stays limited to your assignments.":
    "عرض واضح لجدولك وقوائم حصصك. تقتصر بيانات الطلاب على مهامك المعيّنة.",
  "Your schedule": "جدولك",
  sessions: "حصص",
  "students on roster": "طلاب في القائمة",
  "Your schedule is clear": "جدولك خالٍ حالياً",
  "Assigned sessions will appear here when the academy adds them.":
    "ستظهر الحصص المعيّنة لك عندما تضيفها الأكاديمية.",
  "New leads": "عملاء محتملون جدد",
  "Trials booked": "تجارب محجوزة",
  "Active students": "طلاب نشطون",
  "Sessions today": "حصص اليوم",
  "Trials today": "تجارب اليوم",
  "Attendance today": "حضور اليوم",
  "Finalized sessions only": "الحصص المعتمدة فقط",
  "In loaded records": "في السجلات المحمّلة",
  "Turn interest into a confident first session.":
    "حوّل الاهتمام إلى حصة أولى بثقة.",
  "A clear view of today. The right next step for every family.":
    "رؤية واضحة لليوم. والخطوة المناسبة لكل عائلة.",
  "YOUR NEXT CONVERSATIONS": "تواصلك القادم",
  "THE ACADEMY, IN MOTION": "الأكاديمية تنبض بالحركة",
  "Today’s schedule": "جدول اليوم",
  "View all": "عرض الكل",
  "Your follow-ups are clear": "لا توجد متابعات مستحقة",
  "Set the next follow-up inside a lead to keep the conversation moving.":
    "حدّد موعد المتابعة داخل ملف العميل للحفاظ على التواصل.",
  "A little breathing room": "فسحة في الجدول",
  "No sessions are scheduled today in the loaded records.":
    "لا توجد حصص مجدولة اليوم في السجلات المحمّلة.",
  "KEEP THINGS MOVING": "حافظ على سير العمل",
  "Attention required": "يتطلب المتابعة",
  "Based on your current branch view and permitted records.":
    "استناداً إلى الفرع المعروض والسجلات المصرّح بها.",
  "Pipeline at a glance": "مسار العملاء بنظرة واحدة",
  "Open pipeline": "فتح مسار العملاء",
  "Across the academy": "عبر الأكاديمية",
  "Operational branches": "الفروع التشغيلية",
  "Search leads": "البحث عن العملاء",
  "Filter stage": "تصفية حسب المرحلة",
  "All stages": "جميع المراحل",
  Board: "لوحة",
  List: "قائمة",
  "leads in this view": "عملاء في هذا العرض",
  "Booking, attendance and conversion update the pipeline automatically.":
    "يحدّث الحجز والحضور والتسجيل مراحل العميل تلقائياً.",
  "No leads in this view": "لا يوجد عملاء في هذا العرض",
  "Try another filter or start a new conversation.":
    "جرّب تصفية أخرى أو ابدأ تواصلاً جديداً.",
  "Sales pipeline": "مسار المبيعات",
  "No leads here yet": "لا يوجد عملاء هنا بعد",
  "Child details pending": "بانتظار بيانات الطفل",
  "Sport to be selected": "لم تُحدّد الرياضة",
  "Review possible duplicate": "مراجعة تكرار محتمل",
  "Start a conversation": "ابدأ تواصلاً جديداً",
  "Capture the essentials. Keep the next step clear.":
    "سجّل المعلومات الأساسية وحدّد الخطوة التالية بوضوح.",
  "Lead profile and next actions": "ملف العميل والإجراءات القادمة",
  "Review trial options": "مراجعة خيارات التجربة",
  "Call family": "الاتصال بالعائلة",
  "Link an existing family account": "ربط حساب عائلة موجود",
  "Session details": "تفاصيل الحصة",
  Lead: "عميل محتمل",
  Trial: "تجربة",
  trial_booked: "تجربة محجوزة",
  trial_attended: "تجربة مكتملة",
  contacted: "تم التواصل",
  new: "جديد",
  lost: "غير مستمر",
  "Unsaved changes": "تغييرات غير محفوظة",
  "Keep editing, or discard this draft before leaving. Wait for any save to finish.":
    "تابع التعديل أو تجاهل المسودة قبل المغادرة. انتظر اكتمال أي عملية حفظ.",
  "Keep editing": "متابعة التعديل",
  "Discard changes": "تجاهل التغييرات",
  "Walk-in": "زيارة مباشرة",
  Website: "الموقع الإلكتروني",
  Social: "التواصل الاجتماعي",
  Phone: "الهاتف",
  Referral: "إحالة",
  Ai: "مساعد آلي",
  Whatsapp: "واتساب",
  Scheduled: "مجدولة",
  Completed: "مكتملة",
  Present: "حاضر",
  Absent: "غائب",
  Late: "متأخر",
  Excused: "بعذر",
  Missed: "لم يحضر",
  Requested: "مطلوبة",
  Booked: "محجوزة",
  Attended: "حضر",
  Cancelled: "ملغاة",
  "Session view": "عرض الحصص",
  "All sessions": "جميع الحصص",
  Today: "اليوم",
  "Session date": "تاريخ الحصة",
  "Clear date": "مسح التاريخ",
  "No sessions in this view.": "لا توجد حصص في هذا العرض.",
  View: "العرض",
  "Session roster": "قائمة الحصة",
  Enrollment: "تسجيل",
  ...dailyArabic,
};
