export const communityArabic: Record<string, string> = {
  "Linked guardians": "أولياء الأمور المرتبطون",
  "Family and community": "الأسرة والمجتمع",
  "Community sections": "أقسام الأسرة والمجتمع",
  Notifications: "الإشعارات",
  Support: "الدعم",
  "Family access": "صلاحيات الأسرة",
  Documents: "المستندات",
  Recognition: "التكريم",
  Handover: "تسليم المناوبة",
  "Notifications appear inside this account. Email, WhatsApp, and push delivery are not configured; queued records are not delivery confirmation.":
    "تظهر الإشعارات داخل هذا الحساب. لم تُعد قنوات البريد الإلكتروني وواتساب والإشعارات الفورية؛ ووجود سجل في قائمة الانتظار لا يعني تأكيد التسليم.",
  "No notifications are available for this account.":
    "لا توجد إشعارات متاحة لهذا الحساب.",
  Read: "مقروء",
  Unread: "غير مقروء",
  "Open related record": "فتح السجل المرتبط",
  "Mark as read": "تحديد كمقروء",
  "No support conversations are available in your permitted scope.":
    "لا توجد محادثات دعم ضمن نطاق صلاحياتك.",
  "Linked invoice": "الفاتورة المرتبطة",
  "Assigned to": "المسؤول",
  "Academy staff": "فريق الأكاديمية",
  You: "أنت",
  Participant: "مشارك",
  Resolution: "الحل",
  Message: "الرسالة",
  "Reply to conversation": "الرد على المحادثة",
  "Send reply": "إرسال الرد",
  "Resolve conversation": "إغلاق المحادثة بعد الحل",
  "Record a resolution": "تسجيل الحل",
  "Open a support conversation": "بدء محادثة دعم",
  Subject: "الموضوع",
  "Child (optional)": "الطفل (اختياري)",
  "Session (optional)": "الحصة (اختياري)",
  "Invoice (optional)": "الفاتورة (اختياري)",
  "Create support conversation": "إنشاء محادثة دعم",
  "Assign support conversation": "تعيين مسؤول للمحادثة",
  Conversation: "المحادثة",
  open: "مفتوحة",
  in_progress: "قيد المعالجة",
  resolved: "تم الحل",
  "Your account ID": "معرّف حسابك",
  "Guardianship links provide access to the whole family. An invitation is accepted only by its named, verified parent account; matching an email address does not grant access.":
    "تتيح روابط الوصاية الوصول إلى بيانات الأسرة كاملة. لا يقبل الدعوة إلا حساب ولي الأمر الموثّق والمحدد فيها؛ وتطابق البريد الإلكتروني وحده لا يمنح الصلاحية.",
  "Emergency contact": "جهة اتصال الطوارئ",
  "Save emergency contact": "حفظ جهة اتصال الطوارئ",
  "Contact name": "اسم جهة الاتصال",
  "Mobile number": "رقم الهاتف المتحرك",
  Relationship: "صلة القرابة",
  "Invite another guardian": "دعوة ولي أمر آخر",
  "Ask the guardian for their verified parent account ID. The invitation grants access to this whole family. Share its one-time code privately; it expires after 24 hours.":
    "اطلب من ولي الأمر معرّف حسابه الموثّق. تمنح الدعوة صلاحية الوصول إلى الأسرة كاملة. شارك رمزها لمرة واحدة بشكل خاص؛ وتنتهي صلاحيته بعد 24 ساعة.",
  "Verified parent account ID": "معرّف حساب ولي الأمر الموثّق",
  "Create private invitation code": "إنشاء رمز دعوة خاص",
  "Private invitation code": "رمز الدعوة الخاص",
  "Only the invited parent account can accept this code.":
    "لا يقبل هذا الرمز إلا حساب ولي الأمر المدعو.",
  "Invitation code": "رمز الدعوة",
  "Hide code": "إخفاء الرمز",
  "Invitation code was not returned.": "لم يُرجع النظام رمز الدعوة.",
  "Revoke an invited guardian": "إلغاء صلاحية ولي أمر مدعو",
  "Invited guardian account ID": "معرّف حساب ولي الأمر المدعو",
  "Revoke family access": "إلغاء الوصول إلى الأسرة",
  "Only access created by your invitation can be removed. Revoking a pending invitation preserves independently granted family access.":
    "يمكنك إزالة الوصول الذي أنشأته دعوتك فقط. إلغاء دعوة معلقة لا يلغي وصولاً مُنح إلى الأسرة بشكل مستقل.",
  "Accept a guardian invitation": "قبول دعوة ولي أمر",
  "Accept family access": "قبول الوصول إلى الأسرة",
  "Handover notes coordinate follow-up. They do not verify a pickup, authorize release of a child, or replace safeguarding checks.":
    "تنظم ملاحظات المناوبة المتابعة، ولا تثبت استلام الطفل أو تجيز تسليمه أو تستبدل إجراءات حمايته.",
  "No handovers are available in your permitted scope.":
    "لا توجد سجلات مناوبة ضمن نطاق صلاحياتك.",
  Unassigned: "غير معيّن",
  "Follow-up": "المتابعة",
  "Close handover": "إغلاق سجل المناوبة",
  "Create shift handover": "إنشاء سجل تسليم المناوبة",
  Title: "العنوان",
  "Handover note": "ملاحظة المناوبة",
  "Assign to (optional)": "تعيين مسؤول (اختياري)",
  "Follow-up time (your device timezone)": "وقت المتابعة (بتوقيت جهازك)",
  "Create handover": "إنشاء سجل المناوبة",
  "Choose a valid follow-up time.": "اختر وقت متابعة صالحاً.",
  "Document versions are synthetic until the academy approves their wording. Acceptance records the signed-in guardian’s explicit choice for that version; it is not a handwritten signature.":
    "نسخ المستندات تجريبية حتى تعتمد الأكاديمية صياغتها. يسجل القبول الاختيار الصريح لولي الأمر المسجّل لتلك النسخة، ولا يمثل توقيعاً بخط اليد.",
  "No document versions are available.": "لا توجد نسخ مستندات متاحة.",
  Version: "النسخة",
  "Acceptance history": "سجل القبول",
  Accepted: "مقبول",
  Withdrawn: "مسحوب",
  Guardian: "ولي الأمر",
  "I have read this exact document version and choose to accept it for my family.":
    "قرأت هذه النسخة المحددة من المستند وأختار قبولها لأسرتي.",
  "Record my acceptance": "تسجيل موافقتي",
  "Withdraw my acceptance": "سحب موافقتي",
  "Create a document version": "إنشاء نسخة مستند",
  "Document title": "عنوان المستند",
  Purpose: "الغرض",
  "Full document text": "نص المستند الكامل",
  privacy: "الخصوصية",
  waiver: "الإقرار",
  media: "الصور والوسائط",
  contact: "التواصل",
  "Recognition needs an independent review before appearing to a family. Approval does not publish a child’s identity or image publicly and does not create a cash reward.":
    "يحتاج التكريم إلى مراجعة مستقلة قبل ظهوره للأسرة. لا ينشر الاعتماد هوية الطفل أو صورته علناً ولا ينشئ مكافأة نقدية.",
  "No recognition records are available in your permitted scope.":
    "لا توجد سجلات تكريم ضمن نطاق صلاحياتك.",
  Review: "المراجعة",
  "Nominate recognition": "ترشيح للتكريم",
  "Recognition title": "عنوان التكريم",
  Evidence: "الأدلة",
  "Review recognition nomination": "مراجعة ترشيح التكريم",
  Nomination: "الترشيح",
  "Return for review": "إعادة للمراجعة",
  "Review reason": "سبب القرار",
  submitted: "مقدم للمراجعة",
  returned: "معاد للمراجعة",
  "Support response": "رد الدعم",
  "There is a new message in your support conversation.":
    "توجد رسالة جديدة في محادثة الدعم الخاصة بك.",
  "Recognition approved": "تم اعتماد التكريم",
  "Verified parent account required": "يلزم حساب ولي أمر موثّق",
  "Offer unavailable": "الدعوة غير متاحة",
  "Only your invited guardian can be revoked here":
    "يمكنك هنا إلغاء صلاحية ولي الأمر الذي دعوته فقط",
  "Ticket resolved": "تم إغلاق المحادثة بعد الحل",
  "Invalid assignee": "المسؤول المحدد غير صالح",
  "Context not authorized": "السياق المحدد غير مصرح به",
  "Session not authorized": "الحصة المحددة غير مصرح بها",
  "Invoice not authorized": "الفاتورة المحددة غير مصرح بها",
  "Branch assignee required": "يلزم اختيار مسؤول مخوّل للفرع",
  "Independent review required": "تلزم مراجعة مستقلة",
};
