/** Development module copy merged into useLocale by the shared locale provider. */
export const developmentArabic: Record<string, string> = {
  "Target draft": "مسودة الهدف",
  "Target awaiting review": "الهدف بانتظار المراجعة",
  "Target approved": "تم اعتماد الهدف",
  "Target returned for revision": "أعيد الهدف للتعديل",
  "Active target": "هدف قيد العمل",
  "Completion awaiting review": "الإنجاز بانتظار المراجعة",
  "Target completed": "تم إنجاز الهدف",
  "Target withdrawn": "تم سحب الهدف",
  "Completion returned for revision": "أعيد إثبات الإنجاز للتعديل",
  "Measurable training goal": "هدف تدريبي قابل للقياس",
  "Target measurement": "القياس المستهدف",
  "Target date": "التاريخ المستهدف",
  "Tracked training targets": "أهداف التدريب المتتبعة",
  "Each goal keeps its published baseline, measurement and target date. Later published evidence is checked independently before completion is confirmed.":
    "يحتفظ كل هدف بقياس البداية المنشور والقيمة والتاريخ المستهدفين. تُراجع الأدلة المنشورة اللاحقة بشكل مستقل قبل تأكيد الإنجاز.",
  "Create tracked target": "إنشاء هدف متتبع",
  "Published baseline measurement": "قياس البداية المنشور",
  "The target must improve this baseline within the same criterion range. Choose a date within the next 366 days.":
    "يجب أن يحسّن الهدف قياس البداية ضمن نطاق المعيار نفسه. اختر تاريخاً خلال الأيام الـ٣٦٦ المقبلة.",
  "Draft training target": "مسودة هدف تدريبي",
  "Save target draft": "حفظ مسودة الهدف",
  "A published measurement for an assigned athlete is needed before creating a tracked target.":
    "يلزم قياس منشور لرياضي ضمن حصصك المكلّف بها قبل إنشاء هدف متتبع.",
  "No tracked targets in this view yet.":
    "لا توجد أهداف متتبعة في هذا العرض بعد.",
  "Training target": "هدف تدريبي",
  Baseline: "قياس البداية",
  "Completion evidence": "دليل الإنجاز",
  "Edit target draft": "تعديل مسودة الهدف",
  "Submit target for review": "إرسال الهدف للمراجعة",
  "Review training target": "مراجعة الهدف التدريبي",
  "Publish training target": "نشر الهدف التدريبي",
  "Submit target completion": "إرسال إثبات إنجاز الهدف",
  "Later published measurement": "قياس لاحق منشور",
  "Submit completion evidence": "إرسال دليل الإنجاز",
  "Completion needs a later measurement in this exact metric version, published after the target, that reaches the goal.":
    "يتطلب الإنجاز قياساً لاحقاً ضمن إصدار المعيار نفسه، منشوراً بعد الهدف ويحقق القيمة المستهدفة.",
  "Review target completion": "مراجعة إنجاز الهدف",
  "Withdraw training target": "سحب الهدف التدريبي",
  "Internal target review history": "سجل المراجعة الداخلي للهدف",
  "Target history": "سجل الهدف",
  Enabled: "مفعّل",
  Disabled: "معطّل",

  "Download published report PDF": "تنزيل التقرير المنشور بصيغة PDF",
  "Session emergency contacts": "جهات اتصال الطوارئ للحصة",
  "Use these current contacts only for the assigned session. Details are available within the academy's configured window and close when the session ends.":
    "استخدم جهات الاتصال الحالية للحصة المكلّف بها فقط. تظهر التفاصيل ضمن الفترة التي تحددها الأكاديمية وتُحجب عند انتهاء الحصة.",
  "No emergency contacts are available in your current session window.":
    "لا تتوفر جهات اتصال طوارئ ضمن فترة الحصة الحالية.",
  "Emergency contact visibility policy": "سياسة إتاحة جهات اتصال الطوارئ",
  "Disabled until explicitly configured. A policy shares only the current emergency contact with assigned coaches for rostered children, from the configured lead time until the session ends.":
    "تظل الإتاحة معطلة حتى ضبطها صراحة. تتيح السياسة جهة اتصال الطوارئ الحالية فقط للمدربين المكلّفين بالأطفال المدرجين في الحصة، من الوقت المحدد قبل بدايتها حتى نهايتها.",
  "minutes before the session": "دقيقة قبل الحصة",
  "No policy configured. Coach emergency contact access is disabled.":
    "لم تُضبط سياسة بعد. إتاحة جهات اتصال الطوارئ للمدربين معطلة.",
  "Check the branch, time window and synthetic policy acknowledgement.":
    "تحقق من الفرع والفترة الزمنية والإقرار بالسياسة التجريبية.",
  "Create safety policy version": "إنشاء إصدار لسياسة السلامة",
  "Minutes before session (0–360)": "الدقائق قبل الحصة (٠–٣٦٠)",
  "Allow assigned coaches to view emergency contacts":
    "السماح للمدربين المكلّفين بعرض جهات اتصال الطوارئ",
  "I acknowledge this synthetic safety policy needs academy approval before use with real families.":
    "أقر بأن سياسة السلامة التجريبية هذه تحتاج موافقة الأكاديمية قبل استخدامها مع أسر حقيقية.",
  "Save policy version": "حفظ إصدار السياسة",
  "Training and safety instructions": "تعليمات التدريب والسلامة",
  "Share only current practical instructions needed for training. Assigned coaches see these instructions for relevant sessions.":
    "شارك التعليمات العملية الحالية اللازمة للتدريب فقط. يطّلع عليها المدربون المكلّفون بالحصص ذات الصلة.",
  "No current instructions recorded.": "لم تُسجّل تعليمات حالية.",
  Updated: "آخر تحديث",
  "Edit current instructions": "تعديل التعليمات الحالية",
  "Save instructions": "حفظ التعليمات",
  "Current training instructions": "تعليمات التدريب الحالية",
  "Up to 1,000 characters. Clear this field to remove outdated instructions. Keep medical documents and detailed health history out of this field.":
    "حتى ١٬٠٠٠ حرف. امسح هذا الحقل لإزالة التعليمات القديمة. لا تُدرج مستندات طبية أو تفاصيل السجل الصحي في هذا الحقل.",
  "Next training target": "هدف التدريب التالي",
  "A practical next step linked to this assessment. Families see it after academy review and publication.":
    "خطوة عملية تالية مرتبطة بهذا التقييم. تظهر للأسرة بعد مراجعة الأكاديمية ونشر التقييم.",
  "Progression reversed": "تم التراجع عن التقدم المعتمد",
  "Reverse approved progression": "التراجع عن التقدم المعتمد",
  "Restores the previous sport level and withdraws related certificates. No class enrollment is created or changed.":
    "يعيد المستوى الرياضي السابق ويسحب الشهادات المرتبطة به. لا يُنشأ أي تسجيل في الحصص ولا يتغير التسجيل الحالي.",
  "Family-facing correction reason": "سبب التصحيح الظاهر للأسرة",
  "Certificate withdrawn": "تم سحب الشهادة",
  "Reissue certificate": "إعادة إصدار الشهادة",
  "The replacement gets a new reference. Earlier versions remain in the history and cannot be downloaded.":
    "تحصل الشهادة البديلة على رقم مرجعي جديد. تبقى النسخ السابقة في السجل ولا يمكن تنزيلها.",
  "Edit report summary": "تعديل ملخص التقرير",
  "Edit the draft using the review feedback, then submit it again.":
    "عدّل المسودة بالاستفادة من ملاحظات المراجعة ثم أرسلها مجدداً.",
  "Generate evidence report": "توليد تقرير من الأدلة",
  "Generate draft": "توليد مسودة",
  "Generate a factual draft from published assessments, recorded measurements and finalized attendance. Academy review is still required.":
    "أنشئ مسودة موثّقة من التقييمات المنشورة والقياسات المسجّلة والحضور المعتمد. تظل مراجعة الأكاديمية مطلوبة.",
  "GROWING WITH PURPOSE": "ننمو بهدف واضح",
  "Coaching standards": "معايير التدريب",
  "Coaching and assessments": "التدريب والتقييمات",
  "Your sporting journey": "رحلتك الرياضية",
  "Measured progress, reviewed by the academy, kept with each athlete.":
    "تطور موثّق تراجعه الأكاديمية ويُحفظ في ملف كل رياضي.",
  "All athletes in this view": "جميع الرياضيين في هذا العرض",
  "All sports": "جميع الرياضات",
  Athlete: "الرياضي",
  "Criteria versions": "إصدارات المعايير",
  "Create criteria version": "إنشاء إصدار للمعايير",
  "Create version": "إنشاء إصدار",
  "Each revision preserves the criteria used by earlier assessments.":
    "يحتفظ كل تحديث بالمعايير المستخدمة في التقييمات السابقة.",
  "Criteria title": "عنوان المعايير",
  Version: "الإصدار",
  Metric: "القياس",
  "Metric key": "معرّف القياس",
  "Metric name": "اسم القياس",
  "Arabic metric name": "اسم القياس بالعربية",
  Unit: "الوحدة",
  Minimum: "الحد الأدنى",
  Maximum: "الحد الأعلى",
  "Better result": "النتيجة الأفضل",
  Higher: "الأعلى",
  Lower: "الأقل",
  "Higher is better": "الأعلى أفضل",
  "Lower is better": "الأقل أفضل",
  "Remove metric": "إزالة القياس",
  "Add metric": "إضافة قياس",
  "No coaching criteria configured yet.": "لم تُضبط معايير التدريب بعد.",
  "Check required fields, metric ranges and evidence.":
    "تحقق من الحقول المطلوبة ونطاقات القياس والأدلة.",
  "Could not save. Please try again.": "تعذّر الحفظ. يُرجى المحاولة مجدداً.",
  "Save draft": "حفظ المسودة",
  "No criteria are configured for this session level. Head Office must add a version before assessment.":
    "لا توجد معايير لمستوى هذه الحصة. يجب أن تضيف الإدارة إصداراً قبل التقييم.",
  "Edit assessment draft": "تعديل مسودة التقييم",
  "Assess athlete": "تقييم الرياضي",
  "Criteria version": "إصدار المعايير",
  "Family-facing progress summary": "ملخص التطور المعروض للعائلة",
  "Internal coach note": "ملاحظة داخلية للمدرب",
  "Only assigned coaching staff and authorized reviewers can read this note.":
    "يمكن فقط للمدربين المكلّفين والمراجعين المخوّلين قراءة هذه الملاحظة.",
  "Recommended next level": "المستوى التالي المقترح",
  "No recommendation": "لا يوجد اقتراح",
  "Your assigned sessions": "حصصك المكلّف بها",
  "Session plan": "خطة الحصة",
  "Session objectives": "أهداف الحصة",
  "Planned activities": "الأنشطة المخططة",
  "No current assigned sessions are available.":
    "لا توجد حصص مكلّف بها حالياً.",
  "Assessment opens when the session starts.": "يُتاح التقييم عند بدء الحصة.",
  "Progress assessments": "تقييمات التطور",
  Review: "المراجعة",
  "Review decision": "قرار المراجعة",
  Approve: "اعتماد",
  "Return for revision": "إعادة للتعديل",
  "Internal review reason": "سبب المراجعة الداخلي",
  "Submit for review": "إرسال للمراجعة",
  "Review assessment": "مراجعة التقييم",
  "Publish to family": "نشر للعائلة",
  "Approve level progression": "اعتماد الانتقال إلى المستوى التالي",
  "Family-facing approval reason": "سبب الاعتماد المعروض للعائلة",
  "Issue achievement certificate": "إصدار شهادة إنجاز",
  "Certificate title": "عنوان الشهادة",
  "No progress assessments in this view yet.":
    "لا توجد تقييمات تطور في هذا العرض بعد.",
  "Personal bests": "أفضل النتائج الشخصية",
  "Real measurements stay in their original unit and criteria version.":
    "تُحفظ القياسات الفعلية بوحدتها الأصلية وإصدار المعايير المستخدم.",
  "Published measurements will appear here.": "ستظهر القياسات المنشورة هنا.",
  "Sport level history": "سجل المستويات الرياضية",
  "Approved level changes will appear here. Class changes are arranged separately.":
    "ستظهر تغييرات المستوى المعتمدة هنا. تُرتّب تغييرات الصف بشكل منفصل.",
  "Monthly reports": "التقارير الشهرية",
  "Create monthly report": "إنشاء تقرير شهري",
  "Assigned session": "الحصة المكلّف بها",
  "Report month": "شهر التقرير",
  "Published evidence": "الأدلة المنشورة",
  "No published assessments for this athlete, sport and month.":
    "لا توجد تقييمات منشورة لهذا الرياضي والرياضة والشهر.",
  "Family-facing monthly summary": "الملخص الشهري المعروض للعائلة",
  "Evidence assessments": "التقييمات الداعمة",
  "Published assessment": "تقييم منشور",
  "Submit report for review": "إرسال التقرير للمراجعة",
  "Review monthly report": "مراجعة التقرير الشهري",
  "Publish report to family": "نشر التقرير للعائلة",
  "No monthly reports in this view yet.":
    "لا توجد تقارير شهرية في هذا العرض بعد.",
  "Create a new report version using the review feedback.":
    "أنشئ إصداراً جديداً للتقرير بالاستفادة من ملاحظات المراجعة.",
  "Achievement certificates": "شهادات الإنجاز",
  "Download private PDF": "تنزيل الشهادة الخاصة بصيغة PDF",
  "Revoke certificate": "إلغاء الشهادة",
  "Family-facing revocation reason": "سبب الإلغاء المعروض للعائلة",
  "Issued certificates will appear here after academy approval.":
    "ستظهر الشهادات الصادرة هنا بعد اعتماد الأكاديمية.",
  Draft: "مسودة",
  Submitted: "مُرسل للمراجعة",
  Approved: "مُعتمد",
  Rejected: "مُعاد للتعديل",
  Published: "منشور",
  draft: "مسودة",
  submitted: "مُرسل للمراجعة",
  approved: "مُعتمد",
  rejected: "مُعاد للتعديل",
  published: "منشور",
};
