export const engagementArabic: Record<string, string> = {
  "Evidence within the challenge dates counts, including sessions before joining. Request review within 30 days after the challenge ends.":
    "تُحتسب الأدلة ضمن فترة التحدي، بما فيها الحصص السابقة للانضمام. اطلب المراجعة خلال ٣٠ يوماً بعد انتهاء التحدي.",
  "EFFORT. EVIDENCE. ENCOURAGEMENT.": "جهد موثّق وتشجيع مستمر",
  "Challenges and rewards": "التحديات والمكافآت",
  "Clear rules, reviewed achievements and non-cash academy rewards.":
    "قواعد واضحة وإنجازات مُراجَعة ومكافآت أكاديمية غير نقدية.",
  "Academy challenges": "تحديات الأكاديمية",
  "Create challenge": "إنشاء تحدٍ",
  "Rules are locked when published. Qualifying evidence must fall inside the challenge dates.":
    "تُثبّت القواعد عند النشر. يجب أن تقع الأدلة المؤهّلة ضمن فترة التحدي.",
  "Check the rule, required fields and challenge dates.":
    "تحقق من القاعدة والحقول المطلوبة وتواريخ التحدي.",
  "Level eligibility": "المستويات المؤهّلة",
  "All levels": "جميع المستويات",
  "Challenge title": "عنوان التحدي",
  "Starts at (Dubai time)": "يبدأ في (بتوقيت دبي)",
  "Ends at (Dubai time)": "ينتهي في (بتوقيت دبي)",
  "Reward rule": "قاعدة المكافأة",
  "Completion rule": "قاعدة الإنجاز",
  "Finalized attendance": "الحضور المُعتمد",
  "Published sport measurement": "قياس رياضي منشور",
  "Required attended sessions": "عدد الحصص المطلوبة",
  "Target value": "القيمة المستهدفة",
  "Transparent challenge rules": "قواعد التحدي الواضحة",
  "Create draft": "إنشاء مسودة",
  "Present or late, finalized attendance only.":
    "حضور أو تأخر، من سجلات الحضور المعتمدة فقط.",
  "Published measurements only.": "القياسات المنشورة فقط.",
  Reward: "المكافأة",
  "Publish challenge": "نشر التحدي",
  "Join challenge": "الانضمام إلى التحدي",
  "Request completion review": "طلب مراجعة الإنجاز",
  "Published challenges will appear here.": "ستظهر التحديات المنشورة هنا.",
  "Completion evidence and review": "أدلة الإنجاز ومراجعته",
  "Verified attendance": "الحضور المتحقق منه",
  "Verified measurement target": "القياس المستهدف المتحقق منه",
  "Qualification decision": "قرار التأهيل",
  "Review challenge completion": "مراجعة إنجاز التحدي",
  "Grant challenge reward": "منح مكافأة التحدي",
  "Reviewed achievements will appear here. Internal reviews stay private.":
    "ستظهر الإنجازات المعتمدة هنا. تظل المراجعات الداخلية خاصة.",
  "Reward ledger": "سجل المكافآت",
  "Badges, stars and points have no cash value. Corrections remain visible in the history.":
    "لا تحمل الشارات والنجوم والنقاط قيمة نقدية. تظل التصحيحات ظاهرة في السجل.",
  "Family reward": "مكافأة العائلة",
  "Family-facing reason": "السبب المعروض للعائلة",
  "Reverse reward": "عكس المكافأة",
  "No reward grants in this view yet.":
    "لا توجد مكافآت ممنوحة في هذا العرض بعد.",
  "Approved recognition rewards": "مكافآت التقدير المعتمدة",
  "Rewards reference the academy recognition review. No second nomination is created.":
    "تستند المكافآت إلى مراجعة التقدير في الأكاديمية. لا يُنشأ ترشيح آخر.",
  "Reward already recorded": "سُجّلت المكافأة بالفعل",
  "Grant recognition reward": "منح مكافأة التقدير",
  "Family referrals": "إحالات العائلات",
  "Referral credit requires another family’s first fully paid membership after code entry, followed by academy review. No cash payout.":
    "يتطلب استحقاق الإحالة أول عضوية مدفوعة بالكامل لعائلة أخرى بعد إدخال الرمز، ثم مراجعة الأكاديمية. لا توجد دفعات نقدية.",
  "Publish referral campaign": "نشر حملة الإحالة",
  "Get family referral code": "الحصول على رمز إحالة العائلة",
  "Your referral code": "رمز الإحالة الخاص بك",
  "Enter a referral code": "إدخال رمز إحالة",
  "Referral code": "رمز الإحالة",
  "Referral qualification": "تأهيل الإحالة",
  "Qualification checks the net paid amount against the first membership invoice. Discounts and credit approval do not count as payment.":
    "يتحقق التأهيل من صافي المبلغ المدفوع مقابل فاتورة العضوية الأولى. لا تُعد الخصومات أو الموافقة على الائتمان دفعات.",
  "Review referral qualification": "مراجعة تأهيل الإحالة",
  "Grant referral reward": "منح مكافأة الإحالة",
  "Configure engagement rules": "ضبط قواعد المشاركة",
  "Create non-cash reward rule": "إنشاء قاعدة مكافأة غير نقدية",
  "Stable rule code": "معرّف القاعدة الثابت",
  "Reward title": "عنوان المكافأة",
  "Transparent reward rules": "قواعد المكافأة الواضحة",
  "Qualifying source": "مصدر الاستحقاق",
  Challenge: "تحدٍ",
  "Approved recognition": "تقدير معتمد",
  "Qualified referral": "إحالة مؤهّلة",
  "Non-cash unit": "وحدة غير نقدية",
  Badge: "شارة",
  Star: "نجمة",
  Point: "نقطة",
  badge: "شارة",
  star: "نجمة",
  point: "نقطة",
  Quantity: "الكمية",
  "Publish reward rule": "نشر قاعدة المكافأة",
  "Create referral campaign": "إنشاء حملة إحالة",
  "Campaign title": "عنوان الحملة",
  "Transparent referral rules": "قواعد الإحالة الواضحة",
  "Starts at (ISO with timezone)": "وقت البدء مع المنطقة الزمنية",
  "Ends at (ISO with timezone)": "وقت الانتهاء مع المنطقة الزمنية",
  Joined: "مشارك",
  "Pending review": "بانتظار المراجعة",
  Completed: "مكتمل",
  joined: "مشارك",
  pending_review: "بانتظار المراجعة",
  completed: "مكتمل",
};
