export const managementArabic: Record<string, string> = {
  Contact: "التواصل",
  "Class workspace view": "عرض مساحة الصفوف",
  "Customer directory": "دليل العملاء",
  "Search the records loaded in this workspace":
    "ابحث في السجلات المحملة في مساحة العمل",
  "Search by name or details": "البحث بالاسم أو التفاصيل",
  "Open details": "عرض التفاصيل",
  "No matching records": "لا توجد سجلات مطابقة",
  "Try another search or load more records.":
    "جرّب بحثاً آخر أو حمّل المزيد من السجلات.",
  "loaded records": "سجلات محملة",
  loaded: "محمل",
  more: "إضافية",
  "Previous page": "الصفحة السابقة",
  "Next page": "الصفحة التالية",
  "Session calendar": "تقويم الحصص",
  "Previous period": "الفترة السابقة",
  "Next period": "الفترة التالية",
  "Calendar date": "تاريخ التقويم",
  "Calendar view": "عرض التقويم",
  Week: "أسبوع",
  Day: "يوم",
  "Search sessions": "البحث في الحصص",
  "Search class, coach or venue": "ابحث عن الصف أو المدرب أو المرفق",
  "No loaded sessions": "لا توجد حصص محملة",
  "Class catalogue": "دليل الصفوف",
  "Sport / Level": "الرياضة / المستوى",
  "Coach / Venue": "المدرب / المرفق",
  "Trial admissions": "القبول والتجارب",
  "Trial session": "حصة تجريبية",
  "Awaiting booking": "بانتظار الحجز",
  "Manage trial": "إدارة التجربة",
  "Age not recorded": "العمر غير مسجل",
  "Session register": "سجل الحصص",
  "Date / Time": "التاريخ / الوقت",
  Roster: "قائمة الطلاب",
  Enrollments: "التسجيلات",
  finalized: "مؤكد",

  "Start a membership": "بدء عضوية",
  "Open branches": "فتح الفروع",
  "Central finance": "المالية المركزية",
  "Branch finance": "مالية الفرع",
  "Collections in period": "تحصيلات الفترة",
  "Customer balance · current": "رصيد العملاء الحالي",
  "Approved earnings in period": "المستحقات المعتمدة خلال الفترة",
  "Coach payouts in period": "دفعات المدربين خلال الفترة",
  "Coach balance · current": "رصيد المدربين الحالي",
  session: "لكل حصة",
  hour: "لكل ساعة",
  month: "شهرياً",
  Next: "التالي",
  Previous: "السابق",
  Allowance: "عدد الحصص",
  Actions: "الإجراءات",
  Recorded: "مسجّل",
  Administration: "الإدارة المركزية",
  Customers: "العملاء",
  Users: "المستخدمون",
  Coaches: "المدربون",
  "Branch overview": "نظرة عامة على الفرع",
  "Back to central administration": "العودة إلى الإدارة المركزية",
  "Trials & admissions": "التجارب والتسجيل",
  "Add branch": "إضافة فرع",
  "Manage branch": "إدارة الفرع",
  "Find a branch": "البحث عن فرع",
  "Branch name": "اسم الفرع",
  "Branch details": "بيانات الفرع",
  "Branch code": "رمز الفرع",
  "Branch activities": "أنشطة الفرع",
  "Open branch": "فتح الفرع",
  "Details pending confirmation": "البيانات بانتظار التأكيد",
  "New branches start provisional. Confirm details before offering classes.":
    "تبدأ الفروع الجديدة بحالة مؤقتة. أكّد البيانات قبل تقديم الحصص.",
  "Open a branch to manage its customers, classes, collections and team.":
    "افتح الفرع لإدارة عملائه وحصصه وتحصيلاته وفريقه.",
  "Facilities and operating hours": "المرافق وساعات العمل",
  "Venues and operating hours": "المواقع وساعات العمل",
  "Venue details": "بيانات الموقع",
  "Edit venue": "تعديل الموقع",
  "Register customer": "تسجيل عميل",
  "Parent and child": "ولي الأمر والطفل",
  "Register in this branch": "التسجيل في هذا الفرع",
  "Mobile number": "رقم الهاتف المتحرك",
  "Assessment pending": "بانتظار التقييم",
  "Package configuration": "إعدادات الباقة",
  "Search packages": "البحث عن باقة",
  "Branch availability and price": "التوفر والسعر حسب الفرع",
  "Branch availability controls new sales and renewals. Purchased memberships keep their agreed benefits.":
    "يتحكم توفر الباقة بالمبيعات والتجديدات الجديدة. تحتفظ العضويات المشتراة بمزاياها المتفق عليها.",
  "Default price (AED)": "السعر الأساسي (درهم)",
  "Branch price (AED)": "سعر الفرع (درهم)",
  "Duration (months)": "المدة (بالأشهر)",
  "Save branch offers": "حفظ عروض الفروع",
  "Edit availability": "تعديل التوفر",
  "Available for new sales and renewals": "متاحة للمبيعات والتجديدات الجديدة",
  "Saving creates a new offer version. Existing memberships and invoices are unchanged.":
    "ينشئ الحفظ نسخة جديدة من العرض. تبقى العضويات والفواتير الحالية كما هي.",
  "This existing contract is preserved. Create a catalogue package to configure multiple branches.":
    "يبقى العقد الحالي محفوظاً. أنشئ باقة في الكتالوج لإعداد عروض عدة فروع.",
  "Search coaches": "البحث عن مدرب",
  "Coach management": "إدارة المدربين",
  "Manage coach": "إدارة المدرب",
  "Add coach / invite account": "إضافة مدرب / دعوة مستخدم",
  "Coach details": "بيانات المدرب",
  "Compensation basis": "أساس التعويض",
  "Earnings and payments": "المستحقات والمدفوعات",
  Agreements: "الاتفاقيات",
  Assignments: "التكليفات",
  "Assign branch and activity": "تعيين الفرع والنشاط",
  "Add effective agreement": "إضافة اتفاقية محددة المدة",
  "Activity (optional)": "النشاط (اختياري)",
  "Venue (optional)": "الموقع (اختياري)",
  "Any venue": "أي موقع",
  "Payment basis": "أساس الدفع",
  "Per completed session": "لكل حصة مكتملة",
  "Per delivered hour": "لكل ساعة منفذة",
  "Fixed calendar month": "شهر تقويمي ثابت",
  "Rate (AED)": "المعدل (درهم)",
  "Effective until (exclusive)": "سارية حتى (دون احتساب هذا اليوم)",
  "Substitute coaching": "التدريب البديل",
  "Pay the actual delivering coach": "الدفع للمدرب الذي نفّذ الحصة",
  "Exclude substitute delivery": "استبعاد الحصص البديلة",
  "Cancelled sessions are unpaid. Monthly agreements require a full completed calendar month; no automatic proration.":
    "الحصص الملغاة غير مدفوعة. تتطلب الاتفاقية الشهرية شهراً تقويمياً مكتملاً؛ لا يُحسب جزء من الشهر تلقائياً.",
  "Calculate completed month": "احتساب الشهر المكتمل",
  "Deactivation preserves history. Future classes must be reassigned.":
    "يحفظ التعطيل السجل السابق. يجب إعادة تعيين الحصص القادمة.",
  "Reassignment required": "مطلوب إعادة التعيين",
  "Manage classes": "إدارة الحصص",
  "Coach / work": "المدرب / العمل",
  "Review earnings": "مراجعة المستحقات",
  "Record payout": "تسجيل دفعة للمدرب",
  "No earnings recorded for this selection.":
    "لا توجد مستحقات مسجلة لهذا الاختيار.",
  Earned: "المستحق",
  "Record an offline payment already made. This does not transfer money.":
    "سجّل دفعة تمت خارج المنصة. لا تؤدي هذه العملية إلى تحويل أموال.",
  "Record money already received. No online charge is made.":
    "سجّل مبلغاً تم استلامه بالفعل. لا يتم تحصيل أي مبلغ إلكترونياً.",
  "Coach payouts": "دفعات المدربين",
  "Coach cost": "تكلفة المدربين",
  "Customer balance": "رصيد العملاء",
  "Complete authorized totals. Detail pagination does not change these figures.":
    "إجماليات كاملة ضمن صلاحياتك. لا تتغير بتصفح صفحات التفاصيل.",
  "Open branch finance": "فتح مالية الفرع",
  "Finance views": "الأقسام المالية",
  "Find customer or invoice": "البحث عن عميل أو فاتورة",
  "No matching invoices": "لا توجد فواتير مطابقة",
  Exceptions: "الاستثناءات",
  "For reviewed adjustments, refunds and unallocated payments only.":
    "للتسويات والمبالغ المستردة والمدفوعات غير المخصصة بعد مراجعتها فقط.",
  "Invoice details": "تفاصيل الفاتورة",
  "Invoice paid. Receipt available in Receipts.":
    "تم سداد الفاتورة. الإيصال متاح في قسم الإيصالات.",
  "Record payment and receipt": "تسجيل الدفعة والإيصال",
  "Search users": "البحث عن مستخدم",
  "Invite staff or coach": "دعوة موظف أو مدرب",
  "Advanced permissions": "الصلاحيات المتقدمة",
  "Could not save. Please try again.": "تعذر الحفظ. يرجى المحاولة مجدداً.",
};
