export const productArabic: Record<string, string> = {
  "Event date cancelled": "إلغاء أحد مواعيد الفعالية",
  "Event attendance ready": "سجل حضور الفعالية جاهز",
  "Your selected children are registered for all scheduled event dates.":
    "تم تسجيل أطفالك المحددين في جميع مواعيد الفعالية المجدولة.",
  "Your event registration was cancelled.": "تم إلغاء تسجيلك في الفعالية.",
  "One date in your event timetable has been cancelled. Other dates are unchanged.":
    "تم إلغاء أحد مواعيد الفعالية. بقية المواعيد لم تتغير.",
  "The attendance register for one event date is ready.":
    "أصبح سجل الحضور لأحد مواعيد الفعالية جاهزاً.",
  "Membership cancelled": "تم إلغاء العضوية",
  "The cancellation record and invoice credit are available. Any offline refund is recorded separately.":
    "يمكنك الاطلاع على سجل الإلغاء والرصيد الدائن للفاتورة. تُسجّل أي مبالغ مستردة خارج المنصة بشكل منفصل.",

  "Active enrollments": "التسجيلات النشطة",
  "Manage waitlist": "إدارة قائمة الانتظار",
  "Open trial queue": "فتح قائمة التجارب",
  "This page couldn’t load": "تعذّر تحميل هذه الصفحة",
  "No records have been loaded. Retry to see the current workspace.":
    "لم يتم تحميل أي سجلات. أعد المحاولة لعرض مساحة العمل الحالية.",
  "Your assignments determine student access. Attendance actions follow the academy’s granted permissions.":
    "تحدد تكليفاتك وصولك إلى الطلاب. تخضع إجراءات الحضور للصلاحيات التي تمنحها الأكاديمية.",
  "Front desk today": "الاستقبال اليوم",
  "Action centre": "مركز الإجراءات",
  "Reception actions": "إجراءات الاستقبال",
  "Find a family": "البحث عن عائلة",
  "Capture enquiry": "تسجيل استفسار",
  "Book makeup": "حجز حصة تعويضية",
  "IN PROGRESS": "حصة جارية",
  "NEXT ARRIVALS": "القادمون للحصة التالية",
  Arrived: "حضروا",
  "Awaiting check-in": "بانتظار تسجيل الحضور",
  "Trial places": "أماكن التجربة",
  "Open session roster": "فتح قائمة الحصة",
  "Review the roster before marking attendance. No arrivals are recorded automatically.":
    "راجع القائمة قبل تسجيل الحضور. لا يُسجّل حضور أي طالب تلقائياً.",
  "Expected arrivals": "الحضور المتوقع",
  "No expected participants in this session.":
    "لا يوجد مشاركون متوقعون في هذه الحصة.",
  "Open full roster": "فتح القائمة الكاملة",
  "Keep the shift moving": "متابعة أعمال المناوبة",
  "Attendance unresolved": "حضور بانتظار الاعتماد",
  "Started sessions awaiting finalization": "حصص بدأت وتنتظر اعتماد الحضور",
  "Open shift handover": "فتح تسليم المناوبة",
  "Based on permitted loaded records. Open the relevant workspace for the full queue.":
    "بناءً على السجلات المحمّلة ضمن صلاحياتك. افتح القسم المعني لعرض القائمة الكاملة.",
  "Renewals within seven days": "تجديدات خلال سبعة أيام",
  "PRIORITIES BEFORE NUMBERS": "الأولويات قبل الأرقام",
  "The next right action": "الإجراء التالي المناسب",
  "Action queues": "قوائم الإجراءات",
  "This queue is clear": "لا توجد إجراءات معلّقة",
  "No pending actions in the loaded records.":
    "لا توجد إجراءات معلّقة في السجلات المحمّلة.",
  "Showing the first five records.": "يتم عرض أول خمسة سجلات.",
  "Today’s operating timeline": "الجدول التشغيلي لليوم",
  "Branch activity": "نشاط الفروع",
  "Today’s sessions and expected arrivals, by permitted branch.":
    "حصص اليوم والحضور المتوقع حسب الفروع المسموح بها.",
  Expected: "المتوقع",
  "No operational records in the selected branch.":
    "لا توجد سجلات تشغيلية في الفرع المحدد.",
  "Use the branch filter above to inspect its source records.":
    "استخدم مرشح الفرع أعلاه للاطلاع على سجلاته الأصلية.",

  "Loading selected record…": "جارٍ تحميل السجل المحدد…",
  "More related records are available for this selection.":
    "توجد سجلات إضافية مرتبطة بهذا الاختيار.",
  "Load more related records": "تحميل المزيد من السجلات المرتبطة",
  Home: "الرئيسية",
  Schedule: "الجدول",
  Progress: "التطور",
  More: "المزيد",
  Today: "اليوم",
  Students: "الطلاب",
  Assessments: "التقييمات",
  Updates: "التحديثات",
  Events: "الفعاليات",
  "Unread updates": "تحديثات غير مقروءة",
  "Makeup credits": "أرصدة الحصص التعويضية",
  "Assessments awaiting review": "تقييمات بانتظار المراجعة",
  "Open support conversations": "محادثات الدعم المفتوحة",
  "Invoices with a balance": "فواتير برصيد مستحق",
  "Connected family actions": "إجراءات العائلة",
  "Valid until": "سارية حتى",
  "sessions available": "حصص متاحة",
  "Outstanding in loaded records": "المستحق في السجلات المحمّلة",
  "Financial and operational permissions": "الصلاحيات المالية والتشغيلية",
  "These grants are separate from workspace roles and branch access. Revocation is checked on every request.":
    "هذه الصلاحيات منفصلة عن أدوار مساحات العمل والوصول للفروع. يتم التحقق من إلغائها عند كل طلب.",
  "Grant capability": "منح صلاحية",
  "Staff account": "حساب الموظف",
  Permission: "الصلاحية",
  "Branch (blank means all permitted branches)":
    "الفرع (اتركه فارغاً لجميع الفروع المسموح بها)",
  Saved: "تم الحفظ",
  Revoke: "إلغاء الصلاحية",
  "Communication centre": "مركز التواصل",
  "In-app messages are delivered to verified linked guardians. Email, WhatsApp and push remain not configured.":
    "تصل رسائل المنصة إلى أولياء الأمور الموثّقين المرتبطين بالعائلة. البريد الإلكتروني وواتساب والإشعارات الخارجية غير مهيأة.",
  "Broadcast permission required": "يلزم تصريح إرسال الرسائل الجماعية",
  "Security administration can grant this permission separately.":
    "يمكن لمسؤول الأمان منح هذه الصلاحية بشكل مستقل.",
  "Create a template version": "إنشاء إصدار من القالب",
  "New message template": "قالب رسالة جديد",
  "Template name": "اسم القالب",
  Language: "اللغة",
  English: "الإنجليزية",
  Arabic: "العربية",
  Operational: "تشغيلي",
  "Optional marketing": "تسويق اختياري",
  "Preview recipients": "معاينة المستلمين",
  Choose: "اختر",
  "Message template": "قالب الرسالة",
  "Load recipient preview": "عرض المستلمين",
  "eligible guardians": "من أولياء الأمور المؤهلين",
  "Eligibility and consent are checked again at delivery. No external messages will be sent.":
    "تتم إعادة التحقق من الأهلية والموافقة عند الإرسال. لن تُرسل رسائل خارجية.",
  "I reviewed the message and recipients.": "راجعت الرسالة وقائمة المستلمين.",
  "Scheduled time (UAE)": "موعد الإرسال (توقيت الإمارات)",
  "Schedule in-app message": "جدولة رسالة داخل المنصة",
  "in-app deliveries": "رسائل تم تسليمها داخل المنصة",
  "Deliver when due": "إرسال عند حلول الموعد",
  "Cancel scheduled message": "إلغاء الرسالة المجدولة",
  "Scheduled messages require an authorized operator to run delivery. Automatic job activation is tracked separately.":
    "يتولى موظف مخوّل تنفيذ إرسال الرسائل المجدولة. تفعيل الإرسال التلقائي إجراء منفصل.",
  "Private documents": "المستندات الخاصة",
  "PDF, PNG or JPEG, up to 512 KB. Files stay within the authorized family and reception team. Uploading is not signing a waiver.":
    "ملفات PDF أو PNG أو JPEG حتى 512 كيلوبايت. تقتصر إتاحة الملفات على العائلة وفريق الاستقبال المخوّلين. رفع الملف لا يُعد توقيعاً على إقرار.",
  "Choose a file up to 512 KB.": "اختر ملفاً لا يتجاوز 512 كيلوبايت.",
  "Document saved.": "تم حفظ المستند.",
  "Family document": "مستند للعائلة",
  "Share with reception at branch (optional)":
    "المشاركة مع استقبال الفرع (اختياري)",
  "Family only": "العائلة فقط",
  Document: "المستند",
  Download: "تنزيل",
  "Access withdrawn.": "تم سحب حق الوصول.",
  "Withdraw access": "سحب حق الوصول",
  "Upload private document": "رفع مستند خاص",
  "Uploading…": "جارٍ الرفع…",
  "Withdrawal immediately stops downloads. Retention and deletion requests are reviewed by the academy; no medical or identity documents should be used in this synthetic staging environment.":
    "يمنع سحب الوصول التنزيل فوراً. تراجع الأكاديمية طلبات الاحتفاظ والحذف؛ لا تستخدم مستندات طبية أو هويات حقيقية في هذه البيئة التجريبية.",
  "Leave this page and discard unsaved changes?":
    "هل تريد مغادرة الصفحة وتجاهل التغييرات غير المحفوظة؟",
  "Showing the last loaded records. Refresh before taking action.":
    "يتم عرض آخر سجلات محمّلة. حدّث الصفحة قبل اتخاذ إجراء.",
  "Child context": "الطفل المحدد",
  "Each child has their own sport, level and journey.":
    "لكل طفل رياضته ومستواه ومسيرته الخاصة.",
  years: "سنوات",
  Email: "البريد الإلكتروني",
  ready: "متاح",
  withdrawn: "تم سحب الوصول",
  pending: "قيد الانتظار",
  Memberships: "العضويات",
  Finance: "المالية",
  Makeups: "الحصص التعويضية",
  Reports: "التقارير",
  Certificates: "الشهادات",
  Recognition: "التكريم",
  Engagement: "المشاركة",
  Support: "الدعم",
  "Family access": "الوصول للعائلة",
  Documents: "المستندات",
  Notifications: "الإشعارات",
  Coaching: "التدريب",
  Packages: "الباقات",
  Compensation: "مستحقات المدرّبين",
  Criteria: "المعايير",
  Handover: "تسليم المناوبة",
  Communications: "التواصل",
  "Academy operations": "عمليات الأكاديمية",
  "Family and development": "العائلة والتطور",
  "Business and governance": "الأعمال والحوكمة",
  "Next session": "الحصة القادمة",
  "View schedule": "عرض الجدول",
  "No upcoming session": "لا توجد حصة قادمة",
  "New availability appears here after a confirmed booking.":
    "تظهر هنا الحصص القادمة بعد تأكيد الحجز.",
  "Latest published feedback": "أحدث الملاحظات المنشورة",
  "Read progress": "عرض التطور",
  "UAE time": "توقيت الإمارات",
  "Arrival and venue details": "تفاصيل الحضور والمكان",
};
