-- Scope each relationship before pagination while retaining caller RLS, including security-invoker views.
create or replace function public.branch_records(p_table text,p_branch uuid,p_offset integer default 0) returns jsonb language plpgsql security invoker set search_path='' as $$
declare predicate text; result jsonb; begin
 if not private.active() or not private.branch_access(p_branch) then raise exception 'Branch access denied' using errcode='42501';end if;
 if p_offset<0 or p_offset>100000 then raise exception 'Invalid record request' using errcode='22023';end if;
 predicate:=case p_table
when 'academy_classes' then 't.branch_id=$1'
when 'academy_events' then 't.branch_id=$1'
when 'academy_policies' then 't.branch_id=$1'
when 'age_groups' then 'true'
when 'attendance_corrections' then 'exists(select 1 from public.session_roster p0 where p0.id=t.roster_id and (exists(select 1 from public.class_sessions p1 where p1.id=p0.session_id and (exists(select 1 from public.academy_classes p2 where p2.id=p1.class_id and (p2.branch_id=$1))))))'
when 'audit_events' then 'false'
when 'branch_permissions' then 't.branch_id=$1'
when 'branch_sports' then 't.branch_id=$1'
when 'branches' then 't.id=$1'
when 'child_sports' then 'exists(select 1 from public.children p0 where p0.id=t.child_id and (exists(select 1 from public.families p1 where p1.id=p0.family_id and (exists(select 1 from public.family_branches fb where fb.family_id=p1.id and fb.branch_id=$1)))))'
when 'children' then 'exists(select 1 from public.families p0 where p0.id=t.family_id and (exists(select 1 from public.family_branches fb where fb.family_id=p0.id and fb.branch_id=$1)))'
when 'class_sessions' then 'exists(select 1 from public.academy_classes p0 where p0.id=t.class_id and (p0.branch_id=$1))'
when 'coach_assignments' then 't.branch_id=$1'
when 'coach_availability' then 't.branch_id=$1'
when 'coach_conversations' then 'exists(select 1 from public.enrollments p0 where p0.id=t.enrollment_id and (exists(select 1 from public.academy_classes p1 where p1.id=p0.class_id and (p1.branch_id=$1))))'
when 'coach_message_policies' then 't.branch_id=$1'
when 'coach_message_reads' then 'false'
when 'coach_messages' then 'exists(select 1 from public.coach_conversations p0 where p0.id=t.conversation_id and (exists(select 1 from public.enrollments p1 where p1.id=p0.enrollment_id and (exists(select 1 from public.academy_classes p2 where p2.id=p1.class_id and (p2.branch_id=$1))))))'
when 'coach_substitutions' then 'exists(select 1 from public.class_sessions p0 where p0.id=t.session_id and (exists(select 1 from public.academy_classes p1 where p1.id=p0.class_id and (p1.branch_id=$1))))'
when 'commercial_adjustments' then 'exists(select 1 from public.commercial_invoices p0 where p0.id=t.invoice_id and (p0.branch_id=$1))'
when 'commercial_allocations' then 'exists(select 1 from public.commercial_invoices p0 where p0.id=t.invoice_id and (p0.branch_id=$1))'
when 'commercial_cancellation_previews' then 'exists(select 1 from public.commercial_memberships p0 where p0.id=t.membership_id and (p0.branch_id=$1))'
when 'commercial_compensation_accruals' then 't.branch_id=$1'
when 'commercial_compensation_rates' then 't.branch_id=$1'
when 'commercial_compensation_settlements' then 't.branch_id=$1'
when 'commercial_credit_approvals' then 'exists(select 1 from public.commercial_invoices p0 where p0.id=t.invoice_id and (p0.branch_id=$1))'
when 'commercial_freezes' then 'exists(select 1 from public.commercial_memberships p0 where p0.id=t.membership_id and (p0.branch_id=$1))'
when 'commercial_invoice_lines' then 'exists(select 1 from public.commercial_invoices p0 where p0.id=t.invoice_id and (p0.branch_id=$1))'
when 'commercial_invoices' then 't.branch_id=$1'
when 'commercial_membership_cancellations' then 'exists(select 1 from public.commercial_memberships p0 where p0.id=t.membership_id and (p0.branch_id=$1))'
when 'commercial_membership_extensions' then 'exists(select 1 from public.commercial_memberships p0 where p0.id=t.membership_id and (p0.branch_id=$1))'
when 'commercial_memberships' then 't.branch_id=$1'
when 'commercial_packages' then 't.branch_id=$1'
when 'commercial_payments' then 't.branch_id=$1'
when 'commercial_receipts' then 'exists(select 1 from public.commercial_payments p0 where p0.id=t.payment_id and (p0.branch_id=$1))'
when 'commercial_refunds' then 'exists(select 1 from public.commercial_payments p0 where p0.id=t.payment_id and (p0.branch_id=$1))'
when 'commercial_renewal_reminders' then 'exists(select 1 from public.commercial_memberships p0 where p0.id=t.membership_id and (p0.branch_id=$1))'
when 'communication_batches' then 't.branch_id=$1'
when 'communication_recipients' then 'exists(select 1 from public.communication_batches p0 where p0.id=t.batch_id and (p0.branch_id=$1))'
when 'communication_templates' then 'true'
when 'consent_records' then 'exists(select 1 from public.families p0 where p0.id=t.family_id and (exists(select 1 from public.family_branches fb where fb.family_id=p0.id and fb.branch_id=$1)))'
when 'delivery_outbox' then 'exists(select 1 from public.product_events p0 where p0.id=t.event_id and (p0.branch_id=$1))'
when 'development_assessment_notes' then '(exists(select 1 from public.development_assessments p0 where p0.id=t.assessment_id and (exists(select 1 from public.class_sessions p1 where p1.id=p0.session_id and (exists(select 1 from public.academy_classes p2 where p2.id=p1.class_id and (p2.branch_id=$1)))))))'
when 'development_assessments' then 'exists(select 1 from public.class_sessions p0 where p0.id=t.session_id and (exists(select 1 from public.academy_classes p1 where p1.id=p0.class_id and (p1.branch_id=$1))))'
when 'development_automation_policies' then 't.branch_id=$1'
when 'development_certificate_records' then 't.branch_id=$1'
when 'development_certificate_revocations' then 'exists(select 1 from public.development_certificates p0 where p0.id=t.certificate_id and ((exists(select 1 from public.development_assessments p1 where p1.id=p0.assessment_id and (exists(select 1 from public.class_sessions p2 where p2.id=p1.session_id and (exists(select 1 from public.academy_classes p3 where p3.id=p2.class_id and (p3.branch_id=$1)))))))))'
when 'development_certificates' then '(exists(select 1 from public.development_assessments p0 where p0.id=t.assessment_id and (exists(select 1 from public.class_sessions p1 where p1.id=p0.session_id and (exists(select 1 from public.academy_classes p2 where p2.id=p1.class_id and (p2.branch_id=$1)))))))'
when 'development_coach_emergency_contacts' then 'exists(select 1 from public.class_sessions p0 where p0.id=t.session_id and (exists(select 1 from public.academy_classes p1 where p1.id=p0.class_id and (p1.branch_id=$1))))'
when 'development_criteria' then 'true'
when 'development_emergency_policies' then 't.branch_id=$1'
when 'development_level_history' then '(exists(select 1 from public.development_assessments p0 where p0.id=t.assessment_id and (exists(select 1 from public.class_sessions p1 where p1.id=p0.session_id and (exists(select 1 from public.academy_classes p2 where p2.id=p1.class_id and (p2.branch_id=$1)))))))'
when 'development_level_reversals' then 'exists(select 1 from public.development_level_history p0 where p0.id=t.history_id and ((exists(select 1 from public.development_assessments p1 where p1.id=p0.assessment_id and (exists(select 1 from public.class_sessions p2 where p2.id=p1.session_id and (exists(select 1 from public.academy_classes p3 where p3.id=p2.class_id and (p3.branch_id=$1)))))))))'
when 'development_reports' then 'exists(select 1 from public.class_sessions p0 where p0.id=t.session_id and (exists(select 1 from public.academy_classes p1 where p1.id=p0.class_id and (p1.branch_id=$1))))'
when 'development_results' then '(exists(select 1 from public.development_assessments p0 where p0.id=t.assessment_id and (exists(select 1 from public.class_sessions p1 where p1.id=p0.session_id and (exists(select 1 from public.academy_classes p2 where p2.id=p1.class_id and (p2.branch_id=$1)))))))'
when 'development_reviews' then '(exists(select 1 from public.development_assessments p0 where p0.id=t.assessment_id and (exists(select 1 from public.class_sessions p1 where p1.id=p0.session_id and (exists(select 1 from public.academy_classes p2 where p2.id=p1.class_id and (p2.branch_id=$1)))))) or exists(select 1 from public.development_reports p0 where p0.id=t.report_id and (exists(select 1 from public.class_sessions p1 where p1.id=p0.session_id and (exists(select 1 from public.academy_classes p2 where p2.id=p1.class_id and (p2.branch_id=$1)))))))'
when 'development_safety_children' then 'exists(select 1 from public.children p0 where p0.id=t.id and (exists(select 1 from public.families p1 where p1.id=p0.family_id and (exists(select 1 from public.family_branches fb where fb.family_id=p1.id and fb.branch_id=$1)))))'
when 'development_safety_instructions' then 'exists(select 1 from public.children p0 where p0.id=t.child_id and (exists(select 1 from public.families p1 where p1.id=p0.family_id and (exists(select 1 from public.family_branches fb where fb.family_id=p1.id and fb.branch_id=$1)))))'
when 'development_session_plans' then 'exists(select 1 from public.class_sessions p0 where p0.id=t.session_id and (exists(select 1 from public.academy_classes p1 where p1.id=p0.class_id and (p1.branch_id=$1))))'
when 'development_target_events' then 'exists(select 1 from public.development_targets p0 where p0.id=t.target_id and (exists(select 1 from public.class_sessions p1 where p1.id=p0.session_id and (exists(select 1 from public.academy_classes p2 where p2.id=p1.class_id and (p2.branch_id=$1))))))'
when 'development_target_reviews' then 'exists(select 1 from public.development_targets p0 where p0.id=t.target_id and (exists(select 1 from public.class_sessions p1 where p1.id=p0.session_id and (exists(select 1 from public.academy_classes p2 where p2.id=p1.class_id and (p2.branch_id=$1))))))'
when 'development_targets' then 'exists(select 1 from public.class_sessions p0 where p0.id=t.session_id and (exists(select 1 from public.academy_classes p1 where p1.id=p0.class_id and (p1.branch_id=$1))))'
when 'document_acceptances' then 'exists(select 1 from public.families p0 where p0.id=t.family_id and (exists(select 1 from public.family_branches fb where fb.family_id=p0.id and fb.branch_id=$1)))'
when 'document_versions' then 'true'
when 'engagement_challenges' then 't.branch_id=$1'
when 'engagement_completions' then 'exists(select 1 from public.engagement_entries p0 where p0.id=t.entry_id and (exists(select 1 from public.engagement_challenges p1 where p1.id=p0.challenge_id and (p1.branch_id=$1))))'
when 'engagement_entries' then 'exists(select 1 from public.engagement_challenges p0 where p0.id=t.challenge_id and (p0.branch_id=$1))'
when 'engagement_referral_campaigns' then 't.branch_id=$1'
when 'engagement_referral_claims' then 'exists(select 1 from public.engagement_referral_codes p0 where p0.id=t.code_id and (exists(select 1 from public.engagement_referral_campaigns p1 where p1.id=p0.campaign_id and (p1.branch_id=$1))))'
when 'engagement_referral_codes' then 'exists(select 1 from public.engagement_referral_campaigns p0 where p0.id=t.campaign_id and (p0.branch_id=$1))'
when 'engagement_reviews' then '(exists(select 1 from public.engagement_completions p0 where p0.id=t.completion_id and (exists(select 1 from public.engagement_entries p1 where p1.id=p0.entry_id and (exists(select 1 from public.engagement_challenges p2 where p2.id=p1.challenge_id and (p2.branch_id=$1)))))) or exists(select 1 from public.engagement_referral_claims p0 where p0.id=t.referral_id and (exists(select 1 from public.engagement_referral_codes p1 where p1.id=p0.code_id and (exists(select 1 from public.engagement_referral_campaigns p2 where p2.id=p1.campaign_id and (p2.branch_id=$1)))))))'
when 'engagement_reward_ledger' then '(exists(select 1 from public.engagement_completions p0 where p0.id=t.completion_id and (exists(select 1 from public.engagement_entries p1 where p1.id=p0.entry_id and (exists(select 1 from public.engagement_challenges p2 where p2.id=p1.challenge_id and (p2.branch_id=$1)))))) or exists(select 1 from public.engagement_referral_claims p0 where p0.id=t.referral_id and (exists(select 1 from public.engagement_referral_codes p1 where p1.id=p0.code_id and (exists(select 1 from public.engagement_referral_campaigns p2 where p2.id=p1.campaign_id and (p2.branch_id=$1)))))))'
when 'engagement_reward_rules' then 't.branch_id=$1'
when 'enrollments' then 'exists(select 1 from public.academy_classes p0 where p0.id=t.class_id and (p0.branch_id=$1))'
when 'entitlement_ledger' then 'exists(select 1 from public.commercial_memberships p0 where p0.id=t.membership_id and (p0.branch_id=$1))'
when 'event_attendance' then 'exists(select 1 from public.event_occurrences p0 where p0.id=t.occurrence_id and (exists(select 1 from public.academy_events p1 where p1.id=p0.event_id and (p1.branch_id=$1))))'
when 'event_attendance_corrections' then 'false'
when 'event_attendance_register' then 'exists(select 1 from public.event_occurrences p0 where p0.id=t.occurrence_id and (exists(select 1 from public.academy_events p1 where p1.id=p0.event_id and (p1.branch_id=$1))))'
when 'event_coach_directory' then 't.branch_id=$1'
when 'event_consents' then 'exists(select 1 from public.event_registrations p0 where p0.id=t.registration_id and (exists(select 1 from public.academy_events p1 where p1.id=p0.event_id and (p1.branch_id=$1))))'
when 'event_occurrences' then 'exists(select 1 from public.academy_events p0 where p0.id=t.event_id and (p0.branch_id=$1))'
when 'event_registration_batches' then 'exists(select 1 from public.academy_events p0 where p0.id=t.event_id and (p0.branch_id=$1))'
when 'event_registrations' then 'exists(select 1 from public.academy_events p0 where p0.id=t.event_id and (p0.branch_id=$1))'
when 'families' then 'exists(select 1 from public.family_branches fb where fb.family_id=t.id and fb.branch_id=$1)'
when 'family_branches' then 't.branch_id=$1'
when 'family_emergency_contacts' then 'exists(select 1 from public.families p0 where p0.id=t.family_id and (exists(select 1 from public.family_branches fb where fb.family_id=p0.id and fb.branch_id=$1)))'
when 'family_files' then 't.branch_id=$1'
when 'file_access_events' then 'exists(select 1 from public.family_files p0 where p0.id=t.file_id and (p0.branch_id=$1))'
when 'guardians' then 'exists(select 1 from public.families p0 where p0.id=t.family_id and (exists(select 1 from public.family_branches fb where fb.family_id=p0.id and fb.branch_id=$1)))'
when 'lead_activities' then 'exists(select 1 from public.leads p0 where p0.id=t.lead_id and (p0.branch_id=$1))'
when 'leads' then 't.branch_id=$1'
when 'makeup_bookings' then 'exists(select 1 from public.class_sessions p0 where p0.id=t.session_id and (exists(select 1 from public.academy_classes p1 where p1.id=p0.class_id and (p1.branch_id=$1))))'
when 'makeup_credits' then 't.branch_id=$1'
when 'notifications' then 'exists(select 1 from public.product_events p0 where p0.id=t.event_id and (p0.branch_id=$1))'
when 'operation_events' then 'exists(select 1 from public.session_roster p0 where p0.id=t.roster_id and (exists(select 1 from public.class_sessions p1 where p1.id=p0.session_id and (exists(select 1 from public.academy_classes p2 where p2.id=p1.class_id and (p2.branch_id=$1))))))'
when 'operational_acknowledgements' then 'exists(select 1 from public.class_sessions p0 where p0.id=t.session_id and (exists(select 1 from public.academy_classes p1 where p1.id=p0.class_id and (p1.branch_id=$1))))'
when 'organizations' then 'false'
when 'package_catalogue' then 'true'
when 'package_offer_versions' then 't.branch_id=$1'
when 'product_events' then 't.branch_id=$1'
when 'product_permissions' then '(t.branch_id=$1 or t.branch_id is null)'
when 'profiles' then 'exists(select 1 from public.branch_permissions bp where bp.user_id=t.id and bp.branch_id=$1)'
when 'recognition_nominations' then 't.branch_id=$1'
when 'role_assignments' then 'exists(select 1 from public.branch_permissions bp where bp.user_id=t.user_id and bp.branch_id=$1)'
when 'session_changes' then 'exists(select 1 from public.class_sessions p0 where p0.id=t.session_id and (exists(select 1 from public.academy_classes p1 where p1.id=p0.class_id and (p1.branch_id=$1))))'
when 'session_roster' then 'exists(select 1 from public.class_sessions p0 where p0.id=t.session_id and (exists(select 1 from public.academy_classes p1 where p1.id=p0.class_id and (p1.branch_id=$1))))'
when 'shift_handovers' then 't.branch_id=$1'
when 'sport_levels' then 'true'
when 'staff_invitations' then 'false'
when 'support_messages' then 'exists(select 1 from public.support_tickets p0 where p0.id=t.ticket_id and (p0.branch_id=$1))'
when 'support_tickets' then 't.branch_id=$1'
when 'transfer_decisions' then 'exists(select 1 from public.transfer_requests p0 where p0.id=t.request_id and (exists(select 1 from public.enrollments p1 where p1.id=p0.enrollment_id and (exists(select 1 from public.academy_classes p2 where p2.id=p1.class_id and (p2.branch_id=$1))))))'
when 'transfer_requests' then 'exists(select 1 from public.enrollments p0 where p0.id=t.enrollment_id and (exists(select 1 from public.academy_classes p1 where p1.id=p0.class_id and (p1.branch_id=$1))))'
when 'trial_bookings' then 'exists(select 1 from public.class_sessions p0 where p0.id=t.session_id and (exists(select 1 from public.academy_classes p1 where p1.id=p0.class_id and (p1.branch_id=$1))))'
when 'trial_enquiries' then 'exists(select 1 from public.leads p0 where p0.id=t.lead_id and (p0.branch_id=$1))'
when 'venues' then 't.branch_id=$1'
when 'waitlist_entries' then 'exists(select 1 from public.class_sessions p0 where p0.id=t.session_id and (exists(select 1 from public.academy_classes p1 where p1.id=p0.class_id and (p1.branch_id=$1))))'
 else null end;
 if predicate is null then raise exception 'Invalid record request' using errcode='22023';end if;
 execute format('select coalesce(jsonb_agg(x),''[]''::jsonb) from (select t.* from public.%I t where %s order by to_jsonb(t)::text offset $2 limit 200)x',p_table,predicate) into result using p_branch,p_offset;
 return result;
end $$;
